### ISSUE TITLE
"Loading" Indefinitely on first startup

### ISSUE THREAD

**Issue by deadformat** [Manuel-777/MTG-Arena-Tool#1]
Hi there, I'm looking forward to trying out this tracker. FYI, when I launch the tool, I get an image that says        "Loading
Just a second.."
but nothing ever loads. 

I'm on Windows 10. Thanks!

**Comment by Manuel-777** [comment]
Probably an issue with the log file, It may be found by Tool but if it can't find the user data it wont finish loading. Try restarting both MTG Arena and Tool and see if it loads then.
If that doesnt work send me the log file found at %APPDATA%\LocalLow\Wizards Of The Coast\MTGA\ at mtgatool@gmail.com so I can inspect what went wrong.
