### ISSUE TITLE
Match details show incorrect amount of cards for the opponent's deck

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#1000]
Every card was only played once not thrice.

![screenshot](https://user-images.githubusercontent.com/3404787/79645275-a45be580-81ae-11ea-9099-88054e01f571.png)

Version 4.0.14

**Comment by Manuel-777** [comment]
Aparently fixed in 4.0.18, but ill leave it open just in case

**Comment by riQQ** [comment]
Confirmed fixed, I think we can close this.
