### ISSUE TITLE
Lurrus card is missing from database

### ISSUE THREAD

**Issue by flasaracina** [Manuel-777/MTG-Arena-Tool#1008]
Hello, 
first of all I want to thank you guys because you were fast with the log fix. Nice job.
I notice that the tracker doesn't list "Lurrus of the Dream Den". In fact I own one copy of that card, but it doesn't show up in the collection tab.

For reference, this is the card:
[Lurrus of the Dream Den](https://scryfall.com/card/iko/355/lurrus-of-the-dream-den)

Thanks

**Comment by flasaracina** [comment]
As of today, everything seems OK and Lurrus is there. Maybe it was a temporary issue? I will close this isssue, anyway. Thank you for your patience

**Comment by riQQ** [comment]
Did it show the card with quantity 0 or didn't it show at all?

**Comment by flasaracina** [comment]
I had one from the sealed event but two strange things happened:

- in the "economy" tab, Lurrus had the Fblthp icon (signaling that the icon for Lurrus was missing);
- in the "collection" tab, the card was missing altogheter. It simply wasn't there.

as of today, the card is back, and it shows the correct icon even in the "economy" tab. 

Maybe it was a temporary problem? I don't know if the icons are being downloaded on the fly or saved locally by the app.

**Comment by Thaoden** [comment]
Lurrus is still missing for me, the artwork in `economy` tab as well as the card entry in `collection`.

**Comment by riQQ** [comment]
It shows correctly for me in `Collection > Card view`.

**Comment by Thaoden** [comment]
![Capture](https://user-images.githubusercontent.com/3832723/79779015-ec5b4380-8339-11ea-95c5-3225445db4ce.PNG)

**Comment by riQQ** [comment]
@Thaoden check all the filters ;)

**Comment by Thaoden** [comment]
![Capture](https://user-images.githubusercontent.com/3832723/79779982-87a0e880-833b-11ea-9f5c-102a9471d1f9.PNG)

still doesn't explain why it's not in set view.

**Comment by riQQ** [comment]
![Screenshot](https://user-images.githubusercontent.com/3404787/79784904-414f8780-8343-11ea-9cbe-74355d82da9f.png)

**Comment by Thaoden** [comment]
🤷‍♂️
