### ISSUE TITLE
4.0.17 Error in History Win and Losses indicated in incorrect way

### ISSUE THREAD

**Issue by LuckyBlack72** [Manuel-777/MTG-Arena-Tool#1010]
![image](https://user-images.githubusercontent.com/42611122/79718802-3a8e2980-82dd-11ea-8fde-e95e01a01618.png)

as you can see the win/loss are incorrect

**Comment by riQQ** [comment]
Seems to be best of 3 related or do you also have any BO1 matches displayed incorrectly?

**Comment by Manuel-777** [comment]
Fixed in v4.0.18
