### ISSUE TITLE
Uncaught RangeError: Invalid TimeValue

### ISSUE THREAD

**Issue by Thaoden** [Manuel-777/MTG-Arena-Tool#1016]
Created from Discord:
https://discordapp.com/channels/463844727654187020/467737642306371584/702225802917576824

![1](https://user-images.githubusercontent.com/3404787/80127209-4ce5bd00-8594-11ea-9cd7-34e725315912.JPG)

![2](https://user-images.githubusercontent.com/3404787/80127211-4e16ea00-8594-11ea-9456-44a91588a3a6.JPG)

![3](https://user-images.githubusercontent.com/3404787/80127213-4eaf8080-8594-11ea-9789-7bbb20abb79f.JPG)

**Comment by Manuel-777** [comment]
Might be fixed in v4.0.19
