### ISSUE TITLE
Missing art for Monster Series cards in collection tab

### ISSUE THREAD

**Issue by SoilnRock** [Manuel-777/MTG-Arena-Tool#1018]
Some Monster Series cards only show the questionmark and Fblthp's Totally Lost

**Comment by Manuel-777** [comment]
Interestingly some cards show as missing in the database despite Scryfall having the data and images, like Lurrus. Probably code/name bug in Scryfall's db?

**Comment by Manuel-777** [comment]
This was fixed with a Metadata update (same bug as Lurrus showing Totally Lost art)
