### ISSUE TITLE
Draft Pick Overlay not showing correct card ratings

### ISSUE THREAD

**Issue by Extraballs** [Manuel-777/MTG-Arena-Tool#1020]
MTG-Arena-Tool v4.0.17
In Quick Draft Core Set 2020 - all card ratings were shown as 'F' - not sure but I think the best card was actually at the bottom of the list so they were ordered.

**Comment by max1c** [comment]
That's because there is no draft review on https://www.mtgcommunityreview.com/
The person that does these also said on reddit that they are not planning on doing one for Ikoria. I'm not sure what Manuel-777's plan for this is but I also wanted to report this.

**Comment by aroundightii** [comment]
I played a Ikoia draft yesterday, and found that all the card ratings were F. I hope you can fix this problem for card rating is important when choosing cards.

**Comment by Manuel-777** [comment]
I fixed some issues today on v4.1.3 related to drafts
