### ISSUE TITLE
Overlay Window Resetting Position

### ISSUE THREAD

**Issue by BFGGaming** [Manuel-777/MTG-Arena-Tool#103]
Since the last update the overlay window keeps resetting its position to my other monitor. Even when I set it to Persistent Overlay, as soon as it reloads the deck the position gets reset.

**Comment by Manuel-777** [comment]
You probably have two monitors? See this issue;
https://github.com/Manuel-777/MTG-Arena-Tool/issues/92

It's basically just restraining to your main screen, does it happen on each match?

**Comment by BFGGaming** [comment]
Yes, I have 2 monitors. My "main" monitor (I think it's ID #1) has the game and that's where it pops up every time. Before the last update it didn't do this. It used to open up where I left it, on the other monitor. The window isn't invisible though, it pops up on top (as it should since I have always on-top enabled).

**Comment by BFGGaming** [comment]
Yes, that would definitely be better than having to move it every time I load into a new match. It would be nice if it remembered the position, and just had a button to reset it to default (0, 0) but I understand that might confuse people. So this would be happy medium I guess.
