### ISSUE TITLE
Timeline contains event matches

### ISSUE THREAD

**Issue by Thaoden** [Manuel-777/MTG-Arena-Tool#1033]
![Capture](https://user-images.githubusercontent.com/3832723/80257309-da064000-8680-11ea-9c7e-4a6e993417e4.PNG)

These are some matches from today's FNM event.

**Comment by Manuel-777** [comment]
Fixed in #6e74963430449a3840b32d459ab852f874ec33d2 , should be g2g for `v4.0.20`

**Comment by Thaoden** [comment]
Confirmed fixed in 7aac541fb081fd14924b8e94d924c2597a181980 (v4.0.20).
