### ISSUE TITLE
output_log.txt location on non-Windows not documented/likely not where user would have installed MA

### ISSUE THREAD

**Issue by KerfuffleV2** [Manuel-777/MTG-Arena-Tool#105]
On non-Windows platforms, the default location the tool searches for `output_log.txt` is likely not where a user would have installed Magic Arena. I propose to fall back to looking in the current directory if it doesn't exist in that default location with #104.

It would probably make sense to document the default search location and the new behavior. I'd be happy to amend my pull request with a documentation change as well.

**Comment by Manuel-777** [comment]
Fixed in #107

**Comment by KerfuffleV2** [comment]
> Fixed in #107

Works perfectly, appreciate it! I also notice that it loads much faster now. Great work, thanks!
