### ISSUE TITLE
Alternate art ELD adventures/THB gods/IKO Godzilla cards registered strangely in collection 

### ISSUE THREAD

**Issue by SoilnRock** [Manuel-777/MTG-Arena-Tool#1052]
The showing of these alternate art styles should not be connected to the "not available in boosters" button. I would prefer them not being separate cards in the collection chart view as they are _styles_ in Arena.
Right now the numbers are not correct anyway. (Theros Gods alt art are all counted as 0 for me.)

**Comment by Manuel-777** [comment]
Is this ok now?

**Comment by DarkShaman667** [comment]
I'm still having this issue with Throne of Eldraine. For example, I have card ELD005 (Ardenvale Tactician) 4 times and it shows this correctly. But it ALSO shows I am missing ELD005 and on top of that it shows missing ELD273 (Ardenvale Tactician), which is the special card art.
Thanks in advance! I love MTG Arena Tool!

**Comment by Manuel-777** [comment]
#1142
