### ISSUE TITLE
New/Old panel in deck view: vertical resizing bugged

### ISSUE THREAD

**Issue by SoilnRock** [Manuel-777/MTG-Arena-Tool#1053]
When tryinf to vertically resize the three columns the tool/window responds irrationally.
Would be nice if the veritcal column size would simply be the same by default as in history/collection tab.

**Comment by Manuel-777** [comment]
Is this better with v4.1.3?

**Comment by Manuel-777** [comment]
This seems okay now for me, please reopen if not !
