### ISSUE TITLE
Some Play matches not in history or deck records

### ISSUE THREAD

**Issue by Magican28** [Manuel-777/MTG-Arena-Tool#1057]
Today my first 2 BO1 matches are in history and deck records, then 5 matches are not, then my last 4  are. 

I was deciding whether to delete a marginal deck, but realised the win/loss totals were incomplete

**Comment by riQQ** [comment]
Which version of MTG-Arena-Tool are you using?

**Comment by Magican28** [comment]
Sorry, 4.1.4

**Comment by riQQ** [comment]
Why have you closed the issue?

**Comment by Magican28** [comment]
My mistake - wrong button

**Comment by Manuel-777** [comment]
Issue description is a little vague, under what circumstances the error happened, or what steps could be take to reproduce it? as it is now it does not provide enough information (could be the games were not tracked, the tracker had problems parsing or a millon other reasons)

**Comment by Magican28** [comment]
Hi

I was playing a series of Play BO1 matches and it stopped recording them in
history and in the deck win/loss nunbers mid-sesssion
I started another session and it worked again

I picked it up looking at the history/deck screens after the second session

Just gone back over the last day - 25 matches, all in history, Looks like a
rare event, which may not happen again

Thanks

Stuart

**Comment by Manuel-777** [comment]
Closing then, but don't hesitate to reopen if it happens again!
