### ISSUE TITLE
ZoneType_Hand appear as is in the software

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1059]
See screenshot, in game logs, the - I guess - variable doesn't seems to be transformed to actual text, see screenshot.

![ZoneType_Hand](https://user-images.githubusercontent.com/709500/81242512-a4ad0b00-900d-11ea-8790-031093663ee8.PNG)

**Comment by Manuel-777** [comment]
Implemented in next version!
