### ISSUE TITLE
If user goes directly from a game's Action Log back to the History view, then go to any game, it opens up directly Action log

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1060]
If user:
- Go in History view
- Open one game there
- Open the Action log
- Go back directly to the history list with the arrow on the top-left or by switching on the main menu
- Open a game again (whether it is the same one or not doesn't change anything)
- It'll open up directly on the Action Log view instead of the main one.

**Comment by Manuel-777** [comment]
Fixed in v4.2
