### ISSUE TITLE
TypeError in Cards Winrates View

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#1066]
TypeError: Cannot read property 'forEach' of undefined:

![Screenshot](https://user-images.githubusercontent.com/3404787/81442570-25861700-9174-11ea-91b0-788b9d5356c6.png)

**Comment by Manuel-777** [comment]
Cant reproduce this one, but I am pretty sure its because some specific deck/filter settings?

**Comment by riQQ** [comment]
Confirmed fixed with 4.2.4
