### ISSUE TITLE
Windows Defender found a Trojan virus in the MTGA Installer file. Why?

### ISSUE THREAD

**Issue by Zeraken** [Manuel-777/MTG-Arena-Tool#1067]
My Windows Defender ran a scan on my computer and just found a Trojan virus in the MTG Arena Tool Installer.exe file.

Please explain why this would happen. Why is there a Trojan in the installer file?

![image](https://user-images.githubusercontent.com/65140365/81514024-3d83a500-92f2-11ea-99e6-29187c4d003a.png)

**Comment by Manuel-777** [comment]
It is definitely a false positive, see more here;

https://github.com/electron-userland/electron-builder/issues/4793
