### ISSUE TITLE
Traditonal Draft Ikoria not working

### ISSUE THREAD

**Issue by max1c** [Manuel-777/MTG-Arena-Tool#1070]
v4.2.5 Traditional Draft Ikoria picks are not being shown.

**Comment by riQQ** [comment]
It's a limitation of MtGA. It doesn't log human drafts.

**Comment by Manuel-777** [comment]
Yup, not a problem in Tool itself, but the log we read from does not have Human Drafts data;
https://feedback.wizards.com/forums/918667-mtg-arena-bugs/suggestions/40198426-draft-logs-broken

**Comment by max1c** [comment]
I see. Thanks for the explanation.
