### ISSUE TITLE
Collection Chart view erroneously displays a wanted card that you already own 4 of

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#1072]
![screenshot](https://user-images.githubusercontent.com/3404787/82141981-55e74880-9839-11ea-9627-9ef35684e4d3.png)

**Comment by Manuel-777** [comment]
Just came across this one again, how did this happen exactly?

**Comment by riQQ** [comment]
I don't know, but you can reproduce this with my data if you still have it. If not, i can send it to you again.
