### ISSUE TITLE
Allow user to see/copy user ID from opponents

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1081]
I put it here as a suggestion, but this might also lead to toxic behavior, even if I believe and hope MTG players and community are not like that. And I also think in MTGO it's not really a problem from what I heard (I don't play MTGO).

The basic idea is that logs contain full ID of players we encounter (so including 5 digits after the `#`). So, displaying and allowing for people to copy it in a single click, whether is it during the game, through overlay, or after the game, from game history, it would allow to "patch" a little bit of the biggest difference between MTGA and paper Magic, the social part.

As underlined above, however, this might make it easier to have toxic people (this is already possible by manually digging into log file though). I let you decide if this is a good idea or not.

**Comment by Manuel-777** [comment]
Currently MTGA does not allow people to chat with others unless they are friends, and you cant add people if they dont add you, so this is rather useless. I can add a click button to copy the full userid trough, I think its been suggested before.

**Comment by Porkepix** [comment]
Well that's exactly what I did on my last game yesterday, as it was kinda funny I went to dig into log files and added my opponent :) (for the anecdote, a 80 cards monoR deck with Yorion… :P)

**Comment by Manuel-777** [comment]
Already implemented in teh History tab :)

**Comment by Porkepix** [comment]
> Already implemented in teh History tab :)

@Manuel-777 Would it be a good idea to also have it from the overlay, to use during game (or the risk for toxicity is too high, or bad idea for another reason)?
