### ISSUE TITLE
"New card" pip not shown on first card

### ISSUE THREAD

**Issue by Thaoden** [Manuel-777/MTG-Arena-Tool#1082]
The pips for opened or otherwise new cards currently don't show the first of a given card. For subsequent cards, this works fine.

![Capture](https://user-images.githubusercontent.com/3832723/82433554-e4560700-9a91-11ea-9026-6e0a95631216.PNG)

**Comment by Manuel-777** [comment]
What economy event/transaction is it? (please attach full images of the app)

**Comment by Thaoden** [comment]
Booster pack opening. Can't reproduce now because tool caught up in the meantime.
