### ISSUE TITLE
Can't "continue offline" after update to 4.2.7

### ISSUE THREAD

**Issue by maxmironov** [Manuel-777/MTG-Arena-Tool#1087]
Yesterday tracker updated to 4.2.7 version. First 4 or 5 attempts it couldn't find the log file. After tracker found it and parsed, I can't proceed offline (text is unclickable). I don't have account, if it matters
![image](https://user-images.githubusercontent.com/5163989/82643568-04133980-9c10-11ea-802d-36ec292c90dd.png)

**Comment by maxmironov** [comment]
The problem persists after update to 4.2.8

**Comment by Manuel-777** [comment]
The log being read is probably empty or doesnt have any user data, try going into `%APPDATA%/MTG-Arena-Tool/` and delete `remember.json` or edit it to correct the path.

**Comment by maxmironov** [comment]
@Manuel-777 That helped, thank you.
