### ISSUE TITLE
Wins and losses not show against some decks

### ISSUE THREAD

**Issue by Sashweed** [Manuel-777/MTG-Arena-Tool#109]
I added some new decks today and had a few games with them.
[https://imgur.com/2IpcgUQ](url)
They show up in the history tab but aren't recorded against the deck's
[https://imgur.com/q4s6Sq6](url)
I have tried logging out and back in again but it doesn't seam to work.

**Comment by Manuel-777** [comment]
Hi!, I checked this one and indeed, decks with which you only lost and didn't win were marked as 0% and thus ignored from stats, Thanks for the catch!
