### ISSUE TITLE
Improve search accuracy in collection

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1098]
I tried some random search to check something, and couldn't understand why some of the results appeared. See joined example as screenshot, with a search for "artisan" for example: some cards indeed contain this word and have to be shown up.

But for some others, I can't see the word anywhere on the card, so why does it show up? For example "Soulreaper of Mogis", or "Breeding Pool", or "jousting dummy", and so on.

![artisan_search](https://user-images.githubusercontent.com/709500/82790838-0920f480-9e6d-11ea-9de8-059aca41f9cd.PNG)

**Comment by Manuel-777** [comment]
Fixed in #1142
