### ISSUE TITLE
Tool can get stuck on displaying "Downloading metadata…" message on bottom

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1099]
It doesn't prevent from using the software at all, but message get stuck forever keeping being on screen.

![downloading_metadata](https://user-images.githubusercontent.com/709500/82791104-75035d00-9e6d-11ea-81aa-3fd6016654b8.png)

**Comment by Manuel-777** [comment]
It should go away after a few seconds, depends on your conenction speed (metadata is usually 3mb+)

**Comment by Porkepix** [comment]
Yup, but if I opened the issue it's because after dozens of minutes it was still here, on a fiber optic connection.
That said, it's not here anymore for now. But I think there really was an issue at that time.

**Comment by Manuel-777** [comment]
Managed to reproduce and fix this one on #1105
