### ISSUE TITLE
Format filter on History / Decks

### ISSUE THREAD

**Issue by Manuel-777** [Manuel-777/MTG-Arena-Tool#11]
Add a filter on the history tab to filter only matches played, eg; on Standard / Singleton.

Will gain relevance once more formats are added to MTGA.

**Comment by Manuel-777** [comment]
This proved to be particularly difficult to make. Right now decks have limited data on their format, if its not set as "limited" for draft decks, other decks just show "standard".

I will set this feature on pause until I fugure how to discern a single game's format and store it sucessfully.

**Comment by ecyrbe** [comment]
I suggest letting the user add multiple tags on the legality of the deck himself from a customisable list.
then on filter, allow to filter from this list.

**Comment by Manuel-777** [comment]
Reviving an oldie, but I started working on a tags system to let users filter their decks and organize them, see aggregate winrates, etc.
Any suggestions based on this are welcome! :smile:
