### ISSUE TITLE
Can't scroll decklist in overlay

### ISSUE THREAD

**Issue by MikaVaananen** [Manuel-777/MTG-Arena-Tool#110]
While in game, I can't scroll down the decklist if it's too long to be shown in the window. When I hover over what's presumably a scroll bar, my mouse pointer remains as the game mouse pointer. All other elements in the overlay remain interactive, I can hover over cards to look at their detailed info and change the tab (cards remaining, % of cards remaining etc).

I'm on Windows 10 and running version 2.2.0

**Comment by Manuel-777** [comment]
Are you using transparency? If so, it is a known issue with transparent windows.
Else please share a screenshot

**Comment by MikaVaananen** [comment]
It was the transparency issue! I didn't notice the transparency being on.
