### ISSUE TITLE
Track sideboarding under match history

### ISSUE THREAD

**Issue by dyltay** [Manuel-777/MTG-Arena-Tool#111]
I'm requesting a feature that would show how the user sideboarded during the best of 3 matches each game.   What cards were brought in, what cards were brought out.   Would also need to track who was on the play, or draw.

**Comment by Manuel-777** [comment]
I like this one! Although there's no tracking for best part three data other than the results, so we may have to give some love there ;)

**Comment by Manuel-777** [comment]
r #169 is implementing this feature

**Comment by dyltay** [comment]
Amazing implementation.  Thank you so much!  I'm going to close this, what is in place is exactly what I had imagined.  Thanks again!
