### ISSUE TITLE
Draw probability overlay can still show in library a card that is into play

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1114]
This might be due to alternate arts, although I thought the base name was still the reference.

See the screenshot, alternate art of dirge bat is in play, and while this is the single copy of this deck, it's still shown among cards I can draw.
![tool_draw](https://user-images.githubusercontent.com/709500/84208545-4794f100-aab4-11ea-910d-c6df851cc272.PNG)

**Comment by Manuel-777** [comment]
A possible fix for this is in bbb531ecf619a18743fb6895d332f2277b98ef46 (next release), Card mutations were not tracked properly (this affected all mutate cards when played with the ability).
