### ISSUE TITLE
Stuck on "Please wait a minute" screen (2.2.1 linux)

### ISSUE THREAD

**Issue by bauris-prvt** [Manuel-777/MTG-Arena-Tool#112]
I got the most recent version (2.2.1) to install by following the "Compiling / Run from source" instructions. When I run "npm start" i get stuck. The following warnings / errors pop up in the "Alt+Shift+D" windows.
main window:
(warning message; yellow)
> /home/bastian/spiele/mtga_tracker/MTG-Arena-Tool/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:188 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks.
For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.

background window:
the above mentioned warning pops up in here as well, followed by a reoccuring error message
> Error: EISDIR: illegal operation on a directory, read                background.js:586
attemptLogLoop @ background.js:586
async function (async)
attemptLogLoop @ background.js:582

This is where things get stuck, I guess. User permissions for the mtga-log folder/files and the mtg arena tool folder/files are identical. This is on a Xubuntu 18.04 install, with MTG Arena tool version 2.2.1

**Comment by Manuel-777** [comment]
That seems like either a permission's issue or a locked file by another software, have you tried 2.2.0 from the releases? We changed some stuff inside the log reading code since.

**Comment by bauris-prvt** [comment]
Just ran it with 2.2.0. Same issue. Got stuck on the main window.
Debugging info ("Alt+Shift+D") has the warning message from above (security related). No error message.
The main program window (lavarunner) has a "No log file found" message at the bottom.

Since i run it from CLI, here is some of the console output from the start until the reoccuring error message:

> electron .
linux
IPC LOG:  Renderer state: 1
IPC LOG:  0.101
IPC LOG:  SEND >> 0, get_database, TFI99H, 
IPC LOG:  0.604
IPC LOG:  1.104
IPC LOG:  RECV << 0, get_database, TFI99H, 
IPC LOG:  RECV << 0, get_database, 
**removed html code; 404 code**
IPC LOG:  SEND >> 1, get_status, t2rY40, 
IPC LOG:  httpAsync: t2rY40, 
IPC LOG:  1.605
IPC LOG:  2.105
IPC LOG:  RECV << 1, get_status, t2rY40, 
IPC LOG:  RECV << 1, get_status, {
  "page": {
    "id": "**removed**",   
    "name": "MTG Arena",
    "url": "https://magicthegatheri
IPC LOG:  httpAsync: 
IPC LOG:  2.606
IPC LOG:  3.106
IPC LOG:  3.607
IPC LOG:  4.107
IPC LOG:  4.608
IPC LOG:  5.108
Something went wrong loading 
IPC LOG:  5.609
Something went wrong loading 

At this point the last line is repeated until terminated.

Is it necessary to dig into the source to manually set the path information to the location of the log file?

**Comment by trufanov-nok** [comment]
I've just faced with such problem in ver 2.2.8 and was able to solve.
When I launched the app first time it asked me for a path to output_log.txt
And I specify that path. But it actually needs a full path to  output_log.txt with  output_log.txt at the end. Otherwise it tries to read its parent directory as a file and fails.

So you need to clear app settings (mine was here: `rm -rf /home/myname/.config/MTG-Arena-Tool/`) and specify full path next time it'll ask you. Mine was `/home/mynme/MTG_Arena/prefix/drive_c/users/mynme/AppData/LocalLow/Wizards Of The Coast/MTGA/output_log.txt`

@Manuel-777 could you please add a simple check for output_log.txt at the end of path and automatic fix for this?

**Comment by bauris-prvt** [comment]
I guess, you could close this topic.
I managed to succesfully install and run the latest version of the tool following the hints and instructions from @trufanov-nok . This is on a Xubuntu 18.04, most recent version of MTG Arena and version 2.2.8 of MTG-Arena-Tool.
Only tested offline-mode so far. MTG-Arena-Tool seems to work with no apparent errors/chrashes.

Thanks again to @Manuel-777 for creating this tool and @trufanov-nok for the hints to fix this problem on my end.

**Comment by Manuel-777** [comment]
Excellent, closing then.  To add on what @trufanov-nok found, the specific file you should be deleting in ´rm -rf /home/$(whoami)/.config/MTG-Arena-Tool/´ is ´settings.json´, which is the file that holds the output log location, if you delete everything you risk losing your saved progress.]
Obviously if deleting settings.json doesnt work, you can try everything instead.
