### ISSUE TITLE
(Windows 10) Overlay Missing Scrollbar

### ISSUE THREAD

**Issue by thenaka** [Manuel-777/MTG-Arena-Tool#1120]
This issue started today. My overlay no longer has a scrollbar. I have tried all of the different overlays options (full deck, next draw, etc.). I tried to modify my transparency levels. I tried to resize the window and reset its position Nothing worked to restore the scrollbar.

![overlay](https://user-images.githubusercontent.com/10818700/85211810-04374f80-b30a-11ea-912a-92378c6eeb51.JPG)

**Comment by Manuel-777** [comment]
A temp fix for this is in v5.0.7, that makes Auto resize to work properly again. Tho the scrollbar is still not visible.

**Comment by Manuel-777** [comment]
Fixed in e8f389871af9f95c50649a30471f8d18514b83e2 (next release)
