### ISSUE TITLE
Cube drafts overflow layout in Events tab

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#1122]
![screenshot](https://user-images.githubusercontent.com/3404787/85232157-5a38ef80-b3fd-11ea-8bf5-a8fb1e3a5edf.png)

**Comment by riQQ** [comment]
The fix limits the display to 5 cards. That's not optimal, because there is no indication, that there were more cards.

**Comment by Manuel-777** [comment]
Yeah, I reckon, it was a quick fix to regain visibility to the list item itself, ideally it should displat the number of rares and mythics if above certain threshold.

**Comment by riQQ** [comment]
Should we track it in a new issue?

**Comment by Manuel-777** [comment]
No no, pushed an update to this that will display it like this instead of limiting to 5;
![image](https://user-images.githubusercontent.com/4711391/85428879-3e942d00-b554-11ea-9ac2-a7a0080c314a.png)

**Comment by riQQ** [comment]
Commit 8a3d873ee4468e8fe05c7a74888e834b7972bef5

**Comment by Manuel-777** [comment]
Oh yeah, sorry (changed it mid-coding it)

**Comment by riQQ** [comment]
I thought it would aggregate only over the threshold, but with 5.0.9 it aggregates in every case

**Comment by riQQ** [comment]
With 5.20, it doesn't show any rares for my latest draft even though I definitely drafted rares

**Comment by riQQ** [comment]
At the moment, it always aggregates. That's not intended, right?
