### ISSUE TITLE
export collection csv does not escape card names with commas

### ISSUE THREAD

**Issue by jmhodges** [Manuel-777/MTG-Arena-Tool#113]
When exporting a collection with card names like "Slimefoot, the Stowaway", the generated CSV does not correctly escape the commas in their name. This causes spreadsheet software to see the card names as two separate columns.

**Comment by Chimera91101** [comment]
Manual, Quick fix would to use a different delimiter in the CSV... maybe a semicolon or anything else that Excel uses that isn't in a cards name?

**Comment by jmhodges** [comment]
It's roughly a oneline patch (plus tests, I imagine) to do

```
            name = replaceAll(name, ',', '\\,');
```

or similar (I forget javascript escaping rules) in the current code. Probably, better to use a csv lib like https://csv.js.org/ to generate it because who knows what weird characters wotc might end up putting in there.

**Comment by Manuel-777** [comment]
I was looking for data on this and appearently if you encapsulate a field's value in quotes like this
`value,value,value,"Slimefoot, the Stowaway,value"
value,value,etc`
It should load correctly, can anyone confirm this manually? _(I dont use excel at all and other software may behave differently)_

if this works its a very easy fix, just add quotes to the fields that may contain commas.

**Comment by jmhodges** [comment]
If you're looking for a quick free test, Google Sheets behaves the same as excel!
