### ISSUE TITLE
No Tray icon and "after match"-overlay does not disappear [Linux]

### ISSUE THREAD

**Issue by D1Ck3n** [Manuel-777/MTG-Arena-Tool#1130]
Good day,
i use your Tracker (as appimage) on Manjaro Linux and got some issues with it:

1. i cant see the tray icon (i installed all the dependencies)
2. after a match i see some nice stats about the match but even after closing the game it still don't disappear (see screenshot)

i hope someone can help me, i like this tracker!
best regards
D1Ck3n
![Bildschirmfoto vom 2020-07-07 16-24-52](https://user-images.githubusercontent.com/28949322/86815970-928a3000-c083-11ea-8353-d022896ae6f4.png)

My System:
OS: Manjaro 20.0.3 Lysia
Kernel: x86_64 Linux 5.6.16-1-MANJARO
Shell: bash 5.0.17
Resolution: 3840x1080
DE: Cinnamon 4.6.3
WM: Muffin
Disk: 3,3T / 19T (18%)
CPU: AMD Ryzen 5 2600X Six-Core @ 12x 3.455GHz
GPU: GeForce GTX 1060 6GB
RAM: 3611MiB / 15959MiB

**Comment by Manuel-777** [comment]
I don't seem to have any problems with the tray icon on Manjaro Linux (Gnome, x64), tested with a vanilla installation, without any libraries.

**Comment by D1Ck3n** [comment]
i had it once on version 3 i think but now it does not appear :(

**Comment by D1Ck3n** [comment]
this time it seems to work but after my match against Alxmar10 no stats screen appear, but the next match i had it always in my sight 
![Bildschirmfoto vom 2020-07-08 22-22-12](https://user-images.githubusercontent.com/28949322/86970299-719f0900-c16f-11ea-8b9c-90307b7c8a7c.png)

**Comment by Manuel-777** [comment]
Yep, the X button is hidden on top right, its fixed for next update!

**Comment by D1Ck3n** [comment]
thanks for the update!

other thing: isa it maybe a DE issue with the tray icon? Cinnamon is based on Gnome2, maybe there is the problem

**Comment by D1Ck3n** [comment]
Hey, Version 5.4.1 fixed my Tray icon issue! Thanks!

strangely i can't use the "x" buttons ingame or move the overlay

**Comment by Manuel-777** [comment]
Closing as the problem of Linux and overlays interaction is out of scope, currently there is no easy way to make a full ontop and interact-able overlay in Linux and Mac, although we will keep trying to get it working, if possible!
