### ISSUE TITLE
Number of copies in collection is hard to read since 5.2 update

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1133]
See joined screenshot, numbers in collection table since 5.2 are hard to read due to color changes.

![mtg-tools-collection-colors](https://user-images.githubusercontent.com/709500/86835354-413a6a80-c09c-11ea-8188-3dd0b66feb18.PNG)

**Comment by Manuel-777** [comment]
Fixed in #1142
