### ISSUE TITLE
In collection tab, changing right bar's width result in visual glitches in the table

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1135]
See joined screenshot for some glitched that remains (separation in blue section between column 3 and 4, and green section between column 2 and 3), but more generally, changing right bar's width result in this kind of glitches appearing and disappearing everywhere in the table.

**Comment by Manuel-777** [comment]
#1142 removes the sidebar entirely

**Comment by Porkepix** [comment]
Will we still have all the stats that it provided?

**Comment by Manuel-777** [comment]
Yep, and much more easy to view!
