### ISSUE TITLE
Cannot enter credentials

### ISSUE THREAD

**Issue by Magican28** [Manuel-777/MTG-Arena-Tool#1147]
Started needing a password even though I was in remember me mode, but would not let me enter it
Subsequentally lost my email addrress too, and I can't enter that either
Problem started in 5.2.0 and is still there in 5.4.0

Thanks

**Comment by riQQ** [comment]
Workaround is to restart the tool (see https://github.com/Manuel-777/MTG-Arena-Tool/issues/1141#issuecomment-658771197)

**Comment by Magican28** [comment]
If only - I'd already restarted the tool and restarted the machine and the tool. Still locked out
Just tried both of those again and still the same. 

I also had a look in the registry but didn't find Arena Tool, might have been something to jiggle

**Comment by Manuel-777** [comment]
You should have a message popup explaining what happened when you try to log in, could you share that?

**Comment by Manuel-777** [comment]
BTW scryfall added them to a new set;
https://scryfall.com/card/ajmp/3/archon-of-suns-grace

**Comment by Magican28** [comment]
Sure
Password must contain at least 8 characters

**Comment by Magican28** [comment]
This is embarrassing - user error ! All ok
