### ISSUE TITLE
Draft replay is not recorded anymore

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#1150]
Draft replay is not recorded anymore. I can only say that it's not working for Quick Draft but I guess it's not working for the other modes either. This issue is occuring since 11.06.2020, on 10.06.2020 it was still working.

The deck from the 11th actually has one rare.
![grafik](https://user-images.githubusercontent.com/3404787/87879321-34960a80-c9ea-11ea-9e0b-abbf3b18a781.png)

**Comment by Manuel-777** [comment]
I'll need a draft log to reproduce, I'm quite far off one now

**Comment by riQQ** [comment]
Can confirm the fix with 5.4.2 in Quick Draft.
