### ISSUE TITLE
"Export to Arena" should export cards seen in of all 3 games

### ISSUE THREAD

**Issue by omegaula** [Manuel-777/MTG-Arena-Tool#1159]
If I play best of 3, when I export opponents deck to arena, I want to export all cards seen, not just cards from a single game.

**Comment by eyeq** [comment]
It looks like that enhancement has already been implemented: "Match Combined View".

v4.0.21 (2020/04/29): Added - Cards seen by game (#1040)

**Comment by riQQ** [comment]
Yeah, in the match details there is now a combined view. See also the screenshot below:

![screenshot](https://user-images.githubusercontent.com/3404787/99119369-649c9580-25f9-11eb-871c-cd040329294f.png)
