### ISSUE TITLE
''Collection'' tab contains no data

### ISSUE THREAD

**Issue by jopsie** [Manuel-777/MTG-Arena-Tool#1161]
Hi Folks,

I recently moved (uninstalled/reinstalled) the MTGA client to a new drive. However, the log file location remained the same....C:\Users\jops\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log The MTGA client now resides on my new E:\ drive. (used to be on c:\  )

Now for some reason everything under the collection tab is blank with no data whatsoever. I don't know if this is related to the client move but some data from the log did pull through like the new player decks are there (even though their names are incorrect), gold/diamond balance seems correct.

Is there anything I can do to fix this myself? I tried reinstalling mtg tool but that didn't help?

Thanks guys!
Johan

**Comment by maxmironov** [comment]
+1, collection tab is empty after update to 5.4.4

**Comment by marcelo-re1s** [comment]
If I have the same issue if I set "In Boosters" filter value to "In Boosters".

**Comment by Aldahen** [comment]
I confirm the bug.
- If you select "In boosters", you see nothing
- if you select "All Cards", you see your collection including all cards (in and not in boosters)
- If you select "Not in boosters" you see the same as "All Cards"

**Comment by siwood** [comment]
Same for me in 5.4.1. It was working earlier today. Not sure what happened though.

**Comment by riQQ** [comment]
Should be working again with metadata v91 (see settings > about).

**Comment by maxmironov** [comment]
I have metadata v92. Is there any way to roll it back?

**Comment by riQQ** [comment]
It should also work with metadata v92, everything that is v91 or greater should work.

**Comment by maxmironov** [comment]
Yes, started to work after application restart. Thank you for quick response

**Comment by jopsie** [comment]
Just ran the new update with metadata v92 all seems fine!! cheers :1st_place_medal:
