### ISSUE TITLE
control chime volume

### ISSUE THREAD

**Issue by jmhodges** [Manuel-777/MTG-Arena-Tool#117]
The chime on priority change is great! It's a little loud on my machine when the rest of the audio on it is at an okay level. Could we get a way to control its volume?

**Comment by Manuel-777** [comment]
I agree! and changing with the windows controller is annoying too. 
Will probably add a slider in settings for it.

**Comment by tildar** [comment]
I'm making an attempt to add the volume slider in settings. Will submit pull once I have something working.
