### ISSUE TITLE
Troubleshooting page is missing

### ISSUE THREAD

**Issue by aragos** [Manuel-777/MTG-Arena-Tool#1171]
It was removed in [the fix](https://github.com/Manuel-777/MTG-Arena-Tool/commit/7ad7b6b65c8694356f2a8f18822e6cc18a27eace#diff-e8f0e79b9005fb9fde8c970e2d1b6281) for #1155 but no new page was added in the shared repository. There are several places the troubleshooting page is linked throughout the project which currently result in `404`.

**Comment by riQQ** [comment]
Part of it is here now: https://mtgatool.com/docs

**Comment by Manuel-777** [comment]
Closing, as of #1155 every piece of help/documentation should go in mtgatool.com/docs. All fixes documented in there were outdated for the latest builds.
