### ISSUE TITLE
Resizing Font size

### ISSUE THREAD

**Issue by Littlemad** [Manuel-777/MTG-Arena-Tool#118]
I couldn't find any option related in resizing the text. I find very annoying and frustrating that. I am not talking about the cards, I am talking about the title of the cards, and even more so the small percentage next to it. I find those very useful, and it bothers me to have to force my eyes to try to read it while I am focused on the battle.

Possibly when text would be too big, it should fall on two lines maximum or have "ellipsis" and be visible on overlay somehow.

**Comment by WhiteSp1rit** [comment]
I might add that I cannot read the card list anymore which is shown during the match - one of the updates made the font so small that it became unreadable.
