### ISSUE TITLE
Draft replay screen changes card sort order when revisiting pick we have viewed before

### ISSUE THREAD

**Issue by ojohnny** [Manuel-777/MTG-Arena-Tool#1182]
I see this problem in the Linux version 5.5.3, and I have not tested any other OS:es/versions.

To reproduce, go to the replay view of any draft event.

1. The standard sorting shows Pack 1, Pick 1 with rare at top-left, which is fine.
2. Pressing "right arrow" on keyboard shows Pack 1, Pick 2 with rare at top-left, which is still fine.
3. Pressing "left arrow" on keyboard now shows Pack 1, Pick 1 with rare at bottom-right (!)
4. Pressing "right arrow" on keyboard now shows Pack 1, Pick 2 with rare at bottom-right (!)

This pattern repeats itself when using the keyboard.  It can also be reproduced when using the "slider" on the top of the replay screen, and here we can see that the screens does not need to be adjacent for this to happen.  If we "skip" to any screen we have seen before, then the sorting order for that pick is changed.

Now the really interesting thing happens.

After using the "slider" with the mouse to change the screen, then using the arrow keys on the keyboard no longer changes the sort order (!).

I would expect the sort order to never change in any of these cases.

**Comment by riQQ** [comment]
This is working for me in 5.5.7:

![PNm7GNa5yz](https://user-images.githubusercontent.com/3404787/108399803-d0a32100-721a-11eb-8bd7-c55232b8ea38.gif)

**Comment by ojohnny** [comment]
Can confirm, this no longer seems to be an issue.  Closing.
