### ISSUE TITLE
collection tracker modal cards

### ISSUE THREAD

**Issue by boaguy** [Manuel-777/MTG-Arena-Tool#1190]
back side of modal double faced cards are showing as not owned in tracker when they are owned just part of the forward facing card.

**Comment by riQQ** [comment]
Do you have a screenshot? Where do they show as not owend?

**Comment by boaguy** [comment]
Attached are the screenshots.  I own all the uncommons in the zendikar set
however it shows as im missing uncommons in the tracker.  You can see by
the example in the photos that i own jwari disruption but it is showing
that i don't own jwari ruins.

thanks,
Kyle

**Comment by riQQ** [comment]
In 5.5.4 it doesn't show the back side of the MDFC even with the filter `In Boosters` set to `All cards`, so this is fixed.
