### ISSUE TITLE
MTG Arena Tool incorrectly datestamps deck changes

### ISSUE THREAD

**Issue by Novocastrian** [Manuel-777/MTG-Arena-Tool#1215]
Hi there, 

I just made significant changes to a Brawl deck of mine a moment ago, and the tool thinks these were made 11 hours ago. I'm located in GMT+11 (Australian Eastern Daylight Time), so it's perhaps not getting the local time correctly and defaulting to GMT +0 instead? 
![image](https://user-images.githubusercontent.com/4601813/104151291-c11d0500-5430-11eb-9f93-2c4658f76f04.png)

**Comment by Novocastrian** [comment]
Accidentally reported as #1216 as well, as GitHub displayed an error when I submitted this one.

**Comment by riQQ** [comment]
Duplicate of #1216
