### ISSUE TITLE
The Troubleshooting Guide is missing

### ISSUE THREAD

**Issue by Shardot** [Manuel-777/MTG-Arena-Tool#1246]
As per the title. The Troubleshooting guide (<https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md>) linked to in the Submitting Issues [Guidelines] (#170), as well as in the readme doesn't seem to exist anymore. It's either been incorporated into something else, moved, removed or renamed.

As it's mentioned both in a pin and in the readme, that should probably be fixed. ;)

I haven't checked whether there are more dead links towards that file or not.

**Comment by riQQ** [comment]
I update the issue and made a PR for the README.md.
