### ISSUE TITLE
Strixhaven draft evaluations not showing

### ISSUE THREAD

**Issue by fasmat** [Manuel-777/MTG-Arena-Tool#1249]
For the latest set during draft MTG-Arena-Tool doesn't show the tiers of the cards to be picked.

**Comment by riQQ** [comment]
This was implemented with meta data v117 (ratings https://github.com/mtgatool/mtgatool-metadata/commit/2e8402365e4a82a235b099b930ab0721d5c46ad9, version 117 https://github.com/mtgatool/mtgatool-metadata/commit/e14f0c9c12c0e4789e77a2e1cd3e714f83203c1d).
