### ISSUE TITLE
Check for updates gives Update error.

### ISSUE THREAD

**Issue by fasmat** [Manuel-777/MTG-Arena-Tool#1250]
Clicking on check for updates in Settings -> About only gives an Update error. Furthermore clicking on release notes gives the change log of 5.5.13 and not 5.5.18.

**Comment by fasmat** [comment]
Since MTG-Arena-Tool won't receive any more updates, I'm closing this issue.

**Comment by riQQ** [comment]
Is this on macOS? The problem might exist in 6.x too.
