### ISSUE TITLE
Linux checksum don't match

### ISSUE THREAD

**Issue by ig-perez** [Manuel-777/MTG-Arena-Tool#1258]
The checksum for the latest release file (`latest-linux.yml`) don't match when running `shasum -a 512 MTG-Arena-Tool-5.5.21.AppImage` on Linux.

**Comment by riQQ** [comment]
Is this the first time that happened for you? Nothing really changed regarding creating releases between 5.5.19 and 5.5.21.

**Comment by ig-perez** [comment]
Sorry for the late reply. I uninstalled the application. I'll report if this is still happening when I have a chance to try it again. In the meantime I'm closing the issue.

Thanks!
