### ISSUE TITLE
Icons in deck explorer are mouse over mislabled

### ISSUE THREAD

**Issue by Chimera91101** [Manuel-777/MTG-Arena-Tool#126]
In "My Decks", Select a deck. The Icons directly below the "Export to .TXT" Button are all mislabeled to show "Creatures" when you mouse over them.

Can still play around it, but annoying if you're a first-timer that doesn't know what the icons mean.

**Comment by Manuel-777** [comment]
Fixed [(#31ae8d5ed5f5c743f97a53e600bad633a6582a4c)](https://github.com/Manuel-777/MTG-Arena-Tool/commit/31ae8d5ed5f5c743f97a53e600bad633a6582a4c)
