### ISSUE TITLE
So how long until I can actually track my Arena gains?

### ISSUE THREAD

**Issue by YelmsLight** [Manuel-777/MTG-Arena-Tool#1268]
I've been waiting for over a month to be able to track my activities in Arena.  I've even had to go into my own deck builder in order to track my progress.  How long until there's an actual, usable MTG Arena Tool?  Do I need to abandon it for one that actually works?

**Comment by Manuel-777** [comment]
Hi @YelmsLight ! v6 is partly functional, although not finished yet, you can check it out [here](https://github.com/mtgatool/mtgatool-desktop/)!
