### ISSUE TITLE
TypeError when accessing Collection tab

### ISSUE THREAD

**Issue by arfar** [Manuel-777/MTG-Arena-Tool#1271]
Hi there

Whenever I try to use the "Collection" tab, I get the following error:

    TypeError: Cannot read property "inventory" of undefined

I'm really not sure what further to put unfortunately as the logs provided to not really say much other than the error started from  main.1f89d86d.chunk.js:1:1610372.

It has worked once or maybe twice since installing it a few days ago, but most of the time it does not.

I'm running on Linux, PopOs 21.04 running "mtgatool-desktop-6.1.21.AppImage"

I attach a screenshots
![Screenshot from 2021-12-16 23-00-13](https://user-images.githubusercontent.com/2935358/146461543-d65aaeaf-3fe0-415b-9ddc-90cfe89c49f0.png)
![Screenshot from 2021-12-16 23-02-18](https://user-images.githubusercontent.com/2935358/146461624-29792b58-98ad-4bbd-a669-1a7a0da4bce3.png)

Once this error is encountered, nothing in the app can be used (effectively just locked up and I have to kill it).

Very happy to try any further steps to troubleshoot/diagnose. I understand this is a bit of a useless bug report in its current form.

Thanks in advance
Arthur

**Comment by riQQ** [comment]
Belongs in the repo [mtgatool/mtgatool-desktop](https://github.com/mtgatool/mtgatool-desktop). The one here is for 5.x.
