### ISSUE TITLE
In-client updater doesn't register new update

### ISSUE THREAD

**Issue by flatluigi** [Manuel-777/MTG-Arena-Tool#131]
![screencap](https://puu.sh/CiGzp/909d2b8dc8.png)

Could this be related to the releases not having an .exe build?

**Comment by Manuel-777** [comment]
If you are running from source, yes.

There was an issue with the Electron version that caused 2.2.2 updater to stop working trough, it is fixed now in 2.2.5, if you are on 2.2.2 you will have to update manually.
