### ISSUE TITLE
economy

### ISSUE THREAD

**Issue by rebreanu** [Manuel-777/MTG-Arena-Tool#133]
Hello!
In aplication tab " economy" don't work.

**Comment by Manuel-777** [comment]
Can you elaborate?

**Comment by rebreanu** [comment]
Doesn't show anything.

**Comment by Manuel-777** [comment]
is this still an issue? If so please provide some more data (a developer console capture, output_log + user config files, or reproduction steps)

**Comment by hugo-ds** [comment]
I had the same problem.
If I delete the ABCDABCDABCDABCD.json (contains economy data etc.) file located at .../appdata/roaming/MTG-Arena-Tool/ and launch the app economy tab works normally.
But lose the previous data.

**Comment by Manuel-777** [comment]
Could you send the file to mtgatool@gmail.com for inspection?

**Comment by Manuel-777** [comment]
Checked with @hugo-ds json and it works now (it was indeed failing to load the economy tab)
Should be okay for next release!
