### ISSUE TITLE
We Need Way to Remove or Filter Out Decks We've Deleted from "My Decks"

### ISSUE THREAD

**Issue by Reithan** [Manuel-777/MTG-Arena-Tool#134]
I've got a lot of decks in "My Decks" listed as just "New Deck" or "test" or whatever, because they were made, run a few times to test something, and deleted, but now it's clutter. We need a way to either delete these, or filter to only 'active' decks.

**Comment by Manuel-777** [comment]
There is such an option already, just hover on the red button at the right of the decklist and click the delete button that pops. You need to be on a version newer than 2.2.2 trough.

**Comment by Reithan** [comment]
I'm in v2.2.5 and the red button doesn't do anything.

**Comment by Reithan** [comment]
Also, not every deck has a red button next to it.

**Comment by Manuel-777** [comment]
If the deck is in arena you will not be able to delete it, because decks are automatically imported. The only way to remove those is from arena itself.

**Comment by Manuel-777** [comment]
I think I wasnt clear, the delete button is in the right of the decks screen;
![image](https://user-images.githubusercontent.com/4711391/50459078-c93ba200-0946-11e9-979a-d8a4169af2ca.png)

**Comment by Reithan** [comment]
Oh, I see. That's super hidden. I only see a small pink sliver on the right hand of the window, but it does expand out if you hove it. If you hadn't shown me this I probably never would have found it.
