### ISSUE TITLE
[Overlay] Split the Clock into: Total/Yours/Opponent

### ISSUE THREAD

**Issue by GoldMath** [Manuel-777/MTG-Arena-Tool#135]
Hello,

I find very useful to have the Overlay Clock tracking individually both players times with the addition of the grand total like the following:

```
     Total Time
Your Time | Opponent Time
```

Thanks! Your tool is nicely done and just need some QoL UI fixes!

_PS: I use the overlay on my other screen, would it be possible to add the possibility to Resize the height?_

**Comment by Manuel-777** [comment]
Already implemented
