### ISSUE TITLE
[Collection] Adding Color completion

### ISSUE THREAD

**Issue by GoldMath** [Manuel-777/MTG-Arena-Tool#136]
Hello,

In the **Collection** tab, the sets already track **Rarity completion**, would it be possible to also add **Color completion** under the Rarity too?

![color space](https://user-images.githubusercontent.com/7282547/50400829-1de5ee00-078a-11e9-8186-187aad8c3acd.jpg)

Regards,

_PS: Wouldn't the Sets better being sort by release time instead of alphabet?_

**Comment by tulasacra** [comment]
i dont get the current sorting at all. Would be great for sure if it were by release time.

**Comment by lusbenjamin** [comment]
also not directly implemented in #835, you will eventually be able to turn on individual color filters and view the completion stats for that color one-at-a-time
