### ISSUE TITLE
History and My Decks are empty

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#14]
![screenshot](https://i.imgur.com/v0gfOOB.png)

My Decks shows the decks the first time but if I navigate to any other tab and go back to My Decks it ends up being empty.
Note that this was happening before the recent MTGA update.

**Comment by Manuel-777** [comment]
This is odd, the tab also says you're on history, does this happen all the time?

**Comment by Xiaminou** [comment]
Yes it happens all the time, and is still happening after the latest update.

**Comment by Manuel-777** [comment]
I will need to see the log file of Arena and tool's save config,;
Arena log: C:\Users\<User>\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt"
Tool config;  %APPDATA%/mtg-arena-tool/<userid>.json

Send me those to mtgatool@gmail.com so I can replicate the bug

**Comment by ecyrbe** [comment]
I have the same bug. My decks are no more showing since last update.
[output_log.txt](https://github.com/Manuel-777/MTG-Arena-Tool/files/2206976/output_log.txt)

**Comment by ecyrbe** [comment]
It might be due to the name of the new preconstructed decks that have a weird naming and a not null description.

**Comment by Manuel-777** [comment]
That was corrected on the latest version of mtgatool, make sure you are using v2.0.18
I'll look into the log in case you already have the latest!

**Comment by ecyrbe** [comment]
I erased all the given pre-constructed decks from WOTC and i still have no decks showing.
Maybe a conflict with your DB ? How can i make a fresh install and erase all the previous settings and saved data ?

**Comment by Manuel-777** [comment]
It shouldn't actually, check the installation directiory for the .json config file and send it to mtgatool@gmail.com (do not upload it here)

**Comment by Manuel-777** [comment]
By the way, I'm pretty sure data is there, just not being displayed by someone interface bug, mtgatool does not even have a routine to delete the config file, so unless you manually delete it, it will be saved.
You can see your data is preserved because your username and rank are pne top

**Comment by ecyrbe** [comment]
OK, i sent you the files.

**Comment by Xiaminou** [comment]
I sent the my files earlier today, hopefully that will help.

**Comment by Manuel-777** [comment]
Got them! I'll check them asap
