### ISSUE TITLE
Add Tags to opponent decks

### ISSUE THREAD

**Issue by ecyrbe** [Manuel-777/MTG-Arena-Tool#141]
Now that you can tag your own decks, it would be nice if you could also tag opponent deck.

This way, you could have stats that show your winrate against some tags (jeskai control, rdw, etc) and not only stats against color combination that is showed in the deck view.

**Comment by Manuel-777** [comment]
This was proposed by another user and we thought it would be great to also make tags 'collaborative' in a way. You would get a set of predefined tags based on tags other users created, sorted by popularity, then those tags would serve to identify decks on the server and create a more accurate representation of the meta.

This is a far.future idea trough, normal tags would be also great in the meantime to help categorize history a little more!

**Comment by OdinFK** [comment]
I think this might serve as a basis to make MTGATool much more useful. When decks are tagged then you could also generate data on which cards in your own deck are correlated with winning against which archetypes. P.e. 76% you won against Monored when you played Deafening Clarion. This might be a little difficulr to implement UI-wise, but to me this would make the difference between a nice-to-have tracker and an invaluable tool that would also provide unique value.

**Comment by ecyrbe** [comment]
I guess we can close this one now ?
