### ISSUE TITLE
Self-shrinking UI

### ISSUE THREAD

**Issue by WhiteSp1rit** [Manuel-777/MTG-Arena-Tool#145]
Some time ago with each game start the sideboard which shows the cards left into your deck started shrinking. It became smaller, and smaller, and now it looks like this:

https://i.imgur.com/plaRh6X.jpg

Any ideas? Only the sideboard is affected, main window stays the same.

**Comment by Manuel-777** [comment]
Does it work if you enlarge the window? (place the cursor near an edge as any regular window)

**Comment by Manuel-777** [comment]
Added overlay scale in 2.2.12 which should fix this issue. Closing.
