### ISSUE TITLE
Teferi promo added to change log whenever deck is modified

### ISSUE THREAD

**Issue by OdinFK** [Manuel-777/MTG-Arena-Tool#146]
Whenever I change my deck (which has the Teferi promo) the Teferi promo will afterwards be added to the change log for the deck. You can see him under changes in the picture. The app actually pretends he was added in any of the displayed changes, but the number of Teferis in my deck never changed even once.

![teferibug](https://user-images.githubusercontent.com/19306617/50819842-80fb8700-132b-11e9-85a0-524c5ae8b6c8.jpg)

**Comment by AnnanFay** [comment]
Just posting to confirm this is still happening. Though in my case it is posting that Teferi is being removed every edit. 
![image](https://user-images.githubusercontent.com/766048/62829448-87215100-bbf5-11e9-877c-883ecdd9412a.png)
