### ISSUE TITLE
Some game in History tab appears as 0:0 even though I won them

### ISSUE THREAD

**Issue by pvdlg** [Manuel-777/MTG-Arena-Tool#148]
Here is an example of such game:
![mtg_arena_tool](https://user-images.githubusercontent.com/3250552/50853200-98e50200-134f-11e9-8788-a3e865c1aeaa.jpg)

Here is the client logs associated:
[output_log.txt.zip](https://github.com/Manuel-777/MTG-Arena-Tool/files/2738117/output_log.txt.zip)

**Comment by Manuel-777** [comment]
Been on the hunt for this issue for a while, will investigate further!
