### ISSUE TITLE
Deck stats in "My Decks" don't match the stats of the same deck under "Explore"

### ISSUE THREAD

**Issue by chaosturtle** [Manuel-777/MTG-Arena-Tool#150]
The decks stats for one of my decks (that I know of) under the "My Decks" tab appears to be correct and matches the information found in my "History" for that deck.

Finding the same deck under the "Explore" tab by filtering for colors and looking for the decks name and my user name shows the deck with completely different stats, and the win/loss stats don't make sense when compared with the "History" (meaning, it says the deck is 4/6 but there is no grouping of 10 games in the history that represents a 4/6 record).

I don't think the "Explore" version of the stats is out-of-date (because of the grouping). It seems to be not pulling from the same data as the version under "My Decks."

![screenshot 2019-01-12 10 06 07](https://user-images.githubusercontent.com/24359761/51076220-d2b94f80-1652-11e9-835a-cdc7ea00ce31.png)
![screenshot 2019-01-12 10 09 28](https://user-images.githubusercontent.com/24359761/51076224-f2507800-1652-11e9-817e-4dd9c39db822.png)

**Comment by Manuel-777** [comment]
It is possible you modified the decklist at some point and some games werent counter in that Explore deck, Explore counts decklists so werener you change a card it is counted as a new deck.

**Comment by dougmill** [comment]
Were you playing Traditional (best-of-3) format with this deck? There at least used to be an issue where only the first game in a match would get saved on the server.
