### ISSUE TITLE
Missing matchup in deck stats

### ISSUE THREAD

**Issue by pvdlg** [Manuel-777/MTG-Arena-Tool#151]
I played a game against a White-Blue-Green as seen in this screenshot of the event tab:
![mtg_arena_tool](https://user-images.githubusercontent.com/3250552/51080264-36b93380-16a6-11e9-82ea-9399cb3cb53b.jpg)

However in the deck stats there is no White-Blue-Green matchup:
![mtg_arena_tool](https://user-images.githubusercontent.com/3250552/51080274-5ea89700-16a6-11e9-976d-fcce418f35d6.jpg)

The deck wasn't modified since several days. The missing game happened an hour before taking the screenshot.

**Comment by Manuel-777** [comment]
If it was just one game it will not be shown , to not show clutter of fringe color combinations stacked on the edges, I think two encounters makes them show up.

**Comment by pvdlg** [comment]
Thanks for the explanation!
That would be great to have either a visual indicator to know there is other uncommon match up, or maybe an additional win/loss bars for "others" that would group all those match up encountered less than twice.
