### ISSUE TITLE
Economy 

### ISSUE THREAD

**Issue by usernameapick** [Manuel-777/MTG-Arena-Tool#152]
Hola, Manuel. Ante todo gracias por compartir tu proyecto. La solapa de Economy marca mal las fechas, por ejemplo, en mi caso, veo que la última Player reward "fue" el el martes primero de mayo de 2019. El dato que levanta es de la semana pasada, me acuerdo por la carta de recompensa. ¿Se podrá hacer algo con eso? ¿Los demás datos como el vault estarán bien?
Muchas gracias, por leer y por compartir.

**Comment by Manuel-777** [comment]
El log de mtga usa la fecha de istema, y aveces eso confunde un poco al tool, al estar en el formato equivocado (05/01/2019 vs 01/05/2019), o por lo menos eso es lo que creo que sucede.

Por favor si me puedes enviar un log donde obtengas alguna recompensa a mtgatool@gmail.com te lo agradeceria;
https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md

**Comment by usernameapick** [comment]
Se más especifico. Hay un solo archivo output.log.txt ¿Querés que te envie ese? ¿Querés alguna linea de ese archivo en especial?  
En el troubleshooting dice que renombrar el archivo output.log puede solucionar problemas. ¿Qué la renombre a que nombre?

**Comment by Manuel-777** [comment]
No, solo envia el archivo completo (es como una historia de las acciones durante esa sesion, si no esta entero por ahi no sirve)
No hace falta renombrar, eso es solo si hay problemas al arranque del programa.

**Comment by Manuel-777** [comment]
duplicado de #102
