### ISSUE TITLE
Overlay is blank

### ISSUE THREAD

**Issue by Arslin** [Manuel-777/MTG-Arena-Tool#154]
Since the update this morning, the deck overlay is blank. It has to title bar or content, so I can't move it around.

**Comment by Sashweed** [comment]
I have this issue too .. tried fiddling with the transparency but that doesn't fix it.

I just have a black blob

![image](https://user-images.githubusercontent.com/24534482/51366143-1f5fc780-1b38-11e9-9c10-ccc297c9c632.png)

**Comment by VandenPlause** [comment]
As did I, I wound up adjusting the 3 slider bars in Overlay which is accessed on the gear icon, upper right corner.

After I moved sliders to 5%, 5%, 90% scale, and exited the program and relaunched, it works fine now.

**Comment by Arslin** [comment]
Yes that worked. Thanks for the help!

**Comment by VandenPlause** [comment]
Awesome, glad it worked!

**Comment by Sashweed** [comment]
yep I fixed it it. Manuel the scale bar is default set to %undefined% as soon as you click in the bar it resets everything and works
