### ISSUE TITLE
Cannot read property 'indexOf\' of undefined error when opening the Economy ta

### ISSUE THREAD

**Issue by pvdlg** [Manuel-777/MTG-Arena-Tool#155]
The error started to happen after upgrading to the last version of MTG Arena.
This is the full error:

```
IPC ERROR:  { col: 60,
  line: 494,
  stack:
   'TypeError: Cannot read property \'large\' of undefined\n    at /Users/pvdlg/git/MTG-Arena-Tool/window_main/economy.js:494:60\n    at Array.forEach (<anonymous>)\n    at open_economy_tab (/Users/pvdlg/git/MTG-Arena-Tool/window_main/economy.js:481:27)\n    at EventEmitter.<anonymous> (file:///Users/pvdlg/git/MTG-Arena-Tool/window_main/renderer.js:303:3)\n    at EventEmitter.emit (events.js:182:13)' }
```

If I replace the line `img.src = "https://img.scryfall.com/cards"+card.images[cardQuality];` in `economy.js` by:
```js
if (card) {
  img.src = "https://img.scryfall.com/cards"+card.images[cardQuality];
}
```
The error doesn't happen and I can load the Economy tab. However all cards reward are duplicated:
![mtg_arena_tool](https://user-images.githubusercontent.com/3250552/51372320-d7ef2200-1aca-11e9-8279-f2de2e525abc.jpg)

This is my output_log.txt

[output_log.txt.zip](https://github.com/Manuel-777/MTG-Arena-Tool/files/2771979/output_log.txt.zip)

**Comment by pvdlg** [comment]
Tested again and it seems it was fixed by 517e39e497005911222669ae4cf205b070c3236e

Thanks!

**Comment by pvdlg** [comment]
The bug seemed fixed with 517e39e but after playing a few games it's happening again. I'm using the last version from master.

The error message is now:
```
IPC ERROR:  { col: 41,
  line: 484,
  stack:
   'TypeError: Cannot read property \'indexOf\' of undefined\n    at /Users/pvdlg/git/MTG-Arena-Tool/window_main/economy.js:484:41\n    at Array.forEach (<anonymous>)\n    at open_economy_tab (/Users/pvdlg/git/MTG-Arena-Tool/window_main/economy.js:481:27)\n    at EventEmitter.<anonymous> (file:///Users/pvdlg/git/MTG-Arena-Tool/window_main/renderer.js:303:3)\n    at EventEmitter.emit (events.js:182:13)' }
```

Here is the corresponding output_log.txt:
[output_log.txt.zip](https://github.com/Manuel-777/MTG-Arena-Tool/files/2775279/output_log.txt.zip)

**Comment by Manuel-777** [comment]
Check [2.2.13](https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/v2.2.13)
[1f2c6c4](https://github.com/Manuel-777/MTG-Arena-Tool/commit/1f2c6c46232b08ebd23bf6baeb4a94a438493e2d) added a check to avoid undefined `change.delta.cardsAdded`

**Comment by pvdlg** [comment]
Thanks!
