### ISSUE TITLE
Deck overlay completely white

### ISSUE THREAD

**Issue by ianelletson** [Manuel-777/MTG-Arena-Tool#157]
Haven't played arena in a while, uninstalled the previous version of Arena Tool and then installed the newest.

Everything else appears to be working, but the deck overlay only loads a completely white placeholder.

![image](https://user-images.githubusercontent.com/1207114/51403835-3e9a2d00-1b17-11e9-8dbc-f2f171ff0f50.png)

**Comment by Arjay0** [comment]
Just wanted to add that I'm experiencing the same thing when doing a draft.

**Comment by Arjay0** [comment]
I ended up go into the overlay settings and adjusting the transparency levels and after exiting the draft and rejoining it was no longer white.

**Comment by Manuel-777** [comment]
This is already fixed in dev. Its an issue with overlay scale setting I added, its white because transparency was on.
