### ISSUE TITLE
My Decks Win Ratios do not show until you navigate to History

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#16]
I noticed that the first time you open MTGA Tool the Win Ratios for each deck in My Decks do not show up and you have to navigate to History and then back to My Decks for them to show up.

**Comment by Manuel-777** [comment]
Noticed, this was initially because the calculations for win/loss were obtained after initial rendering. Can be fixed now by re-rendering decks after w/l ratios are calculated.
