### ISSUE TITLE
Does not check for the same card from different sets

### ISSUE THREAD

**Issue by JerkyGunner** [Manuel-777/MTG-Arena-Tool#161]
So I finally decided to look through some of the decks on the Explore tab and I love the feature telling me the number of wildcards needed to craft the deck, however it needs a bit of a fix.

I opened a particular Mono Blue deck that I supposedly needed 6 Commons to be able to create and it appears the tracker cannot check whether I have the cards in question from other sets.

For example, the deck has 4 Mist-Cloaked Heralds, of which I have 5 in fact (4 from M19 and 1 from the Ixalan block) but since the uploaded deck was made with 4 from the Ixalan block the tracker is telling me I still need to craft 3 more.

Does the same thing with other cards in multiple sets.

**Comment by Manuel-777** [comment]
Made the UI to account for reprints as well as Explore, Explore changes should be visible now (please check if it works properly!)
Do notice changes may not translate to other parts of the UI, like My decks and deck details wc icons until next update.
