### ISSUE TITLE
Overlay not displaying any cards

### ISSUE THREAD

**Issue by cooIcat** [Manuel-777/MTG-Arena-Tool#166]
This is how overlay looks after last update

![24-01-2019 10-04-43](https://user-images.githubusercontent.com/46992346/51667093-87daf880-1fbf-11e9-8c82-958225319f83.jpg)

**Comment by Ragowit** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/31790/51738345-431e9280-208f-11e9-845a-09d288c5997a.png)

If there's anything else I can help with (log entries or whatever), just let me know.

**Comment by Ragowit** [comment]
Played a draft, and now it works again. Not displaying timers though.

**Comment by Manuel-777** [comment]
Hi guys! I urge you two to try latest pre release;
https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/v2.2.15

I tried to tackle most common overlay issues with it.
Please let me know if it works!

**Comment by omegaula** [comment]
Fixed after updating to 2.2.16
