### ISSUE TITLE
"Games until <rank>" shows previous rank

### ISSUE THREAD

**Issue by Fyren** [Manuel-777/MTG-Arena-Tool#171]
I just reached diamond rank.  I went to the history tab and noticed it still said "games until diamond: ~\<number>."  I didn't notice which rank icon was showing in the header.  I played another game (my first in diamond, and won) and went back to the history and it says "games until diamond: ~\<number>," has the platinum 1 icon in the header, but shows a diamond win rate of 100%.

I was on 2.2.12 at first, but I restarted and MTG Arena Tool offered to update to 2.2.13.  The history tab still looks the same.  I noticed there's a 2.2.15 tag on Github, but the client isn't offering to update, even after another restart.

In my log file, I see this event near the bottom:

```[UnityCrossThreadLogger]1/27/2019 4:30:20 PM
(-1) Incoming Rank.Updated {
  "playerId": "<snip>",
  "seasonOrdinal": 1,
  "newClass": "Diamond",
  "oldClass": "Diamond",
  "newLevel": 4,
  "oldLevel": 4,
  "oldStep": 0,
  "newStep": 1,
  "wasLossProtected": false,
  "rankUpdateType": "Constructed"
}
```

Let me know if you'd like me to e-mail my log file.

**Comment by Manuel-777** [comment]
Could it be 'Diamond' and 'Platinum' are swapped? I would find a screenshot useful.

**Comment by Fyren** [comment]
![image](https://user-images.githubusercontent.com/3320115/51808835-ac043700-2256-11e9-95fa-56720beee8a3.png)

The colored dot for the opponent's rank for the most recent game is correct.  It should say "games till mythic" since I'm currently diamond.  The icon and its tooltip in the header is for platinum 1 but should be diamond 4.

**Comment by Fyren** [comment]
I played a second game in diamond and afterwards, it updated.  It shows diamond 4 in the header and "games until mythic."  I saved a copy of the log before and after the second game, if you want them.

**Comment by Manuel-777** [comment]
No need, I found an error in the app around where we calculate the next rank and fixed it, but I am not sure if it was affecting that.
