### ISSUE TITLE
Reading log stuck at 68%

### ISSUE THREAD

**Issue by rramstad833** [Manuel-777/MTG-Arena-Tool#172]
Hi, I've been running MTG Arena Tool for many weeks now without too many problems.

I just upgraded to the latest 2.2.16 and when it restarted, it got stuck at reading log 68%.

I uninstalled and reinstalled and ran it again and the exact same thing happened.

The odd thing is I'd think the log had already been parsed by an earlier version of the program i.e. I haven't played Arena today, and the tool was running yesterday when I played, and 68% is presumably at least a few days ago...  if not more than that.

So something is likely broken.  I looked at the Troubleshooting document and I have no way of understanding the debugging console at all.

**Comment by rramstad833** [comment]
Ooh, very strange.  I started Arena, with the tool running, and now it's saying that it's reading log 200000000% percent i.e. it's counting up very rapidly... and now it's started over from 0% and is up to 10000%+ again.  The overlay is showing random stuff with names of players and whatnot... I see the same player names repeatedly....

Yeah, something is really broken with this version.

**Comment by Manuel-777** [comment]
The log will be parsed on startup event if it was parsed before, that is to not miss nay changes or events that could have happened in between play sessions.

The troubleshooting guide should help; Rename the output log with MTGA Closed, start MTGA Again and lastly start Tool.

Also, if you are using other trackers it is possible the log is not being cleared as it is suposed to, please let me know if that is the case.

**Comment by rramstad833** [comment]
Why does it loop forever when reading the log at startup?

I am not using any other tracker.

**Comment by rramstad833** [comment]
Anyhow, I did as you asked, renamed the log, restarted both, rebooted computer, it's working and I think I probably didn't lose too much match data.

Thanks.

**Comment by Manuel-777** [comment]
If you can please send a copy of the log at mtgatool@gmail.com for me to analyze what failed.
Thanks!

**Comment by jmhodges** [comment]
I'm seeing this as well. I'm not sure why this ticket was closed?
