### ISSUE TITLE
Incorrect mythic wildcards needed

### ISSUE THREAD

**Issue by combataran** [Manuel-777/MTG-Arena-Tool#173]
It shows that I only need to redeem 2 more mythic wcs for the Teferis, but I actually only have [1 mythic edition Teferi and 0 normal Teferis, so it should be 3 instead](https://i.imgur.com/47ysBno.png).

**Comment by Manuel-777** [comment]
What's your version number? This was addressed in 2.2.16

**Comment by combataran** [comment]
[2.2.16](https://i.imgur.com/tEEtbNz.png)

**Comment by Manuel-777** [comment]
Its a result of the issue I mentioned above, teferi is checked twice because it appears twice in the list, first time, since you already have one, no wildcard is added, second time, since you already have 1/3, two wildcards are added.
It's solved by grouping teferi as one item in the list.

**Comment by combataran** [comment]
How do I do that?

**Comment by Manuel-777** [comment]
Either use all the same edition in your deck list (can't because you have only MED?) Or wait for a fix

**Comment by combataran** [comment]
Since I only have one MED tef, wait it is then.
