### ISSUE TITLE
Incorrect mana histogram for split cards 

### ISSUE THREAD

**Issue by pvdlg** [Manuel-777/MTG-Arena-Tool#174]
![mtg_arena_tool](https://user-images.githubusercontent.com/3250552/52024207-efb4a600-24cd-11e9-9b60-118a012635e2.jpg)

This deck plays one copy of Response // Resurgence which is either 2 or 5 Mana. However in the histogram it appears in the 7 Mana slot. I'm guessing the client current add both cost.

I'm not sure what is the right way to display split card in the histogram, but displaying it with the sum of both seems wrong.
Maybe in such case the card should be accounted for both the 2 and the 5 mana slot? With maybe some sort of indication in the histogram bars?

**Comment by Manuel-777** [comment]
7 *is* actually the converted mana cost of it, thus the actual correct place to put it. trough I think using both 2 and 5 would be good from a deck building perspective.
I wanted to compare to most common deck builders to get an idea here, but I have seen some use only the lowest cmc side, one even uses average between the two sides, etc, it seems there is no consensus at all.

**Comment by ianelletson** [comment]
I think by default it _should_ show as 7. That's what it is in the rules. A toggle would be great though :)

**Comment by liberforce** [comment]
Here's the ruling about [split cards converted mana cost](https://mtg.gamepedia.com/Split_card#Rulings). The rules have [changed since Amonkhet](https://magic.wizards.com/en/articles/archive/news/amonkhet-split-card-rules-changes-2017-04-04).
