### ISSUE TITLE
Login button does nothing (2.2.17)

### ISSUE THREAD

**Issue by ZeMannFred** [Manuel-777/MTG-Arena-Tool#179]
Hi,

I installed the 2.2.17 and the login button does't work.

It is the first time I tried it.

Looks like a great soft :)

**Comment by devloloper** [comment]
I just had the same problem, worked around it by using the offline mode and then choosing login in the options, which made it return to the original login screen but this time with a working button.

**Comment by Manuel-777** [comment]
The login button was getting blocked when an error occured with the auth request, I made it so it doesnt block any more, and will be adding a popup to tell the user they have to try again.

**Comment by Manuel-777** [comment]
Closing, fixed in v2.2.19

**Comment by thiagopromano** [comment]
Still having the same problem on v2.2.19 😢
