### ISSUE TITLE
Naming a draft deck the same name as one drafted before causes it not to be tracked under 'My Decks' Tab

### ISSUE THREAD

**Issue by Jondrion** [Manuel-777/MTG-Arena-Tool#180]

**Comment by Manuel-777** [comment]
Deck names are not relevant to the decks tab, I may need an example of this in the form of a user config + log to reproduce it.

**Comment by AnnanFay** [comment]
I'm closing this and marking not reproducible. If anyone experiences this against please re-open and upload your user data file.
