### ISSUE TITLE
[Question / Suggestion] Allow two overlay windows to be open at one time?

### ISSUE THREAD

**Issue by KernelPainc** [Manuel-777/MTG-Arena-Tool#182]
I was just wondering how feasible it would be to have two overlay windows open, one showing your deck, one showing the opponent's deck.

**Comment by Manuel-777** [comment]
This requires a little rework on how the overlay window is handled , but it is definately possible. It can even be made to instantiate multiple specific overlays, one for each use (action log, current decklist, draft, opponents deck, etc) and replace the current implementation of "one for all".

I just wonder if it is really that useful for most users? In my experience using one tracker overlay is already a little space consuming, But I have seen others do this.

**Comment by KernelPainc** [comment]
The reason I ask is I generally have the tracker open on a secondary monitor, where there is plenty of room for more stuff.

**Comment by Manuel-777** [comment]
#413 makes this possible now! a beta release should be up tonight :)

**Comment by KernelPainc** [comment]
Thanks!
