### ISSUE TITLE
stuck at "Reading log: 2098%"

### ISSUE THREAD

**Issue by jmhodges** [Manuel-777/MTG-Arena-Tool#183]
I've seen other values, too. I'm not sure what's going on or how this got corrupted. Nor do I know how to fix it.

**Comment by Manuel-777** [comment]
Are you on 2.2.19? 
If so, send me the faulty log file at mtgatool@gmail.com.
Guide on how to find issues and logs;
[https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md](/TROUBLESHOOTING.md)
