### ISSUE TITLE
output_log contains no player data

### ISSUE THREAD

**Issue by shrddr** [Manuel-777/MTG-Arena-Tool#184]
After today's MTGA update the Tool loops forever at "Loading... just a moment" and there's a message below: output_log contains no player data. The file c:\Users\xxx\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt does exist and the size is 43Mb

**Comment by amollerson** [comment]
The error I'm seeing in my dev console is 

> (node:21064) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
writeOut @ internal/process/warning.js:18

Which I'm going to guess is what is causing the output_log load to fail.

**Comment by PeterBorah** [comment]
I'm getting the same. Also started immediately after the update.

**Comment by shrddr** [comment]
Oh well after a couple restarts it finally updated and works fine now. Try reinstalling the latest version manually if still stuck
