### ISSUE TITLE
A timeout draw is counted as a loss, at least for constructed event

### ISSUE THREAD

**Issue by Jazz640** [Manuel-777/MTG-Arena-Tool#186]
I cloned a deck (bant 62 bo1) to start a new count on the W:L ratio since I had made lots of changes (new deck is just bant 62). I played a constructed event and went 7:2 for the first run with the clone, but noticed the main page said my record was 7:3. Looking at the second image showing the game log, you can see where there was a draw - client lagged out and didn't start a match - shown in red. This is counted as a loss. There were no other games played with this deck and I included the last game with bant 62 bo1 in the second image to show where I switched.

The event page does show the correct W:L of 7:2.

edit: clicking on the game shows the same spells played as the prior game vs pistolpete which is why there are colors on the game log even though no spells were played.

edit: This is the latest version 2.2.17 on win7.

PS - Great software! Very clean interface.

![tool1](https://user-images.githubusercontent.com/47678738/52889309-f33e6300-3144-11e9-8384-fac54fe0abf6.png)
![tool2](https://user-images.githubusercontent.com/47678738/52889313-f76a8080-3144-11e9-8784-1c33056e378d.png)

**Comment by Manuel-777** [comment]
Hello! In v2.2.19 I added counts for draws, its not retroactive for past games trough, but future happenings of this should be counted correctly.
