### ISSUE TITLE
Issue installing v2.2.19

### ISSUE THREAD

**Issue by CrackTheSkye** [Manuel-777/MTG-Arena-Tool#189]
Hi

I'm having an issue with installing the latest update. The auto-updater wouldn't work, so I uninstalled and tried re-installing. This didn't work, so I tried uninstalling using Revo Uninstaller, removing all files and installing again as administrator.

I get this error however:
https://imgur.com/A3P4mTP

Translated from Dutch: "Can't gain access to the specified device, path or file. It's possible you don't have the right permissions."

This is a work pc, so there is some security stuff, but normally I get a prompt whenever installing something to put in my username and password. This doesn't happen now though, even when installing as administrator.

v2.2.17 worked perfectly.

Really hope we'll be able to solve this, I very much enjoy this tool.

**Comment by CrackTheSkye** [comment]
Well, apparently running in compatibility mode for Windows 8 magically fixed it, weird.

**Comment by Manuel-777** [comment]
Closing, glad you sorted it out !
