### ISSUE TITLE
Deck overlay is empty

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#19]
![screenshot](https://i.imgur.com/PluN0S8.png)

**Comment by Manuel-777** [comment]
Could you specify the version you are using is the latest? V2.0.18+
Also;
Check in settings persistent overlay is off
Check all overlay parts are visible in settings

**Comment by Xiaminou** [comment]
Yes I'm using 2.0.18.
Oh I see you have to tick everything off to have it be the same as it was before? Sorry I didn't know.

**Comment by Manuel-777** [comment]
It seems the new settings i added were defaulted to false , probably my fault!
