### ISSUE TITLE
Incorrect wild cards needed

### ISSUE THREAD

**Issue by combataran** [Manuel-777/MTG-Arena-Tool#190]
[Take a look](https://i.imgur.com/Zhxp7Pd.jpg) at the sideboard.

I need:
3 duresses
1 negate
1 cast down 
1 kraul harpooner
1 vraska's contempt and
1 hostage taker

The tool says I only need:
1 duress
1 negate and
1 kraul harpooner 

and estimating 3 approximate booster packs to complete the deck. 
My wildcard wheel says I need 7 packs for 2 rare wildcards.

Tool version: latest

**Comment by Manuel-777** [comment]
Make sure that tool is actually reading the log? close and open again. It is possible some cards (like Duress) , that have different versions, get different 'needed' ammounts since Arena does not take that into account while Tool does. But cards like Vraska's Contempt should be accounted perfectly.

**Comment by combataran** [comment]
I renamed the old log, restarted Arena then the tool, so it should be reading fine right?

**Comment by combataran** [comment]
![image](https://user-images.githubusercontent.com/2815112/53059670-a6ff7400-34f2-11e9-88eb-b483bb5f9086.png)
I loaded a new log file and it's now showing me something different.
