### ISSUE TITLE
Set Name "Magic 2019" should be "Core Set 2019"

### ISSUE THREAD

**Issue by jonathanjames30** [Manuel-777/MTG-Arena-Tool#194]
Not sure if this has been posted anywhere but when exporting the collection, I noticed the set "Magic 2019" in the csv and I believe this is the wrong name for this set. According to Scryfall the set is called "Core Set 2019".

Not to nitpick but I noticed this error when importing to my other apps and just wanted to give you a shoutout. 

![core set 2019](https://user-images.githubusercontent.com/327109/53287767-f62bfa00-37bb-11e9-890c-3acbc548507d.PNG)

Thanks for the good work btw!

**Comment by Manuel-777** [comment]
Fixed!
