### ISSUE TITLE
Missing wildcards count for sideboards

### ISSUE THREAD

**Issue by Manuel-777** [Manuel-777/MTG-Arena-Tool#198]
Currently cards in the sideboard are counted like an independent object to cards in the mainboard with the same name.

![image](https://user-images.githubusercontent.com/4711391/53426101-1d094c80-39c5-11e9-8984-17bb89c02b62.png)

In the image I own 2 of each glacial fortress and tyrants.

**Comment by lusbenjamin** [comment]
I have a fix for this (mostly) working locally, but it depends heavily on the work in https://github.com/Manuel-777/MTG-Arena-Tool/pull/253
