### ISSUE TITLE
Many archetypes are wrong

### ISSUE THREAD

**Issue by cooIcat** [Manuel-777/MTG-Arena-Tool#204]
Take a look:

![image](https://user-images.githubusercontent.com/46992346/53683393-91fbbf80-3d00-11e9-8e5f-fba83b630860.png)

- RWU "Mono blue"
- RG "Mono Red"
- green "blue stompy"
- ratless "rat colony"

![image](https://user-images.githubusercontent.com/46992346/53683407-c5d6e500-3d00-11e9-841a-1026037053ff.png)

How are these even assigned? I can't see any relevant code fragment.

**Comment by Manuel-777** [comment]
You can change the archetype if the app detected the wrong one in history clicking the X on the tag;
![image](https://user-images.githubusercontent.com/4711391/53683664-3faba600-3ce2-11e9-9952-21f32105899f.png)
 This will help the app to get beter results later, since it learns from what users set.

**Comment by Manuel-777** [comment]
And the line where it is detected automatically;
https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/window_background/background.js#L1619

It does need a better heuristic rather than linear comparision trough

**Comment by cooIcat** [comment]
Maybe opponent should play at least N cards to enable autodetection?

Also, I've manually changed some archetypes in history and now new matches are not detected automatically anymore.
