### ISSUE TITLE
Missing games from Events and Deck page (but which are present in match history)

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#208]
This is directly copied from the Discord chat so there's a bug report about it. Two issues which are probably related.

Okay, here's a weird bug. Match History is showing all 5 games from an event:

![image](https://user-images.githubusercontent.com/766048/53727926-5cbeb100-3e69-11e9-8d9f-94ba457105ce.png)

Events screen is only showing 2:
![image](https://user-images.githubusercontent.com/766048/53727945-62b49200-3e69-11e9-8dcb-4612ce9af6ed.png)

The other 3 records are in the data though, and link back to the event. The event's WinLossGate is just stuck in an old state.
![image](https://user-images.githubusercontent.com/766048/53728048-9f808900-3e69-11e9-9d32-f0e68ace9c97.png)
It's also happening to some of the more recent events actually. I just didn't notice.

I also have a case of missing games in the decks list but which are present in the event screen:
![image](https://user-images.githubusercontent.com/766048/53727967-6fd18100-3e69-11e9-8e11-e07db7efb742.png)

Deck listing:
![image](https://user-images.githubusercontent.com/766048/53727974-73fd9e80-3e69-11e9-9213-3683f43c61db.png)

**Comment by AnnanFay** [comment]
The Explore tab is showing the correct number of games for Sordes - 3:3 :
![image](https://user-images.githubusercontent.com/766048/53770012-831a3600-3ed5-11e9-82f9-9ab7885717c1.png)

It might be related to renaming decks or changing deck contents after the first game. I'm not sure, but there's one deck listed in My Decks which is using an old name but has the correct winloss record. However the record under Events is screwed up.

I think I edited Sordes before the last game, which might be why only 1 game is missing.

**Comment by AnnanFay** [comment]
This is probably relevant, but might be a different bug. If you edit a draft deck it doesn't immediately update in the decks list, but the overlay does update. This screenshot was taken after editing a draft deck but before starting playing:

![image](https://user-images.githubusercontent.com/766048/53831698-515caa00-3f7d-11e9-917d-f9d02d501bd5.png)

I made two recent edits to the deck. I added 1 hardy veteran, then I added the second. So both edits were missed. The overlay correctly lists 2 hardy veterans.

**Comment by Manuel-777** [comment]
Can you confirm the new match is listed in the event after you finished the match?
Specifically in `WinLossGate.ProcessedMatchIds` unde the event data, that would confirm its an issue when editing the list mid-event.

**Comment by AnnanFay** [comment]
After the first game everything is being tracked correctly on all three pages (decks/events/history) , and the deck is now listed with the correct cards in the deck list. However if you look at the deck it shows no edits: 

![image](https://user-images.githubusercontent.com/766048/53835111-946e4b80-3f84-11e9-9e50-1ec996b43ba4.png)

I'm going to make an edit after the first game and see what happens. Nope, both matches were recorded.  However the deck page still doesn't think the deck has been edited.

**Comment by lusbenjamin** [comment]
It is possible that #461 had some effect on this bug, but I did not confirm that draft deck edits go through that label handler

**Comment by AnnanFay** [comment]
I've not experienced this for a while so closing. If it happens again, or if anyone else has this happen, please reopen.
