### ISSUE TITLE
Current season not showing Vs. record correctly

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#209]
Originally reported by cornaljoe [here](https://discordapp.com/channels/463844727654187020/467737642306371584/548995575433920534).

The current Vs. ranks breakdown is a bit broken. In the current season I have played against Gold and Silver ranked players but the breakdown shows all games as against silver rank:

![image](https://user-images.githubusercontent.com/766048/53729088-2fbfcd80-3e6c-11e9-9aa6-8acda2381468.png)

I'm not sure if constructed has the same bug, I don't play it enough.

**Comment by lusbenjamin** [comment]
I think this bug was only for Limited and should have been fixed as part of https://github.com/Manuel-777/MTG-Arena-Tool/pull/351.
