### ISSUE TITLE
Overlay's clock doesn't stop after completing a match

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#21]
![screenshot](https://i.imgur.com/nL6TZYy.png)

Is this part of the new overlay or is it a bug? Either way I think it should at least stop the clock, which I guess is the main bug.

Edit: Okay turns out there is an option to make it persistent, so I'm changing this to "overlay's clock doesn't stop after completing a match".

**Comment by Manuel-777** [comment]
I'm surprised it's still showing the decklist trough, it should be cleared once the match ends on persistent mode.
Still the clock should be zeroed

**Comment by Xiaminou** [comment]
Yeah, it still shows the remaining cards and the opponent's cards until you enter another match.
