### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by cptcanuck1** [Manuel-777/MTG-Arena-Tool#220]
Today I could not log in on either of my computers.   I installed 2.2.20 and nothing else and now I get this error.  Even tried resetting the password but got no email from the site

![image](https://user-images.githubusercontent.com/47669416/54255828-dcf2af80-4516-11e9-8def-1f7c862d7ce7.png)

**Comment by gormleymark** [comment]
I have the same issue today.

**Comment by Manuel-777** [comment]
Sorry about this one, could you confirm is it has been fixed now?

**Comment by gormleymark** [comment]
@Manuel-777 confirmed fixed, thanks!

**Comment by mitch13** [comment]
Hi
I have the same issue now as well...
Thanks and BR
