### ISSUE TITLE
Reimporting a deleted deck should attach records to existing deck

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#227]
If I delete a deck it MTGA and later, say a few weeks, reimport the old deck from Arena Tool then the new MTGA deck should be tied to the existing deck's record in AT. 

I suggest the reimported deck should be treated as a new 'edit' in the deck history.

This should *only* happen if the original deck was deleted in MTGA.

There should be a confirmation dialog box.

**Comment by Manuel-777** [comment]
Each deck has a unique `id` tag in the log, when you import a deck, a new ID is created for it, thus it is treated as a whole new deck.

All of the history matches and events are tied to the old deck by their ID, so changing the ID in Tool to the new one assigned by MTGA while importing would mean searching and changing every record of that ID in the history to the new ID assigned. (I hope that made sense)

**Comment by AnnanFay** [comment]
It would be better for AT decks store an array of MTGA decks which they represent then there's no reason to change anything.

Probably keep `id` the same but have `previousIDs`.

**Comment by lusbenjamin** [comment]
I agree with the intuition to preserve old data as immutable and instead write translation for it. I think the idea to enhance our Deck data model in the Tool to allow it group several decks together as one would be powerful and useful! I do _not_ think it would be a good idea to attempt to automatically merge decks together in the Tool, regardless of existence in Arena past or present. I do love the idea of letting users explicitly merge together Decks in the Tool and then displaying unified history/edits/etc.

**Comment by tulasacra** [comment]
i was surprised this does not work. External IDs should be an additional property, and the tool should have its own IDs for the decks.
