### ISSUE TITLE
Mtg Arena Tool not displaying 

### ISSUE THREAD

**Issue by Nasamonkey** [Manuel-777/MTG-Arena-Tool#228]
I have been unable to see the program itself either when logging in or when offline.  It reads my logs and then minimizes and nothing will return it to the screen to view.

**Comment by Manuel-777** [comment]
Is the tray icon visible?

**Comment by Nasamonkey** [comment]
Yes.  I have managed to fix it I think.  I kept my mouse button clicked on it as it loaded my account and now it stays open on screen to view.  I had uninstalled and reinstalled about 5 times over the last few days trying to fix this, lol.  Thanks for getting back to me!

**Comment by Manuel-777** [comment]
No problem! Closing :)
