### ISSUE TITLE
Standardise loading bars - all web requests should have a loading indicator

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#229]
There should be a generalised indicator of a background web requests.

The current issue is that changing the filters on Explore tab starts a web request to get the data but there is no loading bar or indicator that something is happening.

Currently we have:

* Home screen load
* Explore screen load
* Explore filter category change (but not other filters)
* Explore deck view
* Draft sharing
 
The first 2 have loading bars but that last 3 are missing.

Instead of just fixing the issue it would probably be best if all external resource requests went through a single function which handled showing then hiding a loading bar at the top of the screen. Then it will just be an automatic feature for everything added later.

**Comment by AnnanFay** [comment]
There have been a few people on the Discord who reported bugs most likely caused by a failed web request. However currently when a web request fails there's not a message which explains what happens.

So in addition to automatically showing loading bars for every UI web request the loading bar should show an error if the request fails saying what happened. Something like: "Web request failed - please check your internet connection or try again later."

**Comment by Manuel-777** [comment]
in `http-api.js` there are some handlers for error catching , but these are for specialized errors, such as login/auth. I would add errors for the most common http errors (such as timeouts, 404, etc).

And I absolutely agree about the loading bars, altrough these should be activated only on user-input events, like changing to home/explore and opening external decks only, other requests should be excluded.

**Comment by Manuel-777** [comment]
Still missing some way for the renderer to know something failed, to avoid seemingly infinite loading bars on the screen when something fails and the messages do not arrive to the renderer process.
