### ISSUE TITLE
Bug: Action Log event ordering & missing event details

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#234]
The ordering of events in the action log is suspect. For example the 'win' event happens before damage dealt to the opponent which caused the win.

![image](https://user-images.githubusercontent.com/766048/54887400-9abc5d00-4e8a-11e9-9a11-f493f72195da.png)

Also, there is currently no way of knowing which card Unmoored Ego targeted?

**Comment by Manuel-777** [comment]
@lusbenjamin has the ordering been fixed ?

**Comment by Fyren** [comment]
Using 2.6.1, I have a log that seems to be out of order.  It says, roughly:

```
Opponent's turn begin
Opp drew a card
Opp played a land
Opp cast command the dreadhorde
Narset's ability put command the dreadhorde into hand
Command the dreadhorde targeted llanowar elves
Command the dreadhorde did 18 damage to opp
Opp life changed (-18) to -1
Command the dreadhorde put llanowar elves into battlefield
... (puts a bunch more stuff into the battlefield)
Fyren wins
```

Narset's ability is listed in the middle of casting/resolving dreadhorde.
