### ISSUE TITLE
Track mulligans and play/draw in game history

### ISSUE THREAD

**Issue by pvdlg** [Manuel-777/MTG-Arena-Tool#244]
In BO1 the meta is almost hyper aggro (mono white/mono red) and hyper control (Esper) decks. As a result you win most games when on the play, and lose most games on the draw or when you have to mulligan but the opponent doesn't.

Tracking this info manually, over a bit more than 150 games in BO1 with an aggro deck, my win rate is 82% on the play, 50% on the draw, for an average of 66%. The swing is pretty significant... I didn't tracked my mulligans.

To improve your total win ratio you can change your deck to either:
- Have to mulligan less often (play more/less lands)
- "Steal" a few more wins when you are on the draw (more threats, less removal)
- Avoid loosing when you are on the draw (add more cards that can swing the game such as sweepers)

We already have information about the color and archetype of opposing decks. Adding the draw/play info and the mulligan would improve the data quality when analyzing a deck performance. For example you could:
- Figure out if your deck is actually weak/strong against a particular archetype or if it just happens that you had to mulligan more than average against that particular archetype
- Find the games that you "should" have win/loss (ie. game won on the draw, game lost on the play) to analyze them in detail and figure out how to improve your deck/strategy.

In the History tab, for each game we could display an icon for play/draw and a number for mulligans (6, 5, etc...).
In the deck details:
- the histograms could be separated by play/draw
- the percentage of games where each mulligan happened (i.e. 5% mulligan to 6, 1% mulligan to 5, 0.1% mulligan to 4 etc...)

**Comment by Manuel-777** [comment]
Began to record who is on the play and on the draw. it was not being recorded previously, so the whatever statistics we make with it, will not be retroactive :(

**Comment by pvdlg** [comment]
That's still very valuable even if it's not retro-active

**Comment by riQQ** [comment]
Mulligans are tracked now
