### ISSUE TITLE
Draft decks no longer appear in decklist

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#249]
Bug: After making a draft deck it does not appear in the deck list. Previously the decks would appear immediately. Currently it only appears **after** playing games with the deck.

Use case: After constructing a draft deck you can export it for tools like https://mtgoncurve.com. If you need to play games before it appears in the deck list then this makes the export utility less useful for draft.

**Comment by Manuel-777** [comment]
I belive this is fixed now, at least in my (limited) draft experience , closing (but feel free to reopen if im wrong)
