### ISSUE TITLE
Economy Dates totals change

### ISSUE THREAD

**Issue by fbuttons** [Manuel-777/MTG-Arena-Tool#251]
First off, thanks for a great tracking tool.  Love it!

This may be a bug or may just be the way it works, but the totals on the Economy screen for days keep changing on me.  For example, early Sunday it said on Friday April 5th I gained 3500 gold spent 1500.  But by the end of the day Sunday it said that on Friday April 5th I gained 850 gold and spent 700.  It's like the historical dates are rolling 24 hour windows, rather than fixed midnight-to-midnight days.  

Also, as a feature request, would it be possible to show the total gold or gems change as a single number?  Like, a green number for a positive value for the day or a red number with a negative sign for a day that was a loss?  I'm scanning through trying to find out how much gold I'm earning a day and I keep having to do math.  :)

Feel free not to respond to either of these.  I mostly made the account and post to say thanks!

**Comment by Manuel-777** [comment]
I think you hit the nail with the economy 24hr window thing! I'll inspect the code later to see if thats rhe problem :D

**Comment by Manuel-777** [comment]
https://github.com/Manuel-777/MTG-Arena-Tool/blob/166a7465e7ce4b3c9bc800bd2744f2b759e82d9b/shared/util.js#L2263
