### ISSUE TITLE
Incorrect deck showing while playing if the deck has a similar name

### ISSUE THREAD

**Issue by timmiedinnie** [Manuel-777/MTG-Arena-Tool#260]
I have two decks:

"ABCDE" anda copied deck "ABCDE (2)".

When I play "ABCDE (2)", it shows the "ABCDE"  ingame.

**Comment by Manuel-777** [comment]
Naming should be irrelevant, do you have a screenshot of both decks and the in game overlay?

**Comment by timmiedinnie** [comment]
Oh weird, I'm at work (didn't know my github pw at home). I will try again at home and make a screenshot showing the tool showing a different deck then i'm actually playing.

**Comment by timmiedinnie** [comment]
Deck 1 

![image](https://user-images.githubusercontent.com/3026022/56216013-f2e91800-6060-11e9-87ac-4f87ae55154d.png)
Deck 2

![image](https://user-images.githubusercontent.com/3026022/56216041-fa102600-6060-11e9-9e9d-92761a4a66fe.png)


Oh i see now it shows another deck.

![image](https://user-images.githubusercontent.com/3026022/56216239-596e3600-6061-11e9-96ab-75356fccb4f8.png)


Maybe its something with the "(2)" ? And he shows only the latest deck?

**Comment by Manuel-777** [comment]
Please check here:
[TROUBLESHOOTING.md](https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md#if-you-have-any-other-unexpected-behaviour)

Also, an output log could help more, its located at;
`%APPDATA%\..\LocalLow\Wizards Of The Coast\MTGA\output_log.txt`

**Comment by AnnanFay** [comment]
As there hasn't been an update since April I'm closing this. The tracker has seen heavy changes since April and quite possibly this has been fixed.

If it is still happening please reopen.
