### ISSUE TITLE
Not tracking ICR rewards while playing BO3

### ISSUE THREAD

**Issue by ZetaVillegas** [Manuel-777/MTG-Arena-Tool#261]
I noticed today that the ICRs I get after winning a Bo3 game (from daily quests) aren't tracked on the ECONOMY tab. It only shows the gold I earned.

Since you play two games at a time, when you finish you have two rewards (assumming you win, ofc), X gold and a ICR usually. The economy tab is only tracking the gold gained, not the ICR.

**Comment by Manuel-777** [comment]
Fixed in beta, thanks for reporting!
