### ISSUE TITLE
Add total cards vs. unique cards stats

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#267]
E.g. for each set, be able to see "Mythic Rare:  12/16 unique, 39/64 total", instead of just the latter.  And apologies if it exists and I just didn't see it.

**Comment by Manuel-777** [comment]
Not sure if that PR is what you were looking for? please let me know!

**Comment by jeffchrisope** [comment]
Yep, I think that gives me the info I need.  It's a little on the cumbersome side, as ideally I'd envision seeing both the # of unique cards/# of total cards in, say, common WAR, instead of having to change the Singles/All Cards drop-down, then reselecting the right set … but it's okay.
