### ISSUE TITLE
Archetype entry dropdown UI element is chopped off

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#268]
When you start typing in the archetype textbox, the dropdown appears to give you choices … but you only can see the first line of the list, and even that's obscured.  Any choices below that are invisible.  Also, once you select one and commit it, when you erase it and try to get the dropdown again it doesn't seem to be there anymore at all.

**Comment by Manuel-777** [comment]
Closing, fixed in dev :)
