### ISSUE TITLE
Additional info call-outs for each game - draw/play and mulligan(s)

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#269]
I know this information can be gotten by drilling into each match screen and looking at the number of cards in the opening hand, and the first lines of the action log … but it would be AWESOME to see an icon or other indication in the game list itself that says draw/play and mulligan count.

**Comment by Manuel-777** [comment]
I know, its not optimal at all ! But the data is already set to be saved so it should be displayed in the history list soon :)
