### ISSUE TITLE
Ritual of Soot leaving mess in action log ...

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#272]
Not sure if this is particular to the entries Ritual of Soot leaves in the Arena logs or what, but my last game produced a lot of this (and the 'undefined' error burst kept coming up after most subsequent, non-related events …):

11:45:15 DrEvil casted Ritual of Soot
11:45:15 Ritual of Soot destroyed Rustwing Falcon
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 DrEvil resolved Ritual of Soot
11:45:15 Zhardumani drew a card
11:45:15 History of Benalia moved to ZoneType_Graveyard
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Zhardumani casted Snubhorn Sentry
11:45:15 Zhardumani resolved Snubhorn Sentry
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
11:45:15 Ritual of Soot destroyed undefined
…

**Comment by Manuel-777** [comment]
Closing as it should be fixed in v2.2.25, but please reopen or let me know if you see anything like this again!
