### ISSUE TITLE
'n cards left' on overlay is incorrect

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#273]
Opening hand, message says 51 cards left, but should say 53 (and indeed, the total of the numbers shown is actually 53, so not sure what's up …):

![MathOops](https://user-images.githubusercontent.com/6776224/56516304-f95b1200-64ee-11e9-9889-b662dfc12c93.png)

**Comment by jeffchrisope** [comment]
Note:  it USUALLY is correct ...

**Comment by Manuel-777** [comment]
I have rewritten the entire system that handles action log and cards left, so it should be more accurate now, expect to see the changes in next version!

**Comment by jeffchrisope** [comment]
Awesome!  Thanks!

**Comment by Manuel-777** [comment]
Please let me know if this has been corrected in v2.2.25! If so we can close this issue :)

**Comment by jeffchrisope** [comment]
I haven't seen the problem again - though to be fair, I didn't see it repro all that often originally.  Probably fine to just close this and reactivate if it pops again.
