### ISSUE TITLE
Supported on multiple machines? [Sync Tags]

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#276]
I was assuming that the fact that I have to login with a central account meant that data (match history, economy history, all that) was stored centrally … but now that I've installed it on a 2nd machine, I don't see any of the data.  Do I have to wait awhile for the clients to sync, or is this not supported at all?

**Comment by jeffchrisope** [comment]
... or perhaps this requires the $5/month Patroen level?

**Comment by Manuel-777** [comment]
Yes! Sorry if this isn't clear in the UI yet, data sync is exclusive for patreons :)

**Comment by jeffchrisope** [comment]
No prob.  I signed up, so I'll try again.

**Comment by Manuel-777** [comment]
Just saw the sign up, thanks !
Keep me informed how it goes :)

**Comment by jeffchrisope** [comment]
Hmm … the history items themselves show up, as does economy, etc., but when I edit the opponent deck archetype names (and colors, because that's cool!), the changes aren't visible on the 2nd machine, even if I logout with machine #2 and log back in.  Issue here?  I see the same problem with new keywords I put on my decks - they don't propagate over to the 2nd machine ...

**Comment by Manuel-777** [comment]
I have not considered to propagate those, I will se if I can add that!

**Comment by jeffchrisope** [comment]
Any luck at seeing if this will be possible?  The tags are definitely not core functionality … but they become kind useless if they don't sync between multiple devices, for those who are doing the multi-device thang …

Thoughts?
