### ISSUE TITLE
Not able to Register

### ISSUE THREAD

**Issue by KeithRWalker** [Manuel-777/MTG-Arena-Tool#284]
###### Issue:
After downloading, and following the register link on the log in screen of the app I cannot seem to register a new account. Tried using different passwords, emails, and made sure to click the recaptcha box. Just get a red box with no text. For one password I got a "password must be x characters" error, but not any other attempts.

###### Screen Cap:
![InkedmtgatError_LI](https://user-images.githubusercontent.com/47060623/56719767-06524e00-6707-11e9-9c7a-5f909110ab6a.jpg)

**Comment by Manuel-777** [comment]
Fixed!
