### ISSUE TITLE
Date stamps very wrong

### ISSUE THREAD

**Issue by jeffchrisope** [Manuel-777/MTG-Arena-Tool#291]
Seems new with the last update, but not 100% sure … this is the Events tab.  Individual games here (and games listed under the History tab) seem to be accurate, but the higher level event container is stamped or calculated incorrectly.

![BadDates](https://user-images.githubusercontent.com/6776224/56854627-8555ab00-68ee-11e9-9ee0-d2a9d4f64f2c.png)

**Comment by AnnanFay** [comment]
I believe this was fixed with the date parsing fixes a while back. If this is still happening please reopen.
