### ISSUE TITLE
Collection Improvements

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#3]
I don't know if there's anything planned for the Collection Manager but it would be nice to have a more advanced filter.
Things such as sorting by Rarity, Converted Mana Cost, Color etc...
I would also like to have a slider to zoom in or out, so we can change the size of the cards that are shown. It would allow me to be able to read cards without having to mouse-over.

On a side note: how does the "Newly acquired only" work? How long does it have to be for a card to no longer be new?
Would it be a good idea to add a button to "reset newly acquired" so people can decide? (Of course you'd also have the default behavior)

**Comment by Manuel-777** [comment]
Newly aquired compares with a snapshot of the collection taken the previous day. When the snapshot is 24hs old it is replaced by the current collection and so on.
More filters are coming! Ill update this issue when I add more.

**Comment by Xiaminou** [comment]
Bit of feedback on the "Cards Size" slider, the cards end up being pixelated if you zoom too much. And I think the slider should be in Collection (under the filters) so you don't have to navigate back and forth to find the right size. There should also be something that indicates the default setting on the slider.

**Comment by Manuel-777** [comment]
[4e188e16](https://github.com/Manuel-777/MTG-Arena-Tool/commit/4e188e16131cb30643e2916a811e5d957afb3e58) added a card sample on the settings page and increased cards quality on all cards.

**Comment by Manuel-777** [comment]
Added all filters mentioned by OP, next on the list:
- Separate name and type into two different search boxes.
- "Allow partial" in type search.
- Make spaces search for words instead of full text.
- Include oracle into db and as a separe filter.
- Format filter (should use formats.json from MTG arena's files)
