### ISSUE TITLE
Registration failure - red box

### ISSUE THREAD

**Issue by freakz1z** [Manuel-777/MTG-Arena-Tool#302]
I filled in all the required fields, clicked the captcha and got a "red box". 

![image](https://user-images.githubusercontent.com/50156728/56998106-4e132280-6baa-11e9-9427-949ddb92b649.png)

**Comment by Manuel-777** [comment]
Fixed! You caught me in the middle of some server work :)

**Comment by freakz1z** [comment]
Thank you!
