### ISSUE TITLE
[Suggestion] Explore tab QOL 

### ISSUE THREAD

**Issue by Architekt909** [Manuel-777/MTG-Arena-Tool#308]
It would be great if you could search decks by name in the explore tab. I was making a list of decks I might want to construct and didn't realize that this feature didn't already exist, and so I had to scroll back through the entire list to find them again.

And/or it would be cool if you could favorite/bookmark a deck in the explore list. I suppose these could then show up under the "My Decks" tab, maybe add a "Favorite" option to the drop down that's already there. Or perhaps just add a "Favorite" option to the drop down on the explore tab itself.

**Comment by lusbenjamin** [comment]
The second part of this suggestions was added here:
![image](https://user-images.githubusercontent.com/14894693/61566271-78011600-aa30-11e9-8466-186ebe86d99b.png)
