### ISSUE TITLE
Exclude Sparky

### ISSUE THREAD

**Issue by MTGMAD** [Manuel-777/MTG-Arena-Tool#315]
Is there a way to not track your games against sparky in your win / lose total?  I like to play against Sparky to really understand my decks, but I would rather not count those games.  So maybe an option to exclude tracking on username sparky?

Thank you

**Comment by lusbenjamin** [comment]
The tool should be doing exactly what you want already, I hope!

As far as I know, Sparky and practice matches should not have any effect on your data in the tool. I regularly use Sparky to debug during development, and I would definitely have freaked out if my daily 15+ concedes to Sparky had tanked my win rate.

Can you provide any more detail about where and how your practice matches are appearing in the tool?

**Comment by Manuel-777** [comment]
Maybe what @lusbenjamin means is fixed but in a pre-release, check the latest one here;
https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/2.4.0

**Comment by MTGMAD** [comment]
I just had it happen, Played one round against sparky and it added it to my overall rating.  The total win went up by one.
![adding](https://user-images.githubusercontent.com/14255934/57347641-9ab1ad00-7118-11e9-8eaf-e32ebdf9e3de.PNG)

**Comment by MTGMAD** [comment]
Sorry I missed the one about 2.4.0, loaded that one and all the sparky wins and loses went away.  Thank you so much for fixing that!

**Comment by Manuel-777** [comment]
Great! closing then :)
