### ISSUE TITLE
Tags and Archetypes Case Insensitive

### ISSUE THREAD

**Issue by lusbenjamin** [Manuel-777/MTG-Arena-Tool#316]
Deck Tags and Opponent Deck Archetype Tags blend together many different entries from the community with highly varied spelling and capitalization. Unfortunately, tags provide the most value in the tool when they group together nicely.

Simply changing how tags are stored/displayed/grouped into a case-INsensitive format would probably make both types of tags work better without having to tackle difficult clustering or NLP approaches.

**Comment by Manuel-777** [comment]
Closing, as community tags are now deprecated.
