### ISSUE TITLE
Manually changing history info?

### ISSUE THREAD

**Issue by Ymir90** [Manuel-777/MTG-Arena-Tool#326]
Is there a way to manually modify history info or logs? The program sometimes displays erroneous info (for example, I just went 1-2 on a game and in history it appears as 0-0) and it would be cool if there was a simple way to correct them.

**Comment by Manuel-777** [comment]
There is currently not a way to do this, although this is actually related to games ending in concessions or messages not arriving properly (like when you reconnect after the game has ended and you end in the home screen), thus Tool never captures the game end messages.

It would be nice if we could detect when a game ended and the result has not yet been submitted, then allow the user to set the result, I am not a fan of allowing users to change the history data without a good reason.
