### ISSUE TITLE
Overlay defaulting to Action Log

### ISSUE THREAD

**Issue by aculver** [Manuel-777/MTG-Arena-Tool#345]
Each time I open Arena Tool, the overlay always defaults to the Action Log instead of the Cards Remaining. This changed a few weeks ago. Can it be changed back? Or even better, always open to whatever was last displayed, or let us set a default in settings?

**Comment by Manuel-777** [comment]
Set the default mode to "cards left in deck" as before for the meantime, an option for this would be ideal :)
