### ISSUE TITLE
Remove Timestamp from Action Log

### ISSUE THREAD

**Issue by JShultz89** [Manuel-777/MTG-Arena-Tool#349]
The timestamp in the action log takes up a lot of space. Please provide an option to turn off the timestamp from the log.

**Comment by AnnanFay** [comment]
This is a good idea. We can potentially replace it with just seconds since game start. Then have hover over with the timestamp.

**Comment by Manuel-777** [comment]
I imagine we are talking about the overlay specifically, I like @AnnanFay 's idea a lot!
