### ISSUE TITLE
Import from other trackers (long term goal)

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#355]
I think this is going to be hard, but a very good long term goal. There are currently **6** trackers of some type and stuff which falls slightly short of being a 'tracker' such as MTGA Helper.

As much as feasible and legal we should be able to import data from those programs for new users. In addition we should not take steps to make our data hard to import by other trackers.

This would require a new screen in the settings menu and a dialog to new users advertising the import feature. Each of the different trackers should have it's own processor and list of user instructions.

Please discuss below potential issues, suggestions and recommendations.

**Comment by Manuel-777** [comment]
To start with this, what trackers support data export in some way we can make use of? I imagine most data would be relatively easy to import/convert but it may be missing some details we track and they do not. If we do not track some things they do we can always try to implement those features as well.
