### ISSUE TITLE
installer stuck half way

### ISSUE THREAD

**Issue by alcxander** [Manuel-777/MTG-Arena-Tool#358]
download fresh install of v2.5.0 but installer getting stuck and hanging on initial load bar. Unsure whats causing it

**Comment by alcxander** [comment]
version 2.2.25 can install for some reason

**Comment by Manuel-777** [comment]
v2.5.0 is the latest stable, so if it shows the updater for longer than a fraction of second you may have beta channel updates enabled?

**Comment by yutamago** [comment]
I have the same issue, but with the 2.5.7 installer.
