### ISSUE TITLE
Cannot run app

### ISSUE THREAD

**Issue by jonathanjames30** [Manuel-777/MTG-Arena-Tool#37]
Hey there, can't seem to run the latest version. When i runt the app it just gets stuck in the loading screen. I have uninstalled and reinstalled but does not seem to work...

Im using the latest version from the website. 
Windows 10.

Let me know if you need any other info.

**Comment by Sascha-Gschwind** [comment]
Just tried going back to the old version (2.0.27) but doesn't seem to solve the problem at all.

**Comment by Manuel-777** [comment]
Hi guys!
Try locating your log and config files (to debug possible issues);
Close MTG Arena and MTG Arena Tool.
First go to `%APPDATA%\..\\LocalLow\Wizards Of The Coast\MTGA\`
And proceed deleting `output.log`. Run MTG Arena, once open, run MTG Arena Tool again.

If this does not work, proceed to `%APPDATA%\mtg-arena-tool`
Locate a .json file named with your User ID, something like `0A1F2E3E4D5C6B7A.json`
Rename the file, adding something to the end. **Do not delete it!**

Run MTG Arena Tool again. If the last step worked, send the the .json file to [mtgatool@gmail.com](mailto:mtgatool@gmail.com) and I will inspect what is wrong with it.
