### ISSUE TITLE
Accounts / Sign in

### ISSUE THREAD

**Issue by Manuel-777** [Manuel-777/MTG-Arena-Tool#38]
Accounts is very important for the future of the app, It will be necessary for security and data recovery at some point, and other stuff like sharing options.

The idea would be to make register and sign-in as easy as possible;
- To register a browser page (a real browser page!) would be open at mtgatool.com, where your should enter; email, mtga username, and new password/confirmation.
- Once registered on the database an email should be sent containing an auth token. mtgatool should change to a screen asking for auth token. right after it was sent.
- The user should then insert the auth token in app to correlate the user name.
- Once verified you should be prompted for your password to finish sing in in as usual.

Before beginning the registering process , the current username should be verified to be non existent the database, so you can only start sign up if that MTGA user has not been used. The entire process will check on this several times.

To sign in the username should be obtained from the log and auto-completed (no other data from the log should be loaded then), and insert password
Once signed in the app should load that user's data *regardless* of whether or not the user is signed on MTGA or not. if not, a warning should be displayed and no log should be traced (like, ongoing games and such)

This requires some work on the UX, like adding a previous screen to LOADING, which is the first screen we see right now.  only when the user has left "remember me" selected AND the MTG Arena user is the same as the last time, we should continue sign in automatically with the auth token from last session.

**Comment by ecyrbe** [comment]
Please add sign in as an option and desactivate functionnalities that require to log in if the user does not register.

I like to not rely on a server and keep my data private. It's a functionnality that made me use MTGA tool over the other existing ones. I think i'm not the only one.

**Comment by Manuel-777** [comment]
Already implemented in dev, closing.
