### ISSUE TITLE
Every time the tool updates it deletes it self

### ISSUE THREAD

**Issue by nommi** [Manuel-777/MTG-Arena-Tool#394]
This has happened a couple of times on my computer already, it goes like this. I download the tool, use it for a couple of days, then comes the time when the tool updates（the tool at this time still works), then the next day when I start up the computer the actual executable is gone from my system. 

Looking more into it I can see that latest verion(2.6) is already downloaded in C:\Users\Administrator\AppData\Local\mtg-arena-tool-updater\pending

I install it and everything works again, this is on a Win10 and always the version before the latest release.

**Comment by Manuel-777** [comment]
Hi!
Could it be it only deletes the icon on desktop? Does your data remains the same when installing again ?

**Comment by nommi** [comment]
Hi Manuel, no the shortcut is still there but the actual exe is gone from the folder,so the shortcut is just a dead link. And yes my data remains the same

**Comment by nommi** [comment]
Found the solution! Seems like the problem is coming from windows permission shenanigans, where the update can't get permission to replace the original executable, I gave my self full controll of \AppData\ and the problem is fixed.
