### ISSUE TITLE
Transparency breaks scrolling in overlay

### ISSUE THREAD

**Issue by wassonan** [Manuel-777/MTG-Arena-Tool#397]
When turning on overlay transparency, I cannot scroll.

**Comment by Manuel-777** [comment]
This is a known one, and was known for a while. Its not a problem with Tool, but the 'hack' Electron (our framework) uses to achieve transparency.
The only current fix for this would be simply not rely on scrolling in the overlay, like, making the overlay grow when cards fill it up, or make the actionlog always scroll to the bottom.

**Comment by wassonan** [comment]
I see.  Thanks for the update.
