### ISSUE TITLE
Email address is case sensitive when logging in

### ISSUE THREAD

**Issue by paradime** [Manuel-777/MTG-Arena-Tool#398]
Build: 2.6.0
Environment: Windows 10

What happened:
- On a fresh install I was prompted to create an account. 
- I went to the website. 
- I put in my email address (I'll use an example here) `Paradime@gmail.com`. 
- I got the, _you are approved_ toast. 
- When I logged in with `paradime@gmail.com`, I got an error saying that account doesn't exist. 
- I typed in `Paradime@gmail.com` and was able to login.

What I expected to happen:
- When I log in with `paradime@gmail.com` I expect that the case sensitivity shouldn't matter and I should be able to log in with that email address.

**Comment by Manuel-777** [comment]
email addresses *are* case sensitive, so `paradime@gmail.com` is indeed different from `Paradime@gmail.com`. Altrough the way the system is programmed will not allow registering both emails.

**Comment by lusbenjamin** [comment]
@Manuel-777 is _technically_ correct that the local-part of the address is case-sensitive. I agree with @paradime that most users would NOT expect a modern app (or email server) to actually handle the local-part of the address as case-sensitive, especially since the domain-part is case-insensitive.

**Comment by thisguy23** [comment]
security feature... leave it in!

**Comment by AnnanFay** [comment]
As of 24/09/2019 This is resolved in the server code.

Emails are converted to lowercase before being used as user IDs. So it now doesn't matter what capitalisation you enter when logging in.
