### ISSUE TITLE
Do not close the main window when entering a match

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#4]
I'm often browsing MTG Arena Tool's main window while waiting for a match to be found and it is frustrating to have it close up on me while I'm looking at something because a match has been found.

**Comment by Manuel-777** [comment]
I agree, I found that situation before and hadnt thought about it as an issue.
Would simply disabling the main window from closing be good or is auto-closing the expected behaviour?

**Comment by Manuel-777** [comment]
Added option for this settings :D
