### ISSUE TITLE
Draft sharing options

### ISSUE THREAD

**Issue by Manuel-777** [Manuel-777/MTG-Arena-Tool#40]
Add more options for sharing drafts;
Make a button to add new invitations, each invitation contains the number of 'views' and a setting for expiration time _(1 day, 3 days, 1 week, 1 month, 1 year, never)_
You should be able to remove old invitations from here too.

**Comment by ianelletson** [comment]
Would you be willing to add a draft export as well? There are a number of draft viewers online, and as a user I would like to retain my data when possible.

**Comment by Manuel-777** [comment]
If you mean export by a share link, it is already implemented, but hidden until next version that should implement all of the above mentioned features.
Not sure if you mean export somehow differently than a shareable link?

**Comment by Manuel-777** [comment]
The only part missing is to be able to view old links and delete them (like Discord)
Also limit the number of links with short spans of time (like, links created within an hour or so must be the same, a new link must not be created to avoid spamming)
