### ISSUE TITLE
Events are not synced between computers

### ISSUE THREAD

**Issue by EgorKulikov** [Manuel-777/MTG-Arena-Tool#402]
Matches and everything else is synced, but not events

**Comment by Nolivfr** [comment]
Same here.
Also ranks, economy, collection, etc. are not properly synced.

Decks and history are correctly synced

Screenshots : 
Llanowar Elf background is the original MTGA Tool
Ghalta background is the synced MTGA Tool

![original_mtgatool](https://user-images.githubusercontent.com/7694177/62549726-4928d380-b869-11e9-91a5-6843a63c3035.png)
![synced_mtgatool](https://user-images.githubusercontent.com/7694177/62549727-4928d380-b869-11e9-8bb1-0dc9018a2f84.jpg)

![collection_mtgatool_original](https://user-images.githubusercontent.com/7694177/62550120-fdc2f500-b869-11e9-8b1d-0bfe52fe5dcf.png)
![collection_mtgatool_synced](https://user-images.githubusercontent.com/7694177/62550121-fdc2f500-b869-11e9-9e59-5530e19d1f01.jpg)

**Comment by AnnanFay** [comment]
Confirmed. None of the economy or events are being synced for me.

Collection should use the latest data from the log file and doesn't necessarily need to be synced.
