### ISSUE TITLE
Incorrect rewards

### ISSUE THREAD

**Issue by aroundightii** [Manuel-777/MTG-Arena-Tool#403]
I play a BO3, and win the game. It's my third and forth wins, and I get 200$. But in the economy tab, it shows only 100$. I think it's a bug. Please fix it. MTG Arena Tool version: 2.6.1

**Comment by AnnanFay** [comment]
Please provide more detailed information.

By BO3 do you mean BO3 Ranked, BO3 Draft or the BO3 Event?

By 200$ you mean 200 gems, or 200 gold?

The economy tab only reflects what is present in the game logs. For example if you get 500 gold from a quest and 300 gold from an event then the game will give you 800 gold but in economy this will be listed separately.

In your Economy page what is listed before and after the 100?

**Comment by aroundightii** [comment]
BO3 means traditional play or traditional ranked.  200$ means 200 gold. 
![01](https://user-images.githubusercontent.com/51105509/58763602-51297600-858f-11e9-8442-411c367e629b.jpg)
I think a screenshot will make my words clear. I am in Asia, GMT+8. So, I have new quests after 5 PM. 
I play a game of traditional ranked and get the reward which is 250 +100. And it shows 350 gold on the screen whereas the tool shows only 100 gold. I play another  traditional ranked and win 200 gold. And the tool still shows 100 gold. That is the problem I have.

**Comment by Manuel-777** [comment]
A sample log of this would be great, I cant seem to get two consecutive wins in bo3 :)

**Comment by Manuel-777** [comment]
A sample log of this would be great, I cant seem to get two consecutive wins in bo3 :)

**Comment by aroundightii** [comment]
![01](https://user-images.githubusercontent.com/51105509/58764127-3c041580-8596-11e9-954f-d1c03652f87c.jpg)
Is this ok?

**Comment by Manuel-777** [comment]
Managed to find the problem; The ID of the new economy reward was duplicate becase the timestamp and the context were equal, I added a new parameter (the rewards themselves) to the hash so they are differentiated now.
