### ISSUE TITLE
Show how many times on play/draw. 

### ISSUE THREAD

**Issue by Li2012** [Manuel-777/MTG-Arena-Tool#405]
This is a feature request. 
Please in addition to show play/draw win rate, also show number of times on play/draw, and maybe the absolute win/lose. 

Otherwise, consider making this an option.

**Comment by lusbenjamin** [comment]
@Manuel-777 originally had the sample sizes for play/draw win rates visible, but I hid them to try and make the stats panel less overwhelming. They can still be found by hovering over the play/draw winrate:
![image](https://user-images.githubusercontent.com/14894693/59369834-1db8bb00-8cf6-11e9-93f9-ac3fd2c253c8.png)
