### ISSUE TITLE
Gold gem equavalence. 

### ISSUE THREAD

**Issue by Li2012** [Manuel-777/MTG-Arena-Tool#406]
This is a feature request. 
Please make it an option, in the daily economy summary, to show only gold or gem, and convert the other to it based on some fixed conversion value. 

For example, instead of showing, I have earned 1k gold and 40 gems today, and now have 20k gold, 1k gem, show I have earned 1.2k worth of gold (1k gold + 40 gem * 5 gold / gem), and now I have 25k worth of gold. (20k gold + 1k gem * 5 gold / gem)

Background: 
Having to manage two different currency can be confusing or annoying. And to most player, regardless of paying or F2P players, they are mostly equivalent, and it can be easier to track one of them. A player who buy packs using gem and gold, would have 1:5 conversion rate, because 1 pack = 200 gem = 1000 gold. A player who enter draft using gem and gold, would have 15:100 conversion rate, because 1 draft = 750 gem = 5000 gold.

**Comment by Manuel-777** [comment]
The equivalences between gold and gems are quite obscure, it is not as simple as doing some math simply because the wildly different rates at which they are priced, also since they cannot be directly converted it would be misleading for people unaware of that.

**Comment by Li2012** [comment]
Yes, that's true. I'm proposing to add it as an option. So default people won't see that, but can be enabled by check a box in the option section.

**Comment by lusbenjamin** [comment]
This sounds similar to the gem/gold conversion ratio that @AnnanFay has as a parameter in their Spreadsheet of Epic Economic Arena Analysis. I think it could be a powerful new fundamental to build some estimation features about how valuable activity/events/games are. If we do build this, we should be extra careful to explain what it is and how it works (e.g. no actual affiliation with store, purely an approximation, which math it affects).

**Comment by Manuel-777** [comment]
Closing for now, there's a lot of things to consider and the possible confusions it may cause are just not worth it, to Begin with, there's no direct conversion between the two, so any math done using those values would be bogus .
