### ISSUE TITLE
Error parsing response (notifications)

### ISSUE THREAD

**Issue by Thaoden** [Manuel-777/MTG-Arena-Tool#433]
The error message 
> Error parsing response (notifications)

appears at regular intervals at the bottom of the main window.

Apparently, all is working as expected, so it's merely an inconvenience. I haven't been able to find an error in the application logs nor in the debug window.

**Comment by Manuel-777** [comment]
Unlink and linking discord again should clear it, seems an issue with  your profile not having any notifications at all :)

**Comment by Thaoden** [comment]
That may sound odd, but - how do I unlink discord? I never linked it, at least I never intended to...

**Comment by Manuel-777** [comment]
Edited my response

**Comment by Thaoden** [comment]
Yep, that worked. After unlinking again, there are no new error messages. Thanks for the quick help!
