### ISSUE TITLE
Sort by Winrate needs a min. of games set...

### ISSUE THREAD

**Issue by Sleepcap** [Manuel-777/MTG-Arena-Tool#436]
If you sort the "Explore" overview by winrate I get all these 5:0 and 1:0 first, as they have a 100% winrate.
Would be nice if I could set a minimum-number of games played with the deck to remove these (unhelpful) extremes.

**Comment by Manuel-777** [comment]
Limited the number of required matches to show up in explore to 15, but I removed the limit for Draft and Sealed events. Let me know if it works as you expected now :)

**Comment by Sleepcap** [comment]
Much better. Very good change.

**Comment by Manuel-777** [comment]
Closing as fixed ! 👍
