### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by MTGMAD** [Manuel-777/MTG-Arena-Tool#44]
I have to say this is a GREAT option, one question though are you going to add the MTG Arena formatting of cards on export? 

**How it exports now:**
4 Leonin Vanguard

**MtG Arena Format:**
4 Leonin Vanguard (M19) 22

**Comment by Manuel-777** [comment]
I am guessing you did not see the "Export to Arena" button? or am I missing something?

**Comment by MTGMAD** [comment]
I see that for the decks, but what I was referring to is on the collection page all it says is copy to clipboard.  I was talking in regards to exporting your entire collection is this something you are looking at changing the formatting for so it comes out in MTGA format.

Thank you
