### ISSUE TITLE
Running MTG Arena tool on Linux cycle on fails on first screen as it's unable to find logs

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#441]
I tried to run this tool from source on Linux; while I had no issue on a Windows computer, here it seems it can't find the logs on this Linux computer (that ran MTGA through Lutris/Wine), and is not letting user set where those logs are, therefore  looping within darkened screen stating "no log file found" without letting the user do anything.

**Comment by lusbenjamin** [comment]
I believe that the latest version 2.7.5 should have a bugfix for this that lets you set a custom location to look for the `output_log.txt` (a dialog appears on the darkened screen).

**Comment by Porkepix** [comment]
It indeed does, although it would deserve a graphical pick (actually I think it defaults to the correct path with standard Wine install, but I did the install using Lutris, which puts those in `~/Games`).

This is a bit offtopic, but in case you use Linux though, but after this, does it work for you? Here for me it runs, but I get no informations in MTGA Tool; looks like the logs contains almost nothing even though I played in the previous week. Either running through Wine kinda breaks logs, either it was wiped with the update (which would be surprising considering it did not on Windows)

**Comment by lusbenjamin** [comment]
It is not possible to take advantage of the user data sync feature across machines while being in offline mode.

**Comment by lusbenjamin** [comment]
We probably need better documentation about how accounts work and where your data lives. You may be looking for the feature that syncs data between machines automatically. The only description of it that I know of is on the patreon page: https://www.patreon.com/mtgatool

**Comment by Porkepix** [comment]
> It is not possible to take advantage of the user data sync feature across machines while being in offline mode.

Yes I know. I think that my Linux install lost most of its logs on update (or failed to store them, don't know between those).

I guess this issue have to be closed and maybe another one opened to improve logs location with graphical selection maybe?

**Comment by lusbenjamin** [comment]
Sorry to hear that the installation did not happen cleanly on Linux! You may have some luck asking if other users on the Discord use Linux.

Agree that we can close this issue for now. I like the idea of graphical selection, please do open separate enhancement request!

**Comment by Porkepix** [comment]
> Sorry to hear that the installation did not happen cleanly on Linux! You may have some luck asking if other users on the Discord use Linux.

Sadly, I'm not using Discord, it have pretty shady Privacy Policy I don't put trust in, as well as how they'll monetize this in the future.

(On top of that, I did give it a try some times for vocal in a browser and it was not working correctly).
That's a shame, would have been practical to talk otherwise :)
