### ISSUE TITLE
Need to click "continue offline" on every start

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#443]
If a user want to use the application without account, for just local features on the computer, he needs to click "continue offline" as you get the Welcome screen on every single start.

It should be possible to set definitely that you want to use it without account.

**Comment by lusbenjamin** [comment]
This feature request is my white whale. I have tried 3 times to get this to work, and each time I have failed for different reasons. 🤕 

Maybe the 4th time will be the charm!
