### ISSUE TITLE
View About page and edit App-level settings before logging in

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#444]
Settings can't be accessed from welcome screen so that user need to log in or click "continue offline". Access to settings shouldn't be tied to that.

**Comment by lusbenjamin** [comment]
I think Porkepix is suggesting that we break apart the application level settings from the user level settings entirely in the UX, and then make the application level settings available upon application start (before login). (It would probably be confusing/dangerous design idea to make the user level settings available to everyone prior to login.)

**Comment by Porkepix** [comment]
When you speak about user level settings, what kind of settings is this?
On purpose, I do not use any account in the application, does it mean I have some missing settings? 
Otherwise, I guess it means it use a dummy local account, so the same could be done?
I guess I'm missing on what have to offer the account to have a better understanding here.

(The same way, but it's a bit offtopic, if you do not use an account, the *home* of the application is completely empty and looks almost broken actually).

**Comment by lusbenjamin** [comment]
We currently support multiple different Arena accounts on the same machine. This will also cause mtgatool to have multiple user accounts and each one will have different settings (e.g. show a particular overlay).

There are also a few settings that only affect the entire application for all users (e.g. launch mtgatool on startup).

**Comment by lusbenjamin** [comment]
To get more specific about this, what are you trying to achieve before logging in? What is your use case for getting to the settings page earlier?

**Comment by Porkepix** [comment]
So, what difference is done between online accounts onto MTG Arena Tool server, and local ones, related to Magic Arena one? Can one MTG Arena Tool account be related to more than one Arena account ?

I guess the relation between accounts and what those allows or not would deserve some clarification :)

**Comment by Porkepix** [comment]
Mmmmh, I'm not sure what I wanted to do as it's from a week ago, but I think it could have be related to https://github.com/Manuel-777/MTG-Arena-Tool/issues/443 and looking for a way to keep it running as offline without having to click it on every start.

**Comment by Manuel-777** [comment]
Check #457 to know more about why we need accounts, it can be a little confusing since we don't really tie arena and tool users in any meaningful way other than what you do while logged in

**Comment by Porkepix** [comment]
Mmmmh, I guess at least behavior settings could be meaningful from event the first screen?

**Comment by lusbenjamin** [comment]
For debugging installation and updates, it might be useful to access the info and actions on the "about" page, too.
![image](https://user-images.githubusercontent.com/14894693/60622388-1769ac00-9d95-11e9-8457-c7d576a20669.png)

**Comment by Porkepix** [comment]
Yes, that's right.

**Comment by Manuel-777** [comment]
Implemented in v5
