### ISSUE TITLE
Sits on loading screen

### ISSUE THREAD

**Issue by MTGMAD** [Manuel-777/MTG-Arena-Tool#45]
I really enjoy this app, but every time it gets an update it never loads.  Says Loading Just a second..  Then after a while of not trying to load it, it just mysteriously starts working.  This happens on multiple windows 10 I use.   I can reinstall the old one it works just fine.  doesn't matter if it is an upgrade or a clean install.

**Comment by MTGMAD** [comment]
Works perfectly now!  Thank you, btw I really like the visual view you added when you are looking at decks.  Great work.

**Comment by Manuel-777** [comment]
Thanks, closing this now ♥

**Comment by MTGMAD** [comment]
with version 2.1.2 again the issue is happening on multiple windows 10 workstations.

**Comment by Manuel-777** [comment]
Marked 2.1.2 as pre-release for the moment, Does the loading screen show anything meaningful?

**Comment by MTGMAD** [comment]
Just says Loading just a second... Like last time

**Comment by Manuel-777** [comment]
Added a [troubleshooting guide](https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md) which I will update as new things like this come up. That should help us figure out exactly what happened.
