### ISSUE TITLE
Errors Updating Decklist Since M20 Update

### ISSUE THREAD

**Issue by battaile** [Manuel-777/MTG-Arena-Tool#466]
I noticed my decklists weren't updating as quickly as in the past, and after opening the dev console saw that I was getting errors like this:

Deck.UpdateDeckV3 39966551 Object
background.js:932 TypeError: Cannot read property 'forEach' of undefined
at onLabelInDeckUpdateDeck

**Comment by battaile** [comment]
Found this error:

Deck.UpdateDeckV3 39966551 Object
background.js:932 TypeError: Cannot read property 'forEach' of undefined
    at onLabelInDeckUpdateDeck

**Comment by Manuel-777** [comment]
Hi ! what version are you using?

**Comment by battaile** [comment]
Hi Manuel, I'm on 2.7.5

**Comment by battaile** [comment]
It looks like the error is occurring when its iterating the main deck, but I'm trying to verify that now.  My guess is that I created a deck and abandoned it with no cards in the maindeck but cards in the sideboard, and that's causing problems.

**Comment by Manuel-777** [comment]
Ok, will try to reproduce creating an empty main deck, thanks for the info! :)

**Comment by Manuel-777** [comment]
Was able to reproduce the bug, apparently we are not updating deck lists when a new deck is created, neither when we delete them.
