### ISSUE TITLE
Opponent cards overlay not resetting in BO3

### ISSUE THREAD

**Issue by wassonan** [Manuel-777/MTG-Arena-Tool#469]
When playing a best of 3 match, the overlay showing the opponent's cards doesn't reset between games.

**Comment by Manuel-777** [comment]
It is actually by design like that, so you know what he played in previous games as well (should also help sideboarding)

**Comment by wassonan** [comment]
Hmm is there an option to clear it if I want so track how many copies of a card I've seen in later games?

**Comment by greatscotty** [comment]
@Manuel-777 along the lines of this issue I believe I am getting some what I believe is unintended behaviour. In a BO3 the opponent overlay wipes and then starts in-between matches but ticks up all by double. IE. 2 copies of `loyal pegasus` were seen in round one. Overlay wipes, Round 2 starts `loyal pegasus` now records 4 copies after the wipe between rounds. Any thoughts. Thanks in advance love what you have built!!!

**Comment by greatscotty** [comment]
@SabreCat Love you thinking! But something of note is that we need to consider that Draft does not adhere to these rules on card numbers in that they are not capped, so a 4 limit cap might need to  be considers on game type.

**Comment by SabreCat** [comment]
@greatscotty True! Maybe there's no need for a cap, then, so long as it's only showing the maximum played across games in a given match.

**Comment by srulz** [comment]
Aside from fixing the doubling bug as mentioned by @greatscotty above, I would recommend that the played cards would be shown based on games instead of the whole game.

For example:

Game 1:
<card 1> <count>
<card 2> <count>

Game 2:
<card 1> <count>
<card 2> <count>

Etc.
