### ISSUE TITLE
Track progression wrong datestamp, rewards not listed

### ISSUE THREAD

**Issue by Thaoden** [Manuel-777/MTG-Arena-Tool#470]
Using version 2.8.1, I see that some datestamps for XP progression are off, getting it set to the time I open MTG Arena tool instead of the time I achieve my daily win.
Also, the track progression reward booster is listed as Quest reward.

![MTGA](https://user-images.githubusercontent.com/3832723/60984310-cb41dd00-a33b-11e9-9ace-5e41c90b752f.png)

**Comment by Thaoden** [comment]
Seems to be fixed in 2.8.2. Closing this issue.

**Comment by Thaoden** [comment]
Using 2.8.4, all of my yesterday's rewards are listed as earned today again; thus reopening.

**Comment by Manuel-777** [comment]
Did this ever happened again? There were many fixes to economy and dates since this issue was first created!

**Comment by Thaoden** [comment]
On 2.9.3, it seems to be working fine. I'll keep an eye on it, closing for now :)
