### ISSUE TITLE
Account Wipe

### ISSUE THREAD

**Issue by MTGMAD** [Manuel-777/MTG-Arena-Tool#48]
I am curious about the account wipe incoming what does that mean for our data in the app?

**Comment by Manuel-777** [comment]
Hi! The current plan for us is as follows;
- All data in the users PC ia safe (matches history, collection statistics, economy tab, etc), I can't touch that, unless user IDs change with the new wizards accounts. If that is the case renaming the user config files should work.

- All data in tge servers will be wiped, that is, the explore tab data and all matches saved. I will try to filter drafts as those are the only "shareable" ones at the moment.
