### ISSUE TITLE
Output_log.txt not reading and flashes after hitting save

### ISSUE THREAD

**Issue by Ycube** [Manuel-777/MTG-Arena-Tool#484]
MTG Areana Tool Build: 2.8.1
OS: Mac 10.14.5 (18F203)

![test](https://user-images.githubusercontent.com/8517649/61397917-c7ecab00-a87f-11e9-9cba-5e9f0db79580.gif)
When opening MTG Arena Tool, I am always prompted to Enter output_log.txt location. After hitting save, it does not seem to read it from the location. Then when I proceed to try hitting save a 2nd time, it flashes then the container model becomes a small bar and the opacity flashes around. 

Also adding in my username does not seem to make a difference.

**Comment by Manuel-777** [comment]
Reproducible in other platforms as well
