### ISSUE TITLE
Incorrect booster recommendation

### ISSUE THREAD

**Issue by combataran** [Manuel-777/MTG-Arena-Tool#488]
![image](https://user-images.githubusercontent.com/2815112/61526716-90335e00-aa4d-11e9-8974-be02a67c4d1d.png)

I literally only need to redeem 1 rare WC (of which I have 11), why is it telling me to open 6 boosters? Is it so that I get another rare WC and not have to redeem 1 of my own?

**Comment by lusbenjamin** [comment]
Thanks for reporting this! You are correct about what is currently causing the bad math. Should be fixed in the next version.
