### ISSUE TITLE
History is empty

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#50]
![mtgat2](https://user-images.githubusercontent.com/8670392/46213964-3d5fad00-c33a-11e8-95e6-d54713eb61ad.png)

**Comment by Manuel-777** [comment]
This is fixed for next update, unfortunately, old history will be visible but you will not be able to open decks or matches that contain KLD and AKH cards, since those were removed from Arena in the open beta patch ;/
