### ISSUE TITLE
Match History Issue

### ISSUE THREAD

**Issue by niiiptune** [Manuel-777/MTG-Arena-Tool#507]
Since the July 25 update, there seems to be an issue re. match history. Some observations:
- In "Action Log", only "Game X Start"/"X Conceded"/"X Wins" show up.
- Opponent deck doesn't show up in match history.
- All matches end up with "0:0".
- As a results, all the events end up with "0:0".

**Comment by DarkHarlock** [comment]
[Here](https://magic.wizards.com/sites/mtg/files/output_log_arena.txt) official log samples from MTG Arena team found in this [article](https://magic.wizards.com/en/articles/archive/magic-digital/mtg-arena-state-beta-july-2019-07-18)

**Comment by Manuel-777** [comment]
A fix is in `master` already and on https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/v2.8.5 :)
