### ISSUE TITLE
Add an icon for removed cards in "History of changes"

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#51]
![mtgat2](https://user-images.githubusercontent.com/8670392/46214872-51a4a980-c33c-11e8-9977-e0d3a934e2ec.png)

I took me a moment to figure out these were the removed cards. Adding a "red minus" similar to the "green plus" would help in that regard.

**Comment by Manuel-777** [comment]
It was there all the time!
![image](https://user-images.githubusercontent.com/4711391/46249448-ce4c8c00-c3ff-11e8-8fd7-60765f7197cd.png)

Maybe it did not load the image for some reason? try restarting mtgatool and see if it shows up.
