### ISSUE TITLE
Version 2.86

### ISSUE THREAD

**Issue by LuckyBlack72** [Manuel-777/MTG-Arena-Tool#514]
Stuck on Loading after login , the issue is lasting since 2 days ago
![Screenshot_1](https://user-images.githubusercontent.com/42611122/62235204-bdc4c380-b3cc-11e9-9ab9-2fd798ade3bf.jpg)

**Comment by Manuel-777** [comment]
Hello! A quick fix was pushed today (not a full update), Do you have auto login enabled?
If you dont, before pressing "log in" you should wait for the "Metadata Ok" message.
If you do, you can either change the settings file manually at `%APPDATA%/mtg-arena-tool/remember.json`, set "auto_login" to `false`, or try closing both MTG Arena and mtgatool, then start arena and finally tool (some users on Discord suceeded to log in doing that)

A fix in already on master, so except to see it in beta channel or stable soon!
