### ISSUE TITLE
Export/copy entire collection

### ISSUE THREAD

**Issue by danielvy** [Manuel-777/MTG-Arena-Tool#515]
Is it possible to export the **entire collection** to formats that can be imported in popular deck builder sites like deckstats, aetherhub etc? Or, is it possible to copy the entire collection to clipboard (like deck export) so it can be pasted to such places?

If these are not possible, would you consider adding such features?

Thanks.

**Comment by Manuel-777** [comment]
Hi!

In the collection tab there is an export button, and in settings you can customize the format, it's a CSV but it works just like any text file :)

**Comment by danielvy** [comment]
Yes, I am aware of the export button and how to edit CSV files.

But the format as exported by MTG Arena tool (regardless of column customization) is not acceptable by any major MTG site. And there is no way to simply copy the collection to the clipboard.
