### ISSUE TITLE
v2.1.6 wont load

### ISSUE THREAD

**Issue by k3lt** [Manuel-777/MTG-Arena-Tool#52]
It's getting stuck at 51% Loading Meta Data, and hangs on  "Loading Just a second."
![a](https://user-images.githubusercontent.com/22222328/46254758-98a5b280-c494-11e8-9eff-6b3f8c8812ef.png)

Windows 10 x64.

**Comment by Manuel-777** [comment]
Hello! please refer to the [Troubleshooting page](https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md) and see if that works.

Also, do you get to see the "processing log" popup at all?

**Comment by k3lt** [comment]
Yes i had the processing log popup, it couldn't find some kind of log in Appdata (i checked manually and it wasn't there)
But eventually it started working, so i guess it's resolved.

**Comment by Manuel-777** [comment]
Probably something strange in the log files, they get 'cleared' when you restart MTG Arena, probably thats why it works now.

Now im curious to see what caused it :P
