### ISSUE TITLE
Add rank filter on Metagame page

### ISSUE THREAD

**Issue by oysteinga** [Manuel-777/MTG-Arena-Tool#522]
**Description**
Having a rank filter in the Metagame section of the MTG Arena Tool webpage would make it more useful. I would expect that the number of aggro decks would decrease as you move up in ranks.

**Possible solution**
A checkbox for each rank would give a flexible solution, where you can select for which ranks you would like to see the metagame. Having all checkboxes selected by default and hidden behind some sort of "Filter" ˅, should yield the same default result as today, and not clutter up the page.

**Comment by Manuel-777** [comment]
The metagame page is not meant to do that, and doing so would require changing how it works internally, as it is designed to be a one time snapshot of the data, static and non filterable for better performance.

To do what you asked, explore is the closest, although you won't get meta shares
