### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Melissanoma** [Manuel-777/MTG-Arena-Tool#524]
ArenaTool has been using more and more memory lately. 

Here's a screenshot I just took where it is using over a gigabyte, across several processes, while Arena itself is closed and the computer is otherwise idle. Exiting the program resets it, but I set it up to launch Arena and ArenaTool with one shortcut so I often forget to close ArenaTool after closing Arena.

Using version 2.8.7

![screenshot](https://user-images.githubusercontent.com/53976427/62823996-b25c5f80-bb65-11e9-80ba-a8e73978f56e.png)

**Comment by Manuel-777** [comment]
Hello!
v2.9.0 should improve memory usage a LOT, can you confirm please ?

**Comment by Melissanoma** [comment]
Updated to 2.9.0, and technically yes it was a big improvement in memory usage. It went from over a gigabyte to only using half a gigabyte. Also, instead of having one super large process and several at ~50, it is now spread out over a few processes.

To be honest, I don't know how resource intensive a program like this "should" be, so I don't know how low it can get, but it feels kinda high.

![Untitled](https://user-images.githubusercontent.com/53976427/63049953-e5755a80-bea7-11e9-86b5-8e7c5df74932.png)

**Comment by Manuel-777** [comment]
Yes, Electron apps like ours are around the 300mb+ of memory generally, especially if they spawn sub processes/windows like we do. The general consensus seems to be that modern computers have enough memory to handle it, but we should be very careful about it (like before, you were absolutely right about being alarmed for such high usage!)

**Comment by riQQ** [comment]
Running 2.9.0:

![grafik](https://user-images.githubusercontent.com/3404787/63059653-4b85d000-bef0-11e9-8df9-598efc255644.png)

**Comment by lusbenjamin** [comment]
potentially fixed in v3.0.3
