### ISSUE TITLE
Separate Ranked and Constructed Events stats on Metagame page

### ISSUE THREAD

**Issue by MrSolid** [Manuel-777/MTG-Arena-Tool#526]
Metagame page includes constructed events stats.
Meta for ranked and constructed events pretty different and Metagame page in this state completely useless. It's better to separate stats for 4 pages(ce BO1, ce BO3, ranked BO1, ranked BO3) or at least remove constructed events data.
Also. I guess, it would be better to reduce stats data range to 5-7 last days to provide more relevant stats, because meta changes so fast.
![image](https://user-images.githubusercontent.com/20597527/62831339-22321f00-bc26-11e9-8691-2161a4df9b78.png)
![image](https://user-images.githubusercontent.com/20597527/62831341-30803b00-bc26-11e9-90b0-27bf249c014a.png)

**Comment by Manuel-777** [comment]
Since its BO1 , both CE events BO1 and Ranked BO1 should be the same? same goes for BO3 ranked/ce

**Comment by MrSolid** [comment]
No, it shouldn't be the same. People plays more fast aggro archetypes in constructed events and constructed event meta differs from ranked meta because of this, differs archetypes percentage in meta and winrates in CE completely differs from ranked . For example, in CE I play with 70% winrate, but in ranked I have only 50% with the same deck.
