### ISSUE TITLE
Collection stadistics Improvements

### ISSUE THREAD

**Issue by Suko1980** [Manuel-777/MTG-Arena-Tool#528]
Hola Manuel,

Lo primero agradecer el enorme trabajo que estas haciendo con la aplicación, quería hacerte una sugerencia en la pestaña de estadísticas de colección.

La cuestión es que las estadísticas están mal en algunas cartas y quería preguntarte si puedes ajustarla a la realidad, te pondré dos ejemplos:

1.- La colección de Mythic Edition es imposible de conseguir 4 copias ya que no dejan usar los comodines para obtenerlas y solo dieron 1 copia. Por lo tanto debería marcarse como 100% completada con 1 sola copia.
2.- Lo mismo ocurre con las tierras básicas de M20. Yo tengo todas y la aplicacion marca que me faltan 3 copias de cada una.

Un saludo y muchas gracias por tu trabajo.

**Comment by Manuel-777** [comment]
Hola!

Las ediciones especiales como las mythic edition *si* se pueden obtener las 4 copias, pero ya no, al no salir en boosters ni estar en la tienda, yo de hecho tengo 2 copias de teferi, de cuando se abrió la beta .


En el caso de las básicas, ya esta solucionado en el repositorio y en la versión de pre-release :)
