### ISSUE TITLE
Card Art Missing

### ISSUE THREAD

**Issue by MTGMAD** [Manuel-777/MTG-Arena-Tool#53]
I have this happening on 2 windows 10 computers.  In the collection Manager the card art is missing.

<img width="927" alt="card art" src="https://user-images.githubusercontent.com/14255934/46306337-98cbae00-c579-11e8-82cd-840903148bb0.PNG">

**Comment by Manuel-777** [comment]
Can you specify which version you are using?
Also, make sure you have internet whenever mtgatool is initializing, as it may corrupt the cards database when updating it.

**Comment by MTGMAD** [comment]
Internet is confirmed, and I am using 2.1.6

**Comment by Manuel-777** [comment]
I wasnt able to reproduce this bug, if you are still experiencing it I can only recommend running the app from source code instead of the installer to see _exactly_ what causes it
