### ISSUE TITLE
Multi language databases / database cache

### ISSUE THREAD

**Issue by Manuel-777** [Manuel-777/MTG-Arena-Tool#538]
We should make databases download only when they need to be updated.
Currently databases are versioned but we cant *check* the database version on startup, a new API endpoint is needed for this.

@AnnanFay 's input:
> Could make the files `./database/en-US/v0.8.1-database.json`, with `./database/version.info` containing the filename string `v0.8.1-database.json`.
> On startup the version is downloaded and checked against the local version. If there's a new version it downloads the correct language specific database.

We should also improve the database creation script to make it faster and output all languages at once with auto versioning.

**Comment by Manuel-777** [comment]
This is mostly done now! (6bc2c795269da8611fa2777234b213155519ba52) We just need to add a dialog in settings to change the desired language in settings.

**Comment by spphinslove** [comment]
Can't wait to use Chinese.
Any plan to make GUI support Chinese?

**Comment by Manuel-777** [comment]
f106ed27fab52e5a045f99c9bfb84dbad93a24e6 now allos to change between different languages in settings.
