### ISSUE TITLE
Events draft filter not showing WAR

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#542]
The filter implies it displays ranked draft events for the current season, however RNA and WAR are missing when I select the filter. If not the current season then it should still show WAR.

![image](https://user-images.githubusercontent.com/766048/63290483-61f9a600-c2b9-11e9-8c3b-c4a0827b3ca3.png)

**Comment by lusbenjamin** [comment]
This also means that the Ranked Limited pre-set filter (when the user clicks on the limited rank icon) is currently wrong and the estimated games to reach next limited rank is only using a partially complete set of data.

**Comment by Manuel-777** [comment]
Wasn't this because of the server downtime causing #547 issues ?
