### ISSUE TITLE
Draw overlay can become messed and retrieve in library cards that were not

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#543]
During a game, I had like around 30 cards left in library and overlay was correct, and suddenly, many cards already played got back into the overlay while it was not in game.

I'm not sure because I didn't saw it directly but it _might_ have happen after an Ashiok activation on me where quite some cards went from my graveyard to exile and it looks like MTG-Arena-Tool got them back into library.

I have a screenshot showing I have 26 cards left in library and MTG-Arena-Tool says I still have 37, but appart from that it doesn't show much more things. I don't know if it's possible to export a game log nor if it would show anything.

**Comment by Manuel-777** [comment]
Some times the logs can skip data when there are too many game objects in play, this happens with Ashiok and Scapeshift (and a couple other cards, but those are the most common lately). Unfortunately we cant do much about it , since its a problem with how Arena dumps the logs data.
