### ISSUE TITLE
Hide Share button when user is offline

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#545]
I tried to use the share button in a game recap to help for another issue report and it seems to loop indefinitely and do nothing.
I use the application offline, I guess this might be related?

**Comment by Manuel-777** [comment]
Indeed, sharing is not possible in offline mode

**Comment by Porkepix** [comment]
Can't this be done anonymously? Otherwise, maybe the features not working offline should be somehow hidden?

**Comment by Porkepix** [comment]
Ping @Manuel-777 ; is it possible to have some answers for the post above?

**Comment by Manuel-777** [comment]
I am most likely hiding the feature or adding a popup telling users to create an account / using online mode instead, as I want people to know about the benefits of using an account when they are offline.

**Comment by Porkepix** [comment]
So, should this one be hidden too?
Excepted if it's possible to have it working offline as I guess share is just creating a link with either a decklist or a game history?

**Comment by Manuel-777** [comment]
db1cedb99ab9bb8c82aac6c17d96ce653b5ccb75 fades the icon when youre offline and tells you to log in if you hover it.
