### ISSUE TITLE
Application sometimes go back to main "tab" by itself

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#546]
It seems to happen either randomly, either while actually playing a game (I think I mostly notice this during games, but I think not for the last one).
The symptom looks like these:
- I'm currently looking at the collection stats, and it goes back to the collection main page;
- I do a search in the collection and it cancels the search, staying on the page but without the search;
- The last one where I was not in game but in only happened one time so I would need to confirm it really happened: looking at game recap, it went back to the game history list.

**Comment by Manuel-777** [comment]
This is seemingly fixed in dev and should be in next release

**Comment by lusbenjamin** [comment]
this is actually fixed in #559

**Comment by Porkepix** [comment]
@lusbenjamin For your information, just experienced this again on latest stable release (2.9.3). I was doing some search in the collection tab and when the game notified it was my turn, it went back to the standard collection view. I guess this needs to be reopened.
