### ISSUE TITLE
Overlay keyboard shortcut active when Arena not running/doesn't have focus.

### ISSUE THREAD

**Issue by doug-w** [Manuel-777/MTG-Arena-Tool#549]
If you enable the overlay and overlay shortcut then Alt-1 - Alt-5 will be eaten by the tool regardless of if you're playing Arena.

**Comment by Manuel-777** [comment]
This is actually intended, they shortcuts are always active regardless or Arena state. You can change the shortcut in `Settings > Shortcuts` if using 2.9.1.
