### ISSUE TITLE
Overlays not appearing

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#551]
For the last couple of weeks, my overlays have refused to show up. I have Overlay 1 and 2 enabled, with "Deck" and "Opponent" selected, but all that happens when a match begins is that the app's main window minimizes.

Things I've tried:

* Disabling and re-enabling the overlays
* Clicking "Reset Position" on each overlay
* Using the Alt+Shift+(number) and Alt+Shift+E keyboard shortcuts
* Changing the option in the "Overlay Display" dropdown--it sticks to "0 (primary)" and refuses to change to "1"

**Comment by Asatas** [comment]
Same here

**Comment by Manuel-777** [comment]
I recently pushed a fix (1ac6f8b7061ce850c7056046c5d55a4fc7414ed8) to an issue regarding multiple displays and the new overlays, like @SabreCat describes on the last point. However this should not cause the overlays to "not show up", I think the problem may be related.

Try 2.9.1 (latest beta release) and click on "Reset Position" at the end of that overlay settings. If you are not in a match you willl have to enable "Always show overlay" to test. Also, te debug weter you can or cant see the overlay properly , try edit mode (default `Alt + Shift + E`)

**Comment by SabreCat** [comment]
OK, seems to be working now! Perhaps the windows were getting lost somewhere on the main display despite being set to "Always on top"...
