### ISSUE TITLE
Multiple displays with different resolutions not handled correctly

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#555]
I have an odd monitor setup, where the primary display is 16:9 1920x1080 and the secondary display is 4:3 1024x768. I run MTG Arena on the primary display and the Arena Tool on the secondary. If I spawn an overlay on the 4:3 monitor, then drag it over to the 16:9, the overlay won't drag all the way to the top of the new screen--it stops short.

**Comment by Manuel-777** [comment]
Hello @SabreCat ! I pushed a possible fix for this in c208902ba1281a6095a562d5b25bc90f58c603a0 , can you confirm its fixed in release v2.9.2 ?

**Comment by SabreCat** [comment]
Now it won't move from one monitor to the other at all!

**Comment by Manuel-777** [comment]
To have the overlay in your second display you must now select the display in settings and the ovelrays will only be active in it;
![image](https://user-images.githubusercontent.com/4711391/64142813-0284b580-cde4-11e9-8e35-20e6e748ac22.png)

**Comment by SabreCat** [comment]
Ah, ok! That's working, then!
