### ISSUE TITLE
Sort by percentage draw.

### ISSUE THREAD

**Issue by hadronflux** [Manuel-777/MTG-Arena-Tool#56]
A feature request, sort the cards in the overlay by percentage chance to draw. With the percent numbers so small and out of order, one has to spend more energy than necessary to see what is likely to pop up.

**Comment by Manuel-777** [comment]
Done, thanks for the idea! 👍 
![image](https://user-images.githubusercontent.com/4711391/46919095-6de94d00-cfb0-11e8-9447-9e7c2a3ddbc8.png)
