### ISSUE TITLE
Windows 10 taskbar will not appear over other windows

### ISSUE THREAD

**Issue by Donavan** [Manuel-777/MTG-Arena-Tool#560]
If MTG Arena Tool is running and I mouse over my taskbar, it appears under other windows.  If I shut down the tool it correctly draws on top again.

**Comment by lusbenjamin** [comment]
I can reproduce this issue.

To clarify, this only affects users with "Automatically hide the taskbar in desktop mode" enabled and probably only affects the Beta branch (since stable still uses the old overlays).
