### ISSUE TITLE
2.9.3 stuck on loading in Linux

### ISSUE THREAD

**Issue by qiemem** [Manuel-777/MTG-Arena-Tool#567]
2.8.7 was getting stuck on loading with a message about no user data in output_log.txt so I updated to 2.9.3. However, it was still stuck on loading:

![Screenshot from 2019-09-05 09-01-21](https://user-images.githubusercontent.com/28215/64359265-d83a2000-cfbc-11e9-9b5c-debf0fe9037e.png)

So I wiped the MTG-Arena-Tool config folder, but to the same result. None of the logs inside the config directory seem to contain anything, but let me know if there's any information that would be helpful.

Running Fedora 30, Gnome 3.32.2.

**Comment by battaile** [comment]
You have to go into Account Settings in Arena and enable detailed logs.  Its a setting that was just added with the latest patch and is defaulted to off.

**Comment by Manuel-777** [comment]
This i coming up very often despite the popup explaining what the problem is :)

**Comment by qiemem** [comment]
Oh sorry! Completely misread the popup. Even though it clearly says in Arena, I thought it was referring to a new feature in arena tool or something. Sorry about that!

You might make the message. "MTG Arena Tool will not work until you enable this feature in Arena" or something, just to make super clear.

**Comment by battaile** [comment]
"You might make the message. "MTG Arena Tool will not work until you enable this feature in Arena" or something, just to make super clear."

I'm not a contributor on the project but feel free to submit a pull request.
