### ISSUE TITLE
2.9.3 intercepts clicks on other windows in Gnome

### ISSUE THREAD

**Issue by qiemem** [Manuel-777/MTG-Arena-Tool#568]
When I run arena tool after upgrading to 2.9.3, I can no longer click on many of the other windows. Arena Tool works great, as does Arena, but I can't click on, e.g., my file browser or terminal. The gnome dock and menu bar also become non-clickable. It appears that primarily the Gnome native apps are affected; Firefox and other non-native apps continue to be clickable. In order to be able to interact with other apps again, I have to kill mtgatool (I can't quit normally since I can't interact with the system tray icon). Only running mtgatool and then running `killall mtg-arena-tool` afterwards is a workaround, but obviously not ideal.

**Comment by britishben** [comment]
May not be the exact same issue, but I've found on Win10 it seems to happen if the card "hover" is stuck open.  Mousing over another card in the overlay to collapse the "hover" gives me mouse control back.

**Comment by Manuel-777** [comment]
Its a problem with the overlay not intercepting the "hover out " events on it's elements, a quick fix when this happens is to toggle edit mode using Alt+Shift+E.

**Comment by gregersn** [comment]
I experience the same as Manuel-777, I believe. I can not get the overlays to register anything at all, unless I go into edit mode. (Gnome, Ubuntu)

**Comment by qiemem** [comment]
Thanks for the help, @Manuel-777! It looks like toggling alt+shift+E can restore functionality, though it's inconsistent. Seems like I have to do a couple cycles to get it to work. Good to know you're a gnome user too :)

**Comment by qiemem** [comment]
I take it back: alt+shitft+e does not seem to help. It does seem like things will start working at some point (especially while Arena is running), but alt+shift+E doesn't actually seem to have an impact, or if it does, there are other necessary preconditions for it to help that I haven't figured out yet.

**Comment by qiemem** [comment]
Awesome! That worked! Thank you!

**Comment by bauris-prvt** [comment]
Crossposting from #580. The latest appimage 2.9.5 seems to solve my issue as well. Thank you again for looking into this!
