### ISSUE TITLE
MTG Arena tool can get stuck in a loop on startup if it finds an empty output_log.txt

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#569]
The issue *might* be fixed in latest release, however I have no way to check it.

Problem happened with latest 2.8.x version and after latest MTGA update that made changes to logs, and therefore emptied the file.

Next launch after this resulted in a loop as visible on the joined screenshot

![mtg-arena-tool-loop](https://user-images.githubusercontent.com/709500/64469736-82d64e00-d137-11e9-8bd6-4c83d60ec4ef.PNG)

This loop never ended *and* blocked the access to the settings pane, disallowing the user for a manual update from within the application, therefore requiring a manual update by going to download the setup file manually.

I opened the issue as after updating I won't be able to check if the issue is still around.
How do you want to proceed?

**Comment by Manuel-777** [comment]
The auto updater should launch before that screen trough? Try launchin arena tool again see if it updates.

**Comment by AnnanFay** [comment]
Also, all newer versions of the tracker have the version number imprinted in the lower right corner. This doesn't which means it's quite old?

**Comment by Porkepix** [comment]
> The auto updater should launch before that screen trough? Try launching arena tool again see if it updates.
> If it doesnt download from here:
> https://github.com/Manuel-777/MTG-Arena-Tool/releases/latest

So yeah, after relaunching it actually auto-updated, I then had to relaunch mtga by checking the option for detailed logs (just checking it was not enough). I guess we can close this issue.

> Also, all newer versions of the tracker have the version number imprinted in the lower right corner. This doesn't which means it's quite old?

As said above it was the latest 2.8.x ie. 2.8.7, which was the last stable version up until yesterday.

**Comment by AnnanFay** [comment]
> As said above it was the latest 2.8.x ie. 2.8.7

Sorry, missed that bit when I read it. Glad it's working now.
