### ISSUE TITLE
[Windows] If taskbar is set to always visible, new overlays make it black

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#573]
As explained through title, on Windows if user have set the taskbar to be always visible, then new overlays interface make this taskbar completely black (still possible to interact with it though).

EDIT: Issue reproduced on Windows 7; no issue if taskbar auto-hide.

**Comment by Squints11** [comment]
I have the same issue on Windows 7, regardless of my taskbar settings.  Any other ideas what could be causing this?
