### ISSUE TITLE
Won't reopen after close

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#584]
When I finish with Arena and the Tool for a bit, I close the Tool, causing it to minimize to the system tray. After doing so, however, I can't get its main window to come back up, either by double-clicking the system tray icon or by right-clicking and choosing "Show"--I have to right-click, quit, then relaunch the Tool.

**Comment by SabreCat** [comment]
It doesn't seem to happen immediately; if I just close and reopen, it's fine. But if I close, go to work or whatever, then come back and try to bring up the Tool in the evening, it's stuck.

**Comment by SabreCat** [comment]
After a bit more observation, I think it's not duration in the system tray that does it, but the method used to close it. If you "X" from within the app, it's fine, but if I e.g. use Win 10's "peek" feature to mouse over the window in the toolbar and close it from there, it refuses to come back from the system tray.

**Comment by Manuel-777** [comment]
That makes sense!
Closing from the peek window definitely closes the process, thus not allowing tool to come back

I have to check if it's possible to disable the peek close, as that is not intended to happen

**Comment by SabreCat** [comment]
Other close-to-tray apps do seem to handle it OK, so hopefully Windows provides some hook that'll let you do what you need to!

**Comment by Manuel-777** [comment]
Hopefully there's a hook that tells the app that button was pressed instead of directly closing the window, ill investigate!

Notice we are not using default window controls on top, so we need to eliminate the default ones or override them like that

**Comment by SabreCat** [comment]
Now the entire app closes, removing it even from the system tray, on a Windows-based close. Was that the intended fix?
