### ISSUE TITLE
Overlay Size Change

### ISSUE THREAD

**Issue by theelkspeaks** [Manuel-777/MTG-Arena-Tool#59]
The Overlay is extremely large, I would really appreciate being able to make the in game overlay smaller.

I love the tracker, thanks for your hard work!

**Comment by Manuel-777** [comment]
Hi!l there!
The overlay can be dragged and resized to pretty much any size, or you mean scaling it down as well

**Comment by theelkspeaks** [comment]
When I make the overlay smaller, the cards stay the same size, unless I'm doing something wrong

**Comment by theelkspeaks** [comment]
Yeah, either that or having them shrink proportionate to the window as they window rescales - either way would help me shrink the overlay in game to fit it more comfortably while keeping it usable

**Comment by Manuel-777** [comment]
![image](https://user-images.githubusercontent.com/4711391/47607522-7b162b00-d9f7-11e8-8a76-aa395cd43f62.png)

This is how I managed to implement this without messing up the current tiles, it scales down the whole window (as if you were zooming out) depending on the window size. Right now it only scales down when it is smaller than 256px, at a scaling factor of width / 256 (if window is 128px scale is 0.5)

I plan to make a settings input "scale down when smaller than x", where you would select the size you want the window to start scaling down.
