### ISSUE TITLE
Log sharing link not generating: 'Match not found' error

### ISSUE THREAD

**Issue by jumpluff** [Manuel-777/MTG-Arena-Tool#590]
Version: 2.9.3
Problem: When trying to share the human-readable log of a game, the 'link for sharing' field is blank, I get the WUBRG progress bar, and then a 'Match not found' error. No link. 
Fixes attempted and failed: Changed expiry date. Tried with other matches. Restarted MTGATool. Gave MTGATool administrative permissions. Logged in and out of my Arena account to generate a new log. 
Other: Match occurred less than 24 hours ago. Logs exist on my hard drive and tracker produces a complete action log. Can also no longer export to .txt to share (I assume that was removed?). I have never used the sharing feature before, so I don't know if it would work under other circumstances. I have successfully exported games to .txt in previous versions.
Dev console: There are errors. I'm hesitant to paste them in entirety, so I'll email and link to this issue.

Thank you for reading.

**Comment by riQQ** [comment]
Works for me. Does this still not work for you?
