### ISSUE TITLE
Application stuck on "Finishing initial log read"

### ISSUE THREAD

**Issue by PhyrexianHulk** [Manuel-777/MTG-Arena-Tool#591]
After logging in, the application is stuck. I'v restarted multiple times and it's always the same.
![Capture](https://user-images.githubusercontent.com/8269391/65375741-d03dd980-dc66-11e9-8978-d3fb3d90c7d8.JPG)

**Comment by Manuel-777** [comment]
Please try the [Troubleshooting guide](https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md)
