### ISSUE TITLE
In economy tab, show cards earned through new NPE decks

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#596]
This will happen quite rarely and to be honest I'm quite unsure logs contains the information, but considering WotC took the end of only giving missing cards from precons/NPE decks, we can't know for sure which card we actually got from those.

Having it appear in the economy tab as for ICRs or drafts/sealed card pool would be quite nice.

**Comment by AnnanFay** [comment]
It should already show up in Economy screen.

If it did not show up for you can you confirm if the other messages appeared? Specifically the `UpdateBasicLandsSet` event.

![image](https://user-images.githubusercontent.com/766048/65782697-28cd1500-e146-11e9-829e-d060bb75f733.png)

**Comment by Porkepix** [comment]
> It should already show up in Economy screen.
> 
> If it did not show up for you can you confirm if the other messages appeared? Specifically the `UpdateBasicLandsSet` event.
> 
> ![image](https://user-images.githubusercontent.com/766048/65782697-28cd1500-e146-11e9-829e-d060bb75f733.png)

No it's not there. All I have is `Renewal.UpdateRenewalStatus` with the ten random rares of the renewal gift, nothing else.

Could this also be related to the missing NPE decks?
I only received the ten bicolor NPEs, none of the mono decks, and I've seen many people on Reddit in the same situation.

I can screenshot later on if you need so.

**Comment by AnnanFay** [comment]
> Could this also be related to the missing NPE decks?

Very likely.

**Comment by SabreCat** [comment]
I got an `UpdateStarterDecks` economy event today that showed up correctly.

**Comment by Porkepix** [comment]
> I got an `UpdateStarterDecks` economy event today that showed up correctly.

Me too. But I have no idea what those are about. I know for example that I had three missing ravlands I got on Eldraine update, and those are not in this update, so it looks like a different one…
