### ISSUE TITLE
Error parsing response.(get_database_version)

### ISSUE THREAD

**Issue by yugiohyzl** [Manuel-777/MTG-Arena-Tool#599]
then it's stuck,
![360截图20190928092124832](https://user-images.githubusercontent.com/55932140/65823525-80749900-e28a-11e9-84b2-7b257ff3e31f.jpg)

**Comment by Manuel-777** [comment]
Hi ! DO you happen to have set the cards language in chinese by chance?

**Comment by yugiohyzl** [comment]
> Hi ! DO you happen to have set the cards language in chinese by chance?

yes, it's normal until the ELD release
