### ISSUE TITLE
Unclickable deck(s)?

### ISSUE THREAD

**Issue by combataran** [Manuel-777/MTG-Arena-Tool#60]
I wanted to check the number of wild cards needed for an imported deck and somehow that one deck is unclickable(as shown in the gfy, the Mono Red Aggro). The others click fine, not sure what's causing this.

[https://gfycat.com/EasyInsidiousHousefly](gif)

**Comment by Manuel-777** [comment]
Probably something with an unknown card or an unexpected reading error, could you share the log files

**Comment by Manuel-777** [comment]
I believe this is fixed with [13f7a6dd](https://github.com/Manuel-777/MTG-Arena-Tool/commit/13f7a6dd9c54abe9dc776be0f89d110b4e94ce0d), appearently undefined thumbnails were causing decks to not be loaded at all.

**Comment by combataran** [comment]
I'll check when I get back from work.

**Comment by Manuel-777** [comment]
Its not on any release yet trough, but will be on the next update

**Comment by Manuel-777** [comment]
Fastest solution is to add a thumbnail to the deck within MTGA, that should fix it!

**Comment by combataran** [comment]
I'll give that a shot then.

**Comment by combataran** [comment]
You're right, that was the only deck without a thumbnail.
