### ISSUE TITLE
Mis-sized overlay window since 2.10.0

### ISSUE THREAD

**Issue by Fyren** [Manuel-777/MTG-Arena-Tool#601]
https://github.com/Manuel-777/MTG-Arena-Tool/commit/432b9cfa2f7bba7c9460b01f4df110d7daada43e breaks the overlay window sizing on my system.  I tried running 2.9.5, the last release before that commit, and the overlay window is properly sized for me.

On my system, the overlay window is created with a size of 32x27 and not the 5x5 that's specified.  If I call `getMinimumSize()`, it reports 32x27.  To test, I tried calling `setMinimumSize(5, 5)` and then `setSize(5, 5)` or `setBounds({width: 5, height: 5})` but neither resulted in the window actually changing from 32x27.  Maybe the issue is in Electron.

The overlay ends up staying that size forever because the new `isEntireOverlayVisible()` will always return true as it checks if the size is less than 10x10.

I'm not sure what info about my system is relevant.  I'm on Windows 7 with two displays.  The primary is 1920x1080 and the secondary is 1024x768.  The secondary is placed to the left of the primary with the top edges aligned.

**Comment by Manuel-777** [comment]
I supose we can stretch the size to check to 50x50 or something like that, The overlay size will not be lower than that anyway. I will push that and reference here for you to test.

Btw, are you running from source? so you can test the latest commits.

**Comment by Fyren** [comment]
I am running from source.  I tried changing the check, which makes the overlay visible, but the window isn't actually transparent.  Also, I can't resize the overlay using the edit mode.

I ran 2.9.5 again to test, and while I can resize in edit mode there, I still have the transparency problem.  I'm currently trying to find the newest version with no overlay issues for me.

**Comment by Fyren** [comment]
My transparency issue is that Electron requires Aero for it to work.  It seems to just silently give you a non-transparent window otherwise.  From https://electronjs.org/docs/api/frameless-window:

> On Windows operating systems, transparent windows will not work when DWM is disabled.

This really means you have to have Aero enabled.  I have Aero disabled, though dwm.exe is running.  If I enable Aero, then the overlay transparency works.

**Comment by lusbenjamin** [comment]
#670 may affect this
