### ISSUE TITLE
Enabling edit mode is unintuitive

### ISSUE THREAD

**Issue by dpdearing** [Manuel-777/MTG-Arena-Tool#602]
I'm running in a Windows VM through Parallels and I can no longer drag overlays around the desktop to reposition them.

This has been happening to me since around 2.9.3 or so (maybe earlier), but was fine previously.  I tried renaming my config file like the FAQ said, but no change except now they are in the default location and I still can't move them.

**Comment by AnnanFay** [comment]
In order to move overlays around you need to switch to edit mode. Either using the shortcut `Alt + Shift + E` or by clicking on the weird little coloured circle thing on an existing overlay.

![image](https://user-images.githubusercontent.com/766048/65928939-c438e100-e3f7-11e9-8811-4dc8aae663cb.png)

**Comment by dpdearing** [comment]
Thanks!  There have been a lot of little tweaks like this that aren't intuitive from the UI.

**Comment by AnnanFay** [comment]
> There have been a lot of little tweaks like this that aren't intuitive from the UI.

Yeah. I think this is still a valid bug. I'm going to reopen this for now and label as User Experience (UX). It's come up multiple times in the discord server as well.

Potential fixes for this are:

1. Hover over tooltip on edit button - text something like "Toggle Edit Mode (Ctrl + Shift + E)"
2. Cross out the entire screen as well as dim it. This is to make it clearer that you cannot do anything during edit mode - it's a temporary mode.
3. Add "Toggle Edit Mode" to the right click taskbar menu
![image](https://user-images.githubusercontent.com/766048/65999373-2bf13980-e495-11e9-904c-77e8da4ace74.png)
.
4. Add explicit "Edit Mode" button to the overlay settings screen. 
![image](https://user-images.githubusercontent.com/766048/65999335-18de6980-e495-11e9-92b9-ebce2afb551b.png)

**Comment by dpdearing** [comment]
I think the issue for me was that it wasn't even clear to me that an "Edit Mode" existed.  And normal GUI behavior is to just drag+drop a panel, so I didn't event think to look for a way to enable it.  Options 3 and 4 at least help with the issue of not knowing Edit Mode existed.

That said, once I got there it was really hard for me to use Edit Mode mid-game (because that's when the overlays show up) to adjust things.  All while my opponent is waiting for me to act and spamming "Your Go" as I fumble to move things and get out of Edit Mode with my timer burning.

Why does "Edit Mode" need to be a thing versus the old (and normal) drag behavior?  That (to me, anyway) was the source of the problem.

**Comment by Manuel-777** [comment]
The problem is the way the overlays are rendered. The old way used one process for each window and proven to be a disaster memory-wise.
Now instead, we draw one single transparent overlay
