### ISSUE TITLE
Uninstalled but every time I login on my computer the tool shows up

### ISSUE THREAD

**Issue by dragonman88** [Manuel-777/MTG-Arena-Tool#604]
Uninstalled but every time I login on my computer the tool shows up, please help.

**Comment by AnnanFay** [comment]
This is concerning. Can you provide more information?

1. Which version of Arena Tool are you running?
![image](https://user-images.githubusercontent.com/766048/66000087-9e164e00-e496-11e9-90e2-0e70619784b2.png)

2. How are you uninstalling it?

3. After uninstalling does it appear in the list of installed programs? ("Add or Remove programs" window)
![image](https://user-images.githubusercontent.com/766048/66000042-8b9c1480-e496-11e9-9958-406199382689.png)

4. Which Operating system and version are you using? Windows 10 Pro?

5. After trying to uninstall, what is the contents of `%localappdata%\Programs\MTG-Arena-Tool`?

**Comment by AnnanFay** [comment]
As it's been several days without a response I am closing this. We need more information to be able to figure out what is happening.

Please don't hesitate to reopen this issue if it keeps happening.
