### ISSUE TITLE
Program is hidden off-screen and unrestorable.

### ISSUE THREAD

**Issue by kayadash** [Manuel-777/MTG-Arena-Tool#605]
My MTG-Arena-Tool is hidden off-screen on a multi-monitor setup. I can't shift+right click on the icon in the start menu on MTGAT in order to "move" it as I could normally in this scenario. Cascading windows doesn't work. Making the window in focus and holding the windows key while hitting arrow keys doesn't move it like a normal window. I know the window is active as I can see its preview, however, nothing I try works, even uninstalling and reinstalling, disabling monitors, etc. Please advise.

It would be nice if the program could have normal functionality wherein right clicking on the window preview displays the dialogue box that allows for moving.

**Comment by kayadash** [comment]
Could use a response, the program is still entirely unusable for me. I can't even find the registry value in regedit to try and alter LastX/Y positions. Even registry information like that would be helpful, thank you.

**Comment by Manuel-777** [comment]
To edit the default position of the main window you need to go into `%APPDATA%/mtg-arena-tool/USERID.json` where USERID is your mtg arena userid (a random has of letters and number)
Once in the file seek for the "windowBounds" field and edit the x/y values.

The behaviour you describe is unusual trough, I will see if I can reproduce.

**Comment by kayadash** [comment]
Deleting the JSON restored the window. Thank you.
