### ISSUE TITLE
Import Card Ratings

### ISSUE THREAD

**Issue by drapela** [Manuel-777/MTG-Arena-Tool#608]
Please allow us to import card ratings into draft helper. Those that are there are nice, but I prefer ratings from top level players, rather than community aggregates. Even better if it would be possible to show multiple ratings from multiple (2-3) imported sources.

**Comment by AnnanFay** [comment]
Duplicate of #340 enhancement.

Feel free to discuss in that issue, or reopen if you think it is not a duplicate.
