### ISSUE TITLE
Show cards owned in a draft

### ISSUE THREAD

**Issue by andybergon** [Manuel-777/MTG-Arena-Tool#61]
I read about the draft tracker assistant in the present features. Where are the scores taken from. Can we have a screenshot of that UI?

**Comment by andybergon** [comment]
Apparently there is some info in this reddit thread: https://www.reddit.com/r/MagicArena/comments/8ww4j3/mtgatool_draft_helper_vault_gold_history/

Maybe worth adding it to the READMe?

**Comment by luxkun** [comment]
Not sure if this is the place to ask, but it would be grand to also have the number of cards we have of a particular card in our collection, since this is something that I think of when picking in draft.

**Comment by Manuel-777** [comment]
I will follow @luxkun suggestion and cards owned to the draft tracker as soon as I get to draft and test properly, its a pretty crucial piece of information missing in the tracker at the moment !
