### ISSUE TITLE
"Remember Me?" Not Working

### ISSUE THREAD

**Issue by Squints11** [Manuel-777/MTG-Arena-Tool#611]
The tool hasn't correctly "remembered" my password for at least a week now.  I've tried unchecking the box, logging in and out, logging in offline and then logging back in, I've even tried resetting my password through mtgatool portal.  Nothing has worked so far.  Any help?

**Comment by Lego6245** [comment]
Could you expand on "remembered"? Do you mean it didn't automatically log you in, and you had to click "login"? Or when you click login, it fails with invalid password? Just want to clarify what the problem is.

**Comment by Squints11** [comment]
It fails with an invalid password.

**Comment by Manuel-777** [comment]
Maybe the token that gets saved on your client gets revoked and thus, the password Field is emptied, are you logging in from another device with the same account ?

**Comment by Squints11** [comment]
I am not, I've also don't have multiple accounts.  I can't think of a reason why suddenly my password would be saved incorrectly after working fine for several months.

**Comment by Manuel-777** [comment]
Does your email have uppercase letters in it? Try using all lowercase once

**Comment by Squints11** [comment]
Hot Damn!  That worked.  Thank you.  Why was that messing up my password though?

**Comment by Manuel-777** [comment]
Not sure, but we recently changed how emails are used for authentication and emails with uppercase characters need to login at least once to update themselves.

**Comment by Sleepcap** [comment]
Ouch.
That was exactly my problem too...
All lowercase works perfectly.

**Comment by Thaoden** [comment]
Doesn't work for me, hoewever. I have to explicitly click "Login" every time I start the tool, even when changing my mail address to all-lowercase. When removing the "Remember me" checkbox, my password gets rejected...

**Comment by riQQ** [comment]
This should be solved, there were no more reports of this happening.
