### ISSUE TITLE
Overlay sideboard setting should be independent of main decklist

### ISSUE THREAD

**Issue by AnnanFay** [Manuel-777/MTG-Arena-Tool#615]
It's useful to show the sideboard during Bo1 games where you have a choice of playing a sideboard retrieval spell or doing something else. This bug has come up once or twice in the Discord server.

The mainboard often only has 8 different cards because you run full playsets and so they are easy to remember. The sideboard normally has 15 different cards, some of which are rarely played.

![image](https://user-images.githubusercontent.com/766048/66274837-6a626c00-e87a-11e9-9432-1918cd647d3f.png)

**Comment by Manuel-777** [comment]
I think the problem in that image is that you have "Show deck/lists" unchecked. It should not depend on that trough.
