### ISSUE TITLE
Contributing to the website?

### ISSUE THREAD

**Issue by TMiguelT** [Manuel-777/MTG-Arena-Tool#618]
There are some new features the website could use, particularly in terms of the metagame matchups and filtering. I don't suppose the frontend for the https://mtgatool.com is open source/available for contributions?

**Comment by Manuel-777** [comment]
I already have it shared with some contributors, and am looking into ways of making the CI work, so changes are updated more easily.

I am also looking into having someone audit it, before going wide open source.

**Comment by TMiguelT** [comment]
Ah, well I look forward for it to being open source. I'd like to find a way to calculate some more detailed metagame summaries.

**Comment by lusbenjamin** [comment]
https://github.com/mtgatool/mtgatool-web

**Comment by Manuel-777** [comment]
Do note the back end is still closed, but it will eventually be open if everything goes well.
