### ISSUE TITLE
Collection filter resets after any game event

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#622]
If you have a search or filter active on the Collection tab, doing anything in the Arena client causes it to reset back to default. I was trying to keep up a view of all my rares/mythics from a set for raredrafting purposes, but this behavior makes it difficult!

**Comment by lusbenjamin** [comment]
potentially solved in #835

**Comment by SabreCat** [comment]
A quick test says yes! It'll scroll back to the top if you're down the page a bit, but keeps the filters, which is the important part.
