### ISSUE TITLE
Add an option to exclude cards not in packs

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#628]
I'm referring here to the cards you can't find in packs and are locked to paper and digital preconstructed decks. It would be nice to have an option to hide those from collection, and to not count those from collection stats, so that we really know what's missing from packs.

However, I'm stuck at not knowing what to do from cards that can be found in packs, but only in sealed/draft (ie. common bilands; I don't think there are other cards in the same situation).

EDIT: I don't know if Eldraine common lands are in the same situation, I haven't opened any Eldraine packs yet.

**Comment by Manuel-777** [comment]
recently in 87ae453ac8771cf143b5bf9c2a94a990d47a14c8 I excluded the cards you cant open from boosters from collection stats, you can see it in latest pre release already (v2.12.0)

**Comment by Manuel-777** [comment]
Fixed in cec0a2ff50ab1937f9b96603c3fada8f78ab13fd
