### ISSUE TITLE
Economy sorting date incorrectly

### ISSUE THREAD

**Issue by QuinRiva** [Manuel-777/MTG-Arena-Tool#630]
The _Economy_ tab is sorting by date (MM-DD) instead of (YYYY-MM-DD): this results in economy events from last year appearing at the top of the list.

**Comment by Manuel-777** [comment]
Could you please send me your config file to mtgatool@gmail.com ? you can find it at `%APPDATA%\mtg-arena-tool`, a file named like `0A1F2E3E4D5C6B7A.json`
