### ISSUE TITLE
Collection Stats page is empty

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#633]
The Collection Stats page is empty in v2.12.1.

![grafik](https://user-images.githubusercontent.com/3404787/66777827-55b15400-eeca-11e9-880c-682fcc30dbd1.png)

**Comment by Manuel-777** [comment]
If you move to another tab then enter again does it populate?

**Comment by riQQ** [comment]
No, it doesn't help.

**Comment by Manuel-777** [comment]
Please press `Alt + Shift + D` and inspect the console tab of the windows for any red errors.

**Comment by riQQ** [comment]
> C:\Users\<omitted>\AppDat…n\collection.js:744 Uncaught ReferenceError: sets is not defined
    at printStats (C:\Users\<omitted>\AppDat…n\collection.js:744)
    at HTMLDivElement.<anonymous> (C:\Users\<omitted>\AppDat…n\collection.js:352)

> C:\Users\<omitted>\AppDat…n\collection.js:814 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
    at openSetStats (C:\Users\<omitted>\AppDat…n\collection.js:814)
    at C:\Users\<omitted>\AppDat…n\collection.js:804

**Comment by Manuel-777** [comment]
This is fixed by c84edd1c676a4c33c285e09f5cceda144648f3e0 , I will push a new prerelease asap!

**Comment by riQQ** [comment]
Confirmed working with v2.12.2.
