### ISSUE TITLE
Tool capturing clicks during drafts

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#637]
If you have the Tool up during an Arena draft, you can't interact with the display on which Arena is running. The first clue is that Arena's custom cursor disappears, replaced by the default Windows cursor. You then can't click on any cards or menus, with the only way out either force-closing Arena or quitting the Tool. If you quit Arena, the issue persists into the rest of the Windows environment, swallowing any clicks on browser windows etc. where Arena used to be.

**Comment by Manuel-777** [comment]
What version are you using? We did some changes to that since latest stable and trough pre releases

**Comment by SabreCat** [comment]
About page says
>Version 2.12.3
>Metadata: version 24, updated 10/12/2019, 9:20 AM

**Comment by riQQ** [comment]
Has been working for me for a long time.
