### ISSUE TITLE
Rat Colony's quirk doesn't work in the tool

### ISSUE THREAD

**Issue by Hamcha** [Manuel-777/MTG-Arena-Tool#64]
Rat Colony's effect "A deck can have any number of cards named Rat Colony." doesn't work well with MTGA Tool:

First, since the collection can contain at most 4 of any card, the tool thinks I'm missing cards to make the deck (even though it's in my collection already):
![Screenshot showing the "missing" error](https://i.imgur.com/aArAQoA.png)

Secondly, the Rat colony cards themselves don't appear in the visual spoiler at all:
![Screenshot of the visual mode missing rat colony cards](https://i.imgur.com/fA6qQJU.png)

**Comment by Manuel-777** [comment]
Could you supply the log files? as I dont have more than 4 rats to test this (I'm a good man!)

You can find the log at `%APPDATA%\..\LocalLow\Wizards Of The Coast\MTGA\` , please send it over at mtgatool@gmail.com
