### ISSUE TITLE
Include # of new cards of each rarity in your draft pool.

### ISSUE THREAD

**Issue by Lego6245** [Manuel-777/MTG-Arena-Tool#640]
As a drafter, while the current economy screen showing new cards gained from the draft pool is nice, there can be up to 45 of them. I'd like to see, at a glance, how many of each rarity I gained so I can measure how effective that draft was towards set completion.

**Comment by Manuel-777** [comment]
This is something that probably wasnt there when the issue was created;
![image](https://user-images.githubusercontent.com/4711391/82087059-c1100e00-96c5-11ea-8ae1-5decb1992b9c.png)
