### ISSUE TITLE
[Linux] Double click notification tray icon does't open the application

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#646]
Context informations:
Built from source (current master)
I currently try and move between different window managers or desktop environment. Current bug report is about issues I got with KDE/Plasma, and I guess X.org.

MTG Arena Tool is present in the notification tray, but double-clicking it doesn't open the application when it was reduced to notification tray. Instead the only way to open it is to right-click it and then click show.

**Comment by Porkepix** [comment]
After some more testing, this seems to depends on the Desktop Environment or Window Manager; while double clicking it on Windows open it, and KDE have aforementioned result, XFCE and Budgie open up the menu when left-clicking it, whether it is one or two times (same result as right click).
No systray icon for Gnome to check it. I can also do some testing with Awesome or i3/Sway if those support systray icons.

Can this be some upstream issue on Electron?

**Comment by Manuel-777** [comment]
The systray icon is a known issue on Gnome 3 (its on README), the user needs to install an extension to suport legacy icon trays. I am not sure if Electron will be updated to fix this, or even if it can.

However, I believe click support can be enabled, since apps like Discord work.. I have to figure out how.

**Comment by Porkepix** [comment]
Yeah, I knew about Gnome, just didn't installed it, my guess is that it's part of the GTK family as well as XFCE or Budgie, and that it's likely to have the same behavior.
I also forgot I can test Cinnamon aswell.

**Comment by Porkepix** [comment]
Also, just noticed this right now, only tested with KDE/Plasma, might test it with something else: systray icon becomes unusable during a game, both clicks does nothing.
