### ISSUE TITLE
Percent chance next booster has wanted rare can show NaN%

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#648]
See joined screenshot, noticed on master.
I own 100% of set's rare the screenshot was taken on, but not 100% of mythics.

![Screenshot_20191021_101505](https://user-images.githubusercontent.com/709500/67188083-eff22a00-f3eb-11e9-86b4-6d92867e0240.png)

**Comment by Porkepix** [comment]
To add to this, as I think even if I have absolutely zero JS skill I could get a look at that, I don't know what could be the best display for such case.
User won't get a rare in the booster pack as he owns all of them, but can still get a wildcard. Most of the time it's gonna be 20 gems. 0% is both right and wrong, 100% seems always wrong. The text could also be 100% replaced by something else.

**Comment by Manuel-777** [comment]
Please upload a full image (so we can see the filters, version number and all of the other variables that may affect the result of the data)

**Comment by Porkepix** [comment]
Sure, here it is:

![Screenshot_20191021_234528](https://user-images.githubusercontent.com/709500/67245840-3e8bdc80-f45d-11e9-80d7-7531d099a918.png)

But my guess is that it's just about https://github.com/Manuel-777/MTG-Arena-Tool/blob/ee65f2c1dca728a2e0edf98a64a903dba1a27799/src/window_main/collection.js#L897 resulting in a zero, therefore leading to a division by zero on https://github.com/Manuel-777/MTG-Arena-Tool/blob/ee65f2c1dca728a2e0edf98a64a903dba1a27799/src/window_main/collection.js#L898-L900.

But I didn't looked at it very thoroughly, plus I don't read JS easily :þ

**Comment by Lego6245** [comment]
My proposal:

We should not show the calculation of % chance a booster contains a rare if you 'want' 0 rares from that set. I think that ends up being the cleanest solution here.
