### ISSUE TITLE
Changing tab while "Explore" is loading will desync state

### ISSUE THREAD

**Issue by Hamcha** [Manuel-777/MTG-Arena-Tool#65]
Haven't looked at the code but I guess it may be some callback not detecting that the request was cancelled?

Here's a screencap:
https://gfycat.com/UnacceptableHoarseAlaskanhusky

To reproduce just:
1. Click on Explore
2. Click on anything else right away
3. Wait a bit

**Comment by Manuel-777** [comment]
This is a known one for me, I got too used to just *wait* until explore loads :P
Just have to cancel explore loading if the tab changes.

**Comment by Manuel-777** [comment]
Fixed for next release.
