### ISSUE TITLE
Card picture is missing for the five Magic Arena set basic lands

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#650]
This is probably *not* a MTG Arena Tool bug.
But I prefer to open it just in case, and because some people with better information could know where the bug belong to.

See screenshot for the issue.
![Screenshot_20191021_112309](https://user-images.githubusercontent.com/709500/67193674-fa192600-f3f5-11e9-9287-ca52db48330a.png)

For example for the plains, the url if user click on it is https://scryfall.com/card/ana/51/Plains. But the correct url actually is https://scryfall.com/card/ana/61/plains. So there is some issue with the set number.

PS: What's even more strange and that might actually go toward a MTG Arena Tool bug is that on another computer where I run stable release (2.11.0), there's a picture for the land, the link lead to ward the correct card on scryfall, *but* it seems to be the wrong one on the application (set icon seems to be wrong, however it's too small to recognize it precisely. But it definitely does not look like the Arena 'A').

**Comment by Lego6245** [comment]
Yeah, I was noticing this too. Thanks for investigating!

**Comment by Manuel-777** [comment]
Its a thing in the database, I will try to manually override the collector IDs with those!

Btw are those certainly the corresponding ones? (same art/artist)

**Comment by Porkepix** [comment]
I'm not sure I understood the question, but there might be some differences, actually for the frame rather than the art/artist for the example I have in mind: Unhinged basic lands are in Arena part of the Arena set (ANA). And here we have some inconsistencies: MTG Arena Tool displays the original frame from the paper card version (with a full rectangle art) rather than the real Arena one, visible on scryfall, which have curved top part of the art.

See 
![Screenshot_20191021_235816](https://user-images.githubusercontent.com/709500/67246403-ab53a680-f45e-11e9-9b6c-a2df5a44279e.png) as compared to https://img.scryfall.com/cards/large/front/5/2/52ce85a5-1a3e-41a6-8a2c-ac9f78286af3.jpg?1566788528

**Comment by Lego6245** [comment]
There's a similar problem where some cards that are marked as arena cards are linked against their paper counterparts (as in, searching for the card's arena ID brings up the paper version), and while the versions Arena uses are available on scryfall, you can't actually get to them using the Arena ID. Part of this is on Scryfall to more accurately map the "printings" of certain cards to their art, but some of it may be fixable with changes to how we build the database.

I know as a similar example, the Mirage lands all show the classic border, while in Arena they obviously use the more modern one.

**Comment by Manuel-777** [comment]
Obviously, as we dont render cards like Arena does, and I would not like to use custom images to match them. Therefore I find their paper counterparts and link them.

**Comment by Porkepix** [comment]
> Obviously, as we dont render cards like Arena does, and I would not like to use custom images to match them. Therefore I find their paper counterparts and link them.

What's strange though is that scryfall actually does have the real Arena image.

**Comment by Manuel-777** [comment]
Yes, but with a different collector's ID, thats why it fails in obtaining the image.

**Comment by Manuel-777** [comment]
Attemped to add the scryfall Arena lands in 16e5bef6f202e74deb43bb215881e60650454fd0 , but turns out they are already added! (see image below)
![image](https://user-images.githubusercontent.com/4711391/67256960-076afa80-f460-11e9-9760-4c777166b809.png)
These lands we have no images from are from random sets, here are the arena import codes;
`1 Plains (ANA) 51
1 Island (ANA) 52
1 Swamp (ANA) 53
1 Mountain (ANA) 54
1 Forest (ANA) 55`

**Comment by Porkepix** [comment]
What do you mean, that it's for new incoming lands?

These ones still don't appear here, but I'm not sure I did understand your comment and whether it needs to uncomment or do anything else than update the master.

![Screenshot_20191022_105524](https://user-images.githubusercontent.com/709500/67271367-a6bcdb80-f4ba-11e9-9706-1d38f6a72d3a.png)
