### ISSUE TITLE
"Erase my shared data" can result in error

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#651]
Currently running the master, I tried fiddling a bit at different places, and it seems this button does not work anymore.

Clicking it display a `Error parsing response. (delete_data)` error message, while logs contains the following lines:

```
IPC LOG:  SEND >> 0, delete_data, 4jSftJ, undefined
IPC LOG:  RECV << 0, delete_data, <br />
<b>Notice</b>:  Undefined index: token in <b>/var/www/html/api/delete_data.php</b> on line <b
IPC LOG:  httpAsync:
IPC LOG:  SEND >> 0, delete_data, reflSp, undefined
IPC LOG:  RECV << 0, delete_data, <br />
<b>Notice</b>:  Undefined index: token in <b>/var/www/html/api/delete_data.php</b> on line <b
IPC LOG:  httpAsync:
IPC LOG:  SEND >> 0, delete_data, fSsC8k, undefined
IPC LOG:  RECV << 0, delete_data, <br />
<b>Notice</b>:  Undefined index: token in <b>/var/www/html/api/delete_data.php</b> on line <b
IPC LOG:  httpAsync:
IPC LOG:  SEND >> 0, delete_data, z2ZfWD, undefined
IPC LOG:  RECV << 0, delete_data, <br />
```

The small ID seems to be different every time.

**Comment by Manuel-777** [comment]
Are you using offline mode? Your auth token seems to be undefined, wich is required to make server requests.

**Comment by Porkepix** [comment]
Yes it's with offline mode.
Thing is, when I did this on another computer months ago, it did works without any issue, and it already was with offline mode. It's also looks like MTG Arena Tool send data even without account by default, which is I think the reason this button was created at first?

If that's the case, on a side-note, I was wondering about the compliance about this regarding EU's GDPR: the general rule is to send nothing before any informed user consent.
