### ISSUE TITLE
No Icon in taskbar and in application launcher on Linux

### ISSUE THREAD

**Issue by Flecheck** [Manuel-777/MTG-Arena-Tool#675]
I've got no Icon in taskbar and in application launcher.

I'm on Linux using KDE with v2.12.6.

**Comment by Lego6245** [comment]
Similar to #646?

**Comment by Flecheck** [comment]
No, the icon work on the system tray but not in the task manager, the program is opened but it uses the default icon of my icon theme. Same in the application menu.

I also have the same problem as #646.

**Comment by Manuel-777** [comment]
Fixed in #1140
