### ISSUE TITLE
Stuck at "Downloading Metadata" screen for 8+ hours

### ISSUE THREAD

**Issue by combataran** [Manuel-777/MTG-Arena-Tool#68]
Woke up at 6am, opened Arena, reached main menu. Double clicked tool desktop shortcut. "Downloading metadata". Okay, I'll just get back to it when I'm off work. 8 hours later, back at PC. Still "downloading metadata". What gives?

Tried restarting the app, nothing changes. Gets stuck on the "downloading metadata" screen, this time for 20 minutes and counting. I've had this issue before, the only fix is to restart the PC.

**Comment by Manuel-777** [comment]
Close the app and start again. probably caused by an unhanded network error (metadata is 500kb only so it should be fast)
