### ISSUE TITLE
X to remove archetype tag does not save

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#682]
When you click the X to remove an archetype tag from a match in the History view, the tag appears to be removed, but when you leave the screen and return, the tag reappears.

This does not appear to happen when you use the X as part of a workflow to replace the automatically assigned archetype tag, but if you attempt to remove or edit a user-added tag, it doesn't save.

**Comment by riQQ** [comment]
This appears to be fixed. 
- removed the default tag
- added a custom tag
- restarted tool
- removed custom tag
- switched tab back and forth
- custom tag is gone as expected
- restartet tool
- custom tag is still gone as expected
