### ISSUE TITLE
Overlay Display don't work

### ISSUE THREAD

**Issue by Nju79** [Manuel-777/MTG-Arena-Tool#683]
I've two monitors and want the game showing on primary, the overlay the secondary. When I change the Display on Settings->Overlay->Overlay Display all Overlays are be shown on my primary monitor ->no matter what I set here.

In Edit Mode I can move the overlays, but only on the primary. It stucks at the border of the primary, so I can't move it to to secondary.

**Comment by paulternate** [comment]
I'm also able to reproduce this. I have 5 displays and used to be able to have overlays shown on "Display 4." However it seems with the latest update, even when setting the display to another monitor, all overlays still show on the main display. 

Let me know if there is anything I can do to help troubleshoot! Thanks for all the great work!

**Comment by TroubiCZ** [comment]
The same here, after the latest update, overlays are displayed only on my Display 0, regardless of the setting.

I found a partial workaround - when I turn overlays on/off (alt+shift+1), then click on the overlay title and then use Windows shortcut to move the window to other display (win+shift+right arrow), it *sometimes* work. But usually the procedure is too disturbing to me when I am concentrating on a match, and it work only from time to time anyway.

**Comment by Manuel-777** [comment]
Fixed in dev, it should be in next release!
