### ISSUE TITLE
Draft helper data sources

### ISSUE THREAD

**Issue by andybergon** [Manuel-777/MTG-Arena-Tool#69]
Have you thought about using scores from other sources for the draft helper like:
- [LSV set reviews](https://www.channelfireball.com/tag/lsvs-set-review/)
- [Draftaholics Anonymous P1P1](http://www.draftaholicsanonymous.com/p1p1-guilds-of-ravnica/)
- [Magic Community Set Review](https://www.mtgcommunityreview.com/guilds-of-ravnica)

instead of having to collect your own data to make the scores reliable?

**Comment by andybergon** [comment]
I personally use [this](https://docs.google.com/spreadsheets/d/e/2PACX-1vRnvsKgyZhZ1mTS3HQznUPzN3ekb3ZLPRfQ_oi6kFOxvLDyH_5E2R29XCxXm7zeJm24CKff4rll-Tfb/pubhtml#) pick order list that is a weighted average of the 3 previous one. It is done by [Frank Karsten in Channel Fireball](https://docs.google.com/spreadsheets/d/e/2PACX-1vRnvsKgyZhZ1mTS3HQznUPzN3ekb3ZLPRfQ_oi6kFOxvLDyH_5E2R29XCxXm7zeJm24CKff4rll-Tfb/pubhtml#). Going from google sheets to CSV to DB should be easier than the others.

Between the other three (except LSV that is not in tabular form or has an API in front) I would go with Magic Community Set Review that has an already human readable format `A+ to F` that is easily mappable to scores `0-10` or `0-5`.

**Comment by combataran** [comment]
https://www.mtgranks.com

Consolidated LSV scores here.

**Comment by Manuel-777** [comment]
I contacted with the people at magic community set review and they're okay with us using their ratings, and they even have it available as a csv with similar rating system to my own!
I will use that combined with my own data and probably switch to 'A-F' rankings

**Comment by Manuel-777** [comment]
Updated the database and app to display Magic Community set review rankings;
![image](https://user-images.githubusercontent.com/4711391/47609647-1c61a900-da19-11e8-9c47-ffd509cdf40d.png)
