### ISSUE TITLE
Clicking direct challenge entry in History doesn't show log

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#691]
Normally, clicking a match summary on the History tab takes you to a screen with your deck, the cards seen of your opponent's deck, and a human-readable version of the action log. Clicking a Direct Challenge match, however, changes the background as if the screen had transitioned, but doesn't actually take you away from the main History list.

**Comment by Manuel-777** [comment]
Is this still a problem? I cant reproduce atm, please reopen this still happens!
