### ISSUE TITLE
Application window off-screen

### ISSUE THREAD

**Issue by scardog59** [Manuel-777/MTG-Arena-Tool#710]
Hello,

Program is permanently minimized.  Auto runs on start-up, can see the program with my unique login when presesing win + tab.  Closing program and starting from exe file does truly open application.  No overlay is present when launching MTGA (11/11/2019).  I recently installed latest version 2.12.8, no update / change.  Have tried running MTGA tool as administrator.   Attached is what I see when pressing win + tab, but clicking the window does not open it.  It is like it is permanently minimized.  
![mtga tool ](https://user-images.githubusercontent.com/13386313/68621074-b610c280-0483-11ea-933d-c6915c11ed1c.png)

**Comment by Manuel-777** [comment]
Same as #92 (but with main window) and #605
