### ISSUE TITLE
Launch hangs with "output_log.txt contains no player data".

### ISSUE THREAD

**Issue by britishben** [Manuel-777/MTG-Arena-Tool#746]
This is with a fresh install of v2.13.3, Windows 10 x64. I suspect it's to do with today's update (different log format, maybe?). Removing `settings.json` as the FAQ says does not make a difference.

Stuck at the "Loading, just a moment screen" - I can cycle through the icons at the top, but the screen doesn't change. The username & ID are correct, but the ranks are both showing 0. The colour bar is looping, so it's not "frozen".

Dev console shows this:
```
C:\Users\bpmck\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt
http-api.js:186 SEND >> 0, get_database_version Object Object
http-api.js:235 RECV << 0 get_database_version {"latest":29,"lang":"en","updated":1574393851531,"size":2378228}
http-api.js:284 Downloading latest database (had v28, found v29)
http-api.js:186 SEND >> 0, get_database Objectlang: "en"method: "get_database"reqId: "OPHsJI"token: undefined__proto__: Object Objectheaders: {Content-Type: "application/x-www-form-urlencoded", Content-Length: 40}hostname: "mtgatool.com"method: "GET"path: "/database/en"port: 443protocol: "https:"__proto__: Object
http-api.js:235 RECV << 0 get_database {"cards":{"6873":{"id":6873,"name":"Crash of Rhinos","set":"Mirage","artid":1837,"type":"Creature Rhino ","cost":["6","g","g"],"cmc":8,"rarity":"common","cid":"210","frame":[5],"artist":"Steve White","dfc":0,"collectible":false,"craftable":false,"booster":true,"dfcId":false,"rank":0,"rank_values":0,"rank_controversy":0,"images":{"small":"/small/front/d/7/d74e0337-d9ac-4bf2-b2b5-aadc97433030.jpg?1562721929","normal":"/normal/front/d/7/d74e0337-d9ac-4bf2-b2b5-aadc97433030.jpg?1562721929","large":"

```

Let me know if you need any more info, or if there's something I missed.

**Comment by Thaoden** [comment]
Thanks for the report!

The latest game update changed the log formats and broke the tool. More information can be found on the [Discord](https://discordapp.com/channels/463844727654187020/463844728287395851/647157290746511371).

**Comment by BeckysFootSlave** [comment]
Also the 2.13.3 shows still 2.13.2 in the corner, but that is not a issue at all!
Hope the Tool works again soon :)

**Comment by Manuel-777** [comment]
[v2.13.4](https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/v2.13.4) is up with many fixes, still not stable 100% trough

**Comment by Just8Will** [comment]
Just an FYI. 2.13.4 downgrades itself to 2.13.2

**Comment by Manuel-777** [comment]
Will check! it was reported at #751
