### ISSUE TITLE
Draft pick and draft brew overlays are not working

### ISSUE THREAD

**Issue by gregersn** [Manuel-777/MTG-Arena-Tool#749]
v2.13.4 (currently latest) does not show contents in "Draft pick" and "Draft brew" overlays. 

Log sent on email.

**Comment by HalgrimThadeus** [comment]
see him posting on reddit [Manuel777](https://www.reddit.com/user/Manuel777/) that the whole log is broken. I guess that goes together.

**Comment by gregersn** [comment]
There are still issues here. 
Right now, for me, it say "pack 1 pick 1", displays what was on "pick 2", but I am on  "pick 3".

**Comment by gregersn** [comment]
Problem persists in v.2.14.0
