### ISSUE TITLE
Overlay not in line with display when in game using 2k resolution

### ISSUE THREAD

**Issue by ClawhammerLobotomy** [Manuel-777/MTG-Arena-Tool#763]
Since the update that removed choosing the monitor for the overlay, whenever I launch Arena, the overlays become off-center to my main display, and treat the "game area" as a combination of my other monitors.
This is what I see when in game and using the "Edit overlay positions" function.
![2019-11-25 20_39_01-MTGA](https://user-images.githubusercontent.com/6299800/69592426-d7b19400-0fc3-11ea-85a4-45940d40d766.png)

I've tried using the band-aid fix for "reset windows" from the taskbar.
If I reset the position while in a match, it will stay until I start a new game.

I have 4 monitors set up.
1 at 1920 x 1080
2 at 1080 x 1920 (portrait)
1 at 2560 x 1440 (Main display)

![2019-11-25 20_29_28-Settings](https://user-images.githubusercontent.com/6299800/69592016-9e2c5900-0fc2-11ea-9806-8684d4eee444.png)

**Comment by Manuel-777** [comment]
Hello! In `v2.14.0` I modified the overlays reset position arlgorithm (in settings > overlays) to reset to x=0 and y=0 of the promary/main display, is this the behaviour you see when you reset them?

**Comment by ClawhammerLobotomy** [comment]
Hi Manuel,

When I use the reset, it does go back to (0,0) but it seems to reset to a different position once in a game.

My in-game screenshot shows half the screen as dimmer, which is part of the overlay area of the tracker.
I can also see the overlay on my other monitors in this sort of pattern.
![image](https://user-images.githubusercontent.com/6299800/69593917-bb642600-0fc8-11ea-9672-d3d6c4ead0f7.png)
1. Overlay 1 (not actually able to see it, but I assume it is off screen like this)
2. Overlay 2 (shows in the middle of my secondary monitor
3. Card hover overlay

**Comment by lusbenjamin** [comment]
This is a great amount of detail in a bug report, thank you! Is your tool set to have overlay UI Scale = 100%?

**Comment by ClawhammerLobotomy** [comment]
I work in IT support, so I try to be as detailed as possible.

My UI Scale is set to 80%, but I have tried other scaling which didn't seem to change the behavior.
I just tried with 100% and it does the same.

Thanks

**Comment by Manuel-777** [comment]
It appears from the half-dimmed screenshot we are missing on the calculations to get the full display area and positions.

Can you open dev tools in any window? you can do it by pressing `Alt + Shift + D`, then on Console of any of them, paste this and press enter;
JSON.stringify(_electron.remote.screen.getAllDisplays())

![image](https://user-images.githubusercontent.com/4711391/69595029-06883400-0fdd-11ea-9548-a46f54e63a54.png)

We need the output of the command as shown in the screenshot to determine with exactitude how the algorithm is calculating the overlay area.

**Comment by ClawhammerLobotomy** [comment]
Here is what I get when I run this command
`"[{"bounds":{"height":1080,"width":1920,"x":347,"y":-1080},"id":2779098405,"rotation":0,"scaleFactor":1,"size":{"height":1080,"width":1920},"touchSupport":"unknown","workArea":{"height":1034,"width":1920,"x":347,"y":-1080},"workAreaSize":{"height":1034,"width":1920}},{"bounds":{"height":1920,"width":1080,"x":-1080,"y":-158},"id":2841568472,"rotation":270,"scaleFactor":1,"size":{"height":1920,"width":1080},"touchSupport":"unknown","workArea":{"height":1874,"width":1080,"x":-1080,"y":-158},"workAreaSize":{"height":1874,"width":1080}},{"bounds":{"height":1920,"width":1080,"x":2560,"y":-158},"id":2480450848,"rotation":90,"scaleFactor":1,"size":{"height":1920,"width":1080},"touchSupport":"unknown","workArea":{"height":1874,"width":1080,"x":2560,"y":-158},"workAreaSize":{"height":1874,"width":1080}},{"bounds":{"height":1440,"width":2560,"x":0,"y":0},"id":2528732444,"rotation":0,"scaleFactor":1,"size":{"height":1440,"width":2560},"touchSupport":"unknown","workArea":{"height":1394,"width":2560,"x":0,"y":0},"workAreaSize":{"height":1394,"width":2560}}]"`

**Comment by Manuel-777** [comment]
Could you check if this was resolved in `v2.14.2`?

**Comment by ClawhammerLobotomy** [comment]
Hi Manuel,

Doesn't seem like the update fixed it.

Now, it seems like the overlay area is taking up all of my monitors.

I'm no longer able to reset the overlay positions to see the trackers either.

In the `main.js` file, function `overlaySetBounds()` is giving the following results from the console.log function.
`Overlay bounds:  -1080 -1080 4720 2842`

It appears the math.min function being done is causing the x and y values to be -1080 in my case.

I believe that changing the function to be the following might work?
It outputs what I believe to be what should work for my case at least.

`function overlaySetBounds() {`
  `const newBounds = { x: 0, y: 0, width: 0, height: 0 };`
  `electron.screen.getAllDisplays().forEach(display => {`
    `newBounds.x = Math.min(Math.abs(newBounds.x), display.bounds.x);`
   ` newBounds.y = Math.min(Math.abs(newBounds.y), display.bounds.y);`
  `});`
  `electron.screen.getAllDisplays().forEach(display => {`
    `newBounds.width = Math.max(`
     ` newBounds.width,`
    `  Math.abs(newBounds.x) + display.bounds.width`
   ` );`
   ` newBounds.height = Math.max(`
   `   newBounds.height,`
  `    Math.abs(newBounds.y) + display.bounds.height`
 `   );`
`  });`

The main parts of change are
    `newBounds.x = Math.min(Math.abs(newBounds.x), display.bounds.x);`
    `newBounds.y = Math.min(Math.abs(newBounds.y), display.bounds.y);`
`Math.abs(newBounds.x) + display.bounds.width`
`Math.abs(newBounds.y) + display.bounds.height`

**Comment by Manuel-777** [comment]
Being at -1080 is fine, since you have negative coordinates in some of your displays, it *should* cover all of them, that is correct.

Can you try resetting the overlays position from the button the `Settings > Overlays`, scroll to the bottom, each overlay has its own reset button.

**Comment by ClawhammerLobotomy** [comment]
Ah, I see what you're doing now with the overlay area. That makes sense then.

I have tried resetting all of the overlays via this method.

It seems that they go to the -1080, -1080 position, so I am not able to see them or move them afterwards.

**Comment by Manuel-777** [comment]
Is this working as expected now? Please reopen if not! It's been a while

**Comment by ClawhammerLobotomy** [comment]
Manuel,

Unfortunately, it still seems like the reset function is putting the overlays at -1080, -1080 position rather than 0,0.

I'm able to get around it by increasing the UI scale to 200%, moving them off the invisible part of my overlay area, then reducing the size again.

It no longer resets itself, so I've been doing okay with it for now.
