### ISSUE TITLE
Prefer to not install to C:

### ISSUE THREAD

**Issue by Evilvonbek** [Manuel-777/MTG-Arena-Tool#769]
Any chance of a version that can be installed to a non OS drive, or preferably to a specifically set Partition of choice?

I prefer to literally have nothing but Profiles and minimal Data on the OS drive to the point most of the possible other stuff is DIRLinked to a separate drive that isn't the OS one.

**Comment by Evilvonbek** [comment]
Curious why it's been closed without any explanation.

For many people having to install to OS drive is a major bugbear, especially if they are using SSDs.

**Comment by Manuel-777** [comment]
We are currently not configuring the installer in any way due to our updater process using the same installer, which might conflict if the user changes the settings (I am not sure to deploy it), I might come back at this at some point but not in the near future.
