### ISSUE TITLE
2.14.2 metadata 37 has lost deck and overall history

### ISSUE THREAD

**Issue by Magican28** [Manuel-777/MTG-Arena-Tool#774]
Hi
The win/loss of each deck was shown yesterday, plus win/loss overall. Neither is showing now. 
The economy tab has updated ok (new vault value is good) so it is reading the log
Ta

Update - tonight it has started reporting history of the decks I have just played, but the historic info for all the other decks and overall is missing

**Comment by lusbenjamin** [comment]
I am hoping that this is just another example of one of the common "usability bugs" in the tool. By any chance, do you have your current time filter set to "Current Season"? What do you see when you change it to "All Time"?

**Comment by Magican28** [comment]
Brilliant, fixed thanks
The new version must have altered that setting
