### ISSUE TITLE
Can't reset password on MTG Arena Tool website

### ISSUE THREAD

**Issue by ianelletson** [Manuel-777/MTG-Arena-Tool#78]
Created an account but unable to reset the password to access it, since I use a password generator.
Also, I don't see a privacy statement for how the emails will be used.

**Comment by Manuel-777** [comment]
Hello,

Send me the email you used to sign up and the new password so I can change
it manually.

I still haven't updated the policies, but it's used to identify different
users with real authentication, later I will add data recovery and some
rank/leaderboards and stuff like that.

**Comment by Manuel-777** [comment]
https://mtgatool.com/resetpassword/
