### ISSUE TITLE
MTG-Arena-Tool Has Broken

### ISSUE THREAD

**Issue by BanditoP** [Manuel-777/MTG-Arena-Tool#79]
I started MTG-Arena_tool 2.1.14 at the same time as MTGA, which caused it to mess up the output.log file. I then exited everything, and renamed the output.log file, launched MTGA, waited, then launched MTG-Arena-Tool. Now, MTG-Arena-Tool has almost no information in it. "My Decks", "History", "Events", "Explore", "Collection" all show nothing, though "Economy" seems to work. This problem persists in online and offline mode.

I uninstalled the tool, renamed everything in AppData, renamed output.log, restarted my computer, downloaded the installer, reinstalled the tool, launched MTGA, waited, then launched MTG-A-T, but the problem persists.

**Comment by Manuel-777** [comment]
I believe this issue is caused because you may have a deck with an undefined image as deckbox art, something like a double faced card or a split card art the tool may not be handing correctly

**Comment by BanditoP** [comment]
I changed the art on all of my decks, even the precons, then renamed output.log and relaunched mtga, but the app is still broken. Previously I had my decklist show up on launch (non-interactable) and then vanish when swapping tabs, but I renamed the cache to test if bad art was in there, and the decklist stopped showing at all, so it seems it's just not getting new information somehow.

**Comment by Manuel-777** [comment]
Probably, I would need both output_log and your user .json to be sure, if you can please send at mtgatool@gmail.com (I am working on it now and I would like to have it fixed today)
