### ISSUE TITLE
Missing cards in oppo deck

### ISSUE THREAD

**Issue by DarkHarlock** [Manuel-777/MTG-Arena-Tool#796]
I have this list where there is no evidence of Lochmere Serpent in the oppo deck
![image](https://user-images.githubusercontent.com/9002914/70957641-11cbfe00-2077-11ea-8357-96504ea215f0.png)
but in the game log I can see
![image](https://user-images.githubusercontent.com/9002914/70957766-78511c00-2077-11ea-824a-2d6c421af00b.png)

This card was put into the graveyard by oppo at the end of a couple of turns before as it was the 8 (no logs for this in the list), and then activated.

EDIT: 
My current version is:
![image](https://user-images.githubusercontent.com/9002914/70961209-65434980-2081-11ea-9a9f-e07531dedecb.png)

**Comment by Manuel-777** [comment]
Sounds like Tool missed the part where it went into the graveyard the first time, do you remember how that happened?

**Comment by DarkHarlock** [comment]
Oppo discarded the serpent at the end of the turn because it was the 8° in his hand.
