### ISSUE TITLE
Draftsim values not shown?

### ISSUE THREAD

**Issue by lupuleasa-core** [Manuel-777/MTG-Arena-Tool#80]
Hi,

The draft overlay was showing "Undefined" for scores for me.
Is this a new issues?
I understood this tool shows pick suggestions in arena, am I wrong?

Thanks,
Lup.

**Comment by Manuel-777** [comment]
That is correct, what version are you using?

**Comment by Alkwer** [comment]
I also have this problem, overlay is showing up correctly but all values of grades of cards are set to "undefined".

**Comment by Manuel-777** [comment]
If you are on 2.1.14 I would find useful a sample of the ouput_log file located at `%APPDATA%\..\LocalLow\Wizards Of The Coast\MTGA\` , send at mtgatool@gmail.com (to not share publicly)

**Comment by lupuleasa-core** [comment]
will look into it after work, currently I block my games during work hours

**Comment by Manuel-777** [comment]
@lupuleasa-core any news on this one?

**Comment by lupuleasa-core** [comment]
Haven't checked it since then
