### ISSUE TITLE
Error importing deck from www.mtgatool.com

### ISSUE THREAD

**Issue by LuckyBlack72** [Manuel-777/MTG-Arena-Tool#824]
lately it's impossible to import decks from www,mtgatool.com
I always have error like the one in attacched screenshoot , no matter which deck I try to import
![Screenshot_1](https://user-images.githubusercontent.com/42611122/71553888-126d7880-2a17-11ea-8aba-237142ee6c7c.jpg)

**Comment by Manuel-777** [comment]
This was fixed, please reopen if you're still having issues!
