### ISSUE TITLE
More detailed breakdown of win/loss vs colour combinations

### ISSUE THREAD

**Issue by oseparovic** [Manuel-777/MTG-Arena-Tool#85]
Having pie charts showing how you fare vs individual colours only shows part of the picture. If you could see for example a bar chart with Y axis being win % and X points being each different colour combination you faced you could see more info about what weaknesses your deck has.

For example the current deck I'm playing does fairly well vs GR, WG and G but terribly vs UG merfolk deck. As a result my win loss for green is basically even so a bunch of information is lost by clustering into single colours.

MTG Arena Pro does something similar by showing wins and losses as separate side by side bar graphs for each colour

![clipboard01](https://user-images.githubusercontent.com/3710226/47967857-048cb500-e017-11e8-94ae-fe20d2e595d5.png)

**Comment by Manuel-777** [comment]
I made some progress for this, how it would look like currently:
![image](https://user-images.githubusercontent.com/4711391/47975765-f29a2900-e08d-11e8-8128-f5de9dad765b.png)

I think it needs some sort of horizonal metric to know at least what the winrate for each color pair is , but it looks much better this way than before

**Comment by oseparovic** [comment]
This is awesome 👍

**Comment by Manuel-777** [comment]
Done for the next release, you can try pre-release version 2.1.17 to see it in action! :D

**Comment by oseparovic** [comment]
Just downloaded it to try it. Looks great :)
![clipboard01](https://user-images.githubusercontent.com/3710226/48216112-b2aa9e80-e338-11e8-974b-90df31f8b2e6.png)
