### ISSUE TITLE
Lost data on next launch

### ISSUE THREAD

**Issue by Knorrke** [Manuel-777/MTG-Arena-Tool#850]
I played some games with a new deck yesterday and checked the statistics afterwords in the MTG-Arena-Tool (The new view there is amazing btw 👍). Everything looked fine then, but when I restarted it today, all those games were gone, as well as the economy logs of the rewards.

How does that happen? Maybe I didn't close MTG-Arena-Tool correctly?

**System Information**
MTG-Arena-Tool: Version 3.0.2, Metadata Version 43, updated 01/18/2020, 4:52 AM
running the precompiled version, no other trackers running
Windows 10 1909 (Build 18363.592)

**Comment by riQQ** [comment]
The same happened to me, although not everything from the economy tab is gone. The mastery pass purchase and the corresponding events are still there.

**Comment by Knorrke** [comment]
Lost data again today :-/ This time a traditional draft i played yesterday is gone from all tabs, history, events, economy... I also checked the filters, but it's set to "All time" and "All Events". The data was there after the draft, because I remember checking the draft replay and the economy tab.

Can I do something to help debug this @Manuel-777?

**Comment by Manuel-777** [comment]
Yes, please send your config files to mtgatool@gmail.com, you can find the path to them in settings (sorry I can't be more specific, not at my PC)

**Comment by lusbenjamin** [comment]
I am so sorry that you are losing data! 😿
- I honestly have no clue what is going on here. This may be a difficult one to diagnose.
- It could potentially be related to the remote sync feature. Are you a Patreon supporter with that feature enabled?
- It could potentially be caused by a poorly handled race condition in the background processes that snuck its way into v3.0.2. I recommend upgrading to v3.0.3 by enabling "Settings" >> "Behavior" >> "Beta updates channel" or manually installing the latest.

**Comment by Knorrke** [comment]
>     * It could potentially be related to the remote sync feature. Are you a Patreon supporter with that feature enabled?

No, I'm logged in to my mtgatool.com account, but am no patreon supporter yet.
 
>     * It could potentially be related to some of our known issues with multi-Arena accounts. Do you swap between more than one Arena account?

No, only one account.

>     * It could potentially be caused by a poorly handled race condition in the background processes that snuck its way into v3.0.2. I recommend upgrading to v3.0.3 by enabling "Settings" >> "Behavior" >> "Beta updates channel" or manually installing the latest.

I'll try that, thanks. Will let you know if it helped. I've send an email with the files maybe that helps as well. Thanks again for looking into this :-)

**Comment by Knorrke** [comment]
Seems to be fixed, the last days everything worked fine :-) I'll reopen this if it happens again, but for now: Thanks for the fix! :-)
