### ISSUE TITLE
Lost game data after starting MTGA when MTG-Arena-Tool was not running

### ISSUE THREAD

**Issue by budu** [Manuel-777/MTG-Arena-Tool#856]
I've played two game today with MTG-Arena-Tool running. The games stats were showing in MTG-Arena-Tool and everything looked fine. Here's a rundown of what I did afterward:
* I quit MTG-Arena-Tool (to fix another issue)
* Started MTGA (meant to restart MTG-Arena-Tool and did that by mistake)
* Closed MTGA
* Started MTG-Arena-Tool

Then the two games I played just before disappeared. Everything else is fine.

**Comment by Manuel-777** [comment]
Hello!

Could it be a filters issue? Try changing to all time or back and forth.
Tool doesn't erase data so if it was displayed in history, it was stored and should still be there.

**Comment by budu** [comment]
Tried changing the filters and the games are still not there.

Is it possible these were just never written to the games data file?

**Comment by Manuel-777** [comment]
Could be, but not if they ever appeared in history tab, since they are read from the stored data.

**Comment by Manuel-777** [comment]
Btw, this could be related to #850 ?

**Comment by budu** [comment]
They definitely appeared in the history tab. In fact, I did what I did because I was looking at the history for those matches and realized something was off with the matchups stats.

I had a quick look at your code and it looks great, I'll see if I can reproduce the bug and look for a cause. 

As for #850, it is hard to say.

**Comment by budu** [comment]
I wasn't able to reproduce the issue.
