### ISSUE TITLE
Error importing deck from www.mtgatool.com

### ISSUE THREAD

**Issue by LuckyBlack72** [Manuel-777/MTG-Arena-Tool#857]
The issue  #824 , I opened and now is closed , isn't fully fixed because now importing a deck doesn't give error and for MTGA is successfully imported but showing it , It isn't fully imported , but only 4 cards as you can see in the screenshot
![Screenshot_1](https://user-images.githubusercontent.com/42611122/72866880-3aca5900-3cdd-11ea-8eff-61280364f80a.jpg)

**Comment by LuckyBlack72** [comment]
i found why the deck isn't imported, it's because the list missing the expansion and number tag, see the following

--Export from MTGA Tool Site (incorrect) --

4 Agent of Treachery
3 Arboreal Grazer
1 End-Raze Forerunners
3 Cavalier of Thorns
4 Leafkin Druid
4 Risen Reef
3 Uro, Titan of Nature's Wrath
4 Thassa, Deep-Dwelling
4 Nissa, Who Shakes the World
7 Island
4 Breeding Pool
1 Castle Vantress
1 Fabled Passage
4 Temple of Mystery
3 Finale of Devastation
10 Forest

2 Shifting Ceratops
2 Cerulean Drake
1 Return to Nature
2 Mystical Dispute
1 Shadowspear
1 Destiny Spinner
1 Narset, Parter of Veils
2 Brazen Borrower
1 Thassa's Intervention
2 Thrashing Brontodon

-- Export from MTGA Zone (Correct )-- 

3 Aether Gust (M20) 42
4 Bonecrusher Giant (ELD) 115
2 Castle Vantress (ELD) 242
4 Cavalier of Flame (M20) 125
1 Cavalier of Gales (M20) 52
4 Deafening Clarion (GRN) 165
2 Elspeth Conquers Death (THB) 13
3 Fabled Passage (ELD) 244
4 Fires of Invention (ELD) 125
4 Hallowed Fountain (RNA) 251
2 Island (ANA) 62
3 Kenrith, the Returned King (ELD) 303
2 Mountain (ANA) 64
1 Plains (ANA) 61
3 Sacred Foundry (GRN) 254
4 Sphinx of Foresight (RNA) 55
4 Steam Vents (GRN) 257
4 Teferi, Time Raveler (WAR) 221
3 Temple of Epiphany (M20) 253
3 Temple of Triumph (M20) 257

4 Devout Decree (M20) 13
3 Legion Warboss (GRN) 109
4 Mystical Dispute (ELD) 58
4 Tithe Taker (RNA) 27

**Comment by LuckyBlack72** [comment]
the issue is still unresolved, and so is impossible to import in an automatic way from site to MTGA

**Comment by riQQ** [comment]
Exporting from the website and importing in Arena works for me. The export now includes the set and the number.
