### ISSUE TITLE
Explore tab broken/not working correctly?

### ISSUE THREAD

**Issue by max1c** [Manuel-777/MTG-Arena-Tool#858]
How is the explore tab supposed to work? It doesn't seem to be updating at all. It's showing all of the old decks regardless of how you sort. Is this a bug?

**Comment by tobiaslory** [comment]
I must agree, data seems unchanged since release of TherosBD, couldn't find any deck containing cards from the new set. Apparently some problem with the automatic data collection/transfer?

**Comment by brandorf** [comment]
Explore tab for me is missing its color filter as well.

**Comment by max1c** [comment]
This looks like it's resolved. Closing.
