### ISSUE TITLE
Fresh Installation Hangs at "Downloading metadata"

### ISSUE THREAD

**Issue by DirtyMetis** [Manuel-777/MTG-Arena-Tool#86]
Tried both 2.1.15 and 2.1.16, install and launch, hangs at "Loading: Just a second..." and "Downloading metadata screen

![image](https://user-images.githubusercontent.com/18152297/48040790-ff775500-e13f-11e8-93a7-7a1b7941fe3c.png)

**Comment by Manuel-777** [comment]
Hi @DirtyMetis ! Could you please follow the steps in the [troubleshooting guide](https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md)? 

This has been reported by a couple users today already, and I would love to have a fix up today!

**Comment by DirtyMetis** [comment]
Heya--

Started doing so but wanted to ensure I was testing with the release version (2.1.15) so I uninstalled my previous one (2.1.16) and reinstalled .15 and it booted right up.  I'll include my output_log copy for reference, but it appears to be working fine now. /shrug

--Nate
________________________________

**Comment by Manuel-777** [comment]
Just to make sure it's not a bug with 2.1.16, could you install it again and see if it fails again?

**Comment by DirtyMetis** [comment]
Confirmed working with 2.1.16 installation as well
