### ISSUE TITLE
Gold shown at economy tab starts at +1000

### ISSUE THREAD

**Issue by Azzimutt** [Manuel-777/MTG-Arena-Tool#87]
Hello, first off all thanks for developing this tool, it's awesome!
I've noticed that in the economy tab, the gold that shows per day beside the green arrow (earned gold) is always starting at +1000 even if I didn't complete the daily quests yet. And when I start getting the daily quest's gold it adds to the +1000. So is that a bug??.
Inside each day is computing it right, and the loss gold per day is right too.

Thanks a lot,
Sorry for my english, cheers!

**Comment by Manuel-777** [comment]
Hi @Azzimutt , I would need your user config file to see what's wrong, you can find it in appdata as described [here](https://github.com/Manuel-777/MTG-Arena-Tool/blob/master/TROUBLESHOOTING.md)

**Comment by Manuel-777** [comment]
The .Json config mainly, the log would be nice but not required

**Comment by Manuel-777** [comment]
@Azzimutt I reviewed the file but found no errors? this is what I get;
![image](https://user-images.githubusercontent.com/4711391/48164416-332db880-e2c1-11e8-8fd8-9e176833ea58.png)

Or maybe I am missing something obivous?

**Comment by Azzimutt** [comment]
I don't know if that image correspond to my profile, I have had 100 gems for the past week or so, not 5. After I rename the .json file and run mtgatool again the problem solved.

**Comment by Manuel-777** [comment]
> I don't know if that image correspond to my profile, I have had 100 gems for the past week or so, not 5. After I rename the .json file and run mtgatool again the problem solved.

The above values are from my profile actually (since the log I tested with was mine), the history below is yours trough.

**Comment by Azzimutt** [comment]
I don't know how to explain it, but in the case of that image the gold earned was 2975, initially without doing nothing the "today" (yesterday in the image) already had 1000 next to the green arrow, and 0 next to the red one. So when I started to get the gold from the quest it showed as quest gold, and it added to the +1000. But when I rename and deleted the .json file now when I start mtga tool, the "today" tab dosen't show up until I earn some gold, and it shows it correctly.
