### ISSUE TITLE
Cannot track some items when arena language is not English

### ISSUE THREAD

**Issue by theincluder** [Manuel-777/MTG-Arena-Tool#885]
I'm playing mtg arena in Korean, and the tool cannot track some important items such as:
- match date
- opponent's deck and color
- won or lost
- action log
- hands drawn and shuffled order
(successfully tracked when i played Arena in English)

while it can still successfully track:
- my deck, economy, collection
- occurence of each event
- opponent's ID

Can you update your tool for foreign language users?

![asdf](https://user-images.githubusercontent.com/48241718/73765799-673fa400-47b8-11ea-8f53-0118df77bb3b.png)

**Comment by Manuel-777** [comment]
Closing as this is a very old issue and cant reproduce it anymore, the logs have changed substantially since then.
