### ISSUE TITLE
Card counter goes to -1 after bounce

### ISSUE THREAD

**Issue by andybergon** [Manuel-777/MTG-Arena-Tool#89]
![image](https://user-images.githubusercontent.com/5220825/48172337-69862a80-e2f7-11e8-8124-138e88e215a9.png)

Deck card counter for cards that are bounced to the hand goes to `-1`.

**Comment by Manuel-777** [comment]
Having the counter stay at zero does not fix this unfortunately. The card is being substracted as if multiple copies were on the battlefield at the same time, so there is probably something wrong with the object destroy count in GreToClient processing.
