### ISSUE TITLE
Collection Tab Does Not Load

### ISSUE THREAD

**Issue by cayniarb** [Manuel-777/MTG-Arena-Tool#904]
When I try to navigate to the Collection tab, it goes to a blank screen (just the background and the header/tab bar).  The Collection tab does not get highlighted as though it is selected until I click the Collection tab button again, but even then, it does not load.  There is no 'loading...' message or anything else, just nothing.

I've tried resetting both the output_log.txt and user profile .json files without any success.

Version 3.0.7

**Comment by rramstad833** [comment]
I am having the exact same problem.  Collection tab doesn't work at all.

Typically when I click on Collection nothing happens.  Occasionally when I click on Collection I get the Economy tab instead i.e. Economy is highlighted and the data for that tab is shown instead.

**Comment by rramstad833** [comment]
Any chance of this being addressed anytime soon?  It's a real bummer for those of us trying to complete the new set...

**Comment by cayniarb** [comment]
Appears to be resolved in version 3.0.8.

Thanks!
