### ISSUE TITLE
Have a "getting started" guide for the new user

### ISSUE THREAD

**Issue by liberforce** [Manuel-777/MTG-Arena-Tool#91]
I installed MTG-Arena-tool today, latest stable version (2.1.15).

The first time I installed it, I had some (unrelated) network issues when first logged in, so I chose to import offline. I could see only my last 2 games from today.
So when I fixed my network issues, I uninstalled the mtga-tool, moved the associated stored data from %APPDATA%, and reinstalled.

The second time I installed it, I did the import online, but still only had my last 2 games. I wondered If I had to have MTG Arena running on the background, so I ran it. Still no luck and only had my 2 last games. I closed MTG Arena, and uninstalled MTG-Arena-tool.

The third time I installed it, I did the import online, but this time the history was completely empty. This seems due to the fact that I had run MTG Arena just before.

Are you able to get the whole history? Is that from local data, or do you get it from the MTG Arena website?

If you need some logs, please tell, I'll attach them to this bug report.

**Comment by Manuel-777** [comment]
Game history is only local, that is, only records whenever you have Mtgatool running and is saved locally in your PC
Removing appdata will cause you to lose your settings and history.

**Comment by liberforce** [comment]
Ok, so you mean MTG-Arena-tool needs to be always running while I play to record my games?
This also means I don't need to use my MTGA credentials?

At first I thought I had to login using my MTGA credentials to get the game history from WotC servers...
Unless I oversaw it, there's not much information on the website, on the application itself, nor the README.md about how this is supposed to work. So I think this is an area for improvement :)

**Comment by Manuel-777** [comment]
Oh no, MTGA servers are their own only, I have no access there.

I guess a FAQ would solve this
