### ISSUE TITLE
Error while accessing collections [ubuntu]

### ISSUE THREAD

**Issue by AlbertCoca** [Manuel-777/MTG-Arena-Tool#925]
Everything else works fine, just when I click to "collection" i get this error.

I'm using Ubuntu 18.04 LTS.

### How to reproduce the error:
This happens to me with a fresh install. 
The error is introduced in the version 3.0.7. 
The version 3.0.6 works fine.
**Remove ~/.config/MTG-Arena-Tool folder to reproduce the error fresh install** if the ~/.config/MTG-Arena-Tool folder is generated with an older version the error can not be reproduced

![Screenshot from 2020-03-15 17-38-18](https://user-images.githubusercontent.com/20433529/76705886-d1b30080-66e3-11ea-9b2b-15c040e66315.png)

### Commands I have done:
```
git clone https://github.com/Manuel-777/MTG-Arena-Tool
npm install
npm start
```

### The logs I get:
```
XXXXXXXX:~/MTG-Arena-Tool$ npm start

> MTG-Arena-Tool@3.0.8 start /home/XXXXXX/MTG-Arena-Tool
> npm run build && electron .


> MTG-Arena-Tool@3.0.8 prebuild /home/XXXXXXX/MTG-Arena-Tool
> npm run clean:lib


> MTG-Arena-Tool@3.0.8 clean:lib /home/XXXX/MTG-Arena-Tool
> rimraf lib


> MTG-Arena-Tool@3.0.8 build /home/XXXXX/MTG-Arena-Tool
> babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files

[BABEL] Note: The code generator has deoptimised the styling of /home/XXXXXX/MTG-Arena-Tool/src/window_background/messages_pb.js as it exceeds the max of 500KB.
Successfully compiled 154 files with Babel.
linux
Attempted to load extension "React Developer Tools" that has already been loaded.
MAIN:  Initializing
IPC LOG:  Downloading metadata en
IPC LOG:  Initial log parse: arenaId=HHEAABLK6RDOZJBIEF2ARQ3B7I
IPC LOG:  Initial log parse: name=DzSom#43843
IPC LOG:  Database up to date (53), skipping download.
IPC LOG:  Load player ID: HHEAABLK6RDOZJBIEF2ARQ3B7I
IPC LOG:  Player database: /home/XXXXXX/.config/MTG-Arena-Tool/DzSom#43843.db
IPC LOG:  Checking if database requires upgrade...
IPC LOG:  ...no legacy JSON data, skipping migration.
IPC LOG:  Finding all documents in player database...
MAIN:  Updating settings
IPC LOG:  ...found all documents in player database.
IPC LOG:  Starting Arena Log Watcher: /home/XXXXXX/.wine/drive_c/user/XXXXXX/AppData/LocalLow/Wizards of the Coast/MTGA/output_log.txt
IPC LOG:  Calling back to http-api...
IPC LOG:  ...called back to http-api.
IPC LOG:  Checking for sync requests...
IPC LOG:  Fetch remote player items
IPC LOG:  Log read in 0.079s
MAIN:  Updating settings
Gtk-Message: 17:53:57.977: GtkDialog mapped without a transient parent. This is discouraged.



^C
```

**Comment by Manuel-777** [comment]
Could you checkout and pull `develop` branch see if it works? I think this is a problem we fixed there already.

**Comment by AlbertCoca** [comment]
Hi I just checkout develop but i get another error:
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-devtools-installer'
Require stack:
- /home/albert/MTG-Arena-Tool/lib/devtools.js
- /home/albert/MTG-Arena-Tool/lib/main.js
- /home/albert/MTG-Arena-Tool/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Function.Module._resolveFilename (/home/albert/MTG-Arena-Tool/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:27)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/albert/MTG-Arena-Tool/lib/devtools.js:10:58)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
`
My HEAD points to this commit:
`
commit d85a5157b41b55f307f0eeb62a4c62324787d6ab (HEAD -> develop, origin/develop)
Author: Manuel Etchegaray <manuel.etchegaray7@gmail.com>
Date:   Mon Mar 16 17:55:19 2020 -0300

    Dont re-add %%Active separator
`

**Comment by Manuel-777** [comment]
Sorry, I didn't mention you have to `npm install` again when checking out since there are new packages in `develoo`

**Comment by AlbertCoca** [comment]
Sorry of course npm install... 
Now it works! Thanks! 

btw nice changes ;)
