### ISSUE TITLE
Explore => Events => Eventslist too crowded.

### ISSUE THREAD

**Issue by Sleepcap** [Manuel-777/MTG-Arena-Tool#928]
There are a lot of really old events listed in the dropdown menue.
It should only show the most recents events (Maybe the last 2 month).
Or put the most recent (alphabetical) on top than a separator and all the others below.

**Comment by Manuel-777** [comment]
This is in dev;
![image](https://user-images.githubusercontent.com/4711391/76711614-63286f80-66f0-11ea-8846-5043f6147636.png)

There is an "archived" separator below the active ones that contains the old events in alphabetical order. Currently we are not saving the date of the events eto sort them by date trough.
