### ISSUE TITLE
(Linux) Changing log location in settings causes hang

### ISSUE THREAD

**Issue by Dunkhan** [Manuel-777/MTG-Arena-Tool#938]
Expected:
When changing the log location on the settings screen, the application asks to restart. It is expected that after clicking ok the app restarts, or at least quits, and then on next start loads the new logs.

Actual: 
The application window disappears, but the application is still running, it spawns a bunch of threads. The mouse cursor stays as the hand icon that it had from mousing over the ok button. Further mouse clicks on the operating system have no effect rendering the mouse unusable.

Workaround:
If you have this behaviour you can get your mouse back with terminal (ctrl-alt-t) and then using the top command and the kill command kill all the mtgarena tool processes.

To get the application to register the log location change (killing the processes resets it) set it to an invalid location, i.e a random string. Restart mtg arena tools. On startup it will ask again what file to use. You can enter the filename in this window and it will work correctly

Notes:
Linux Mint
detailed logs was NOT enabled in mtga, this could be a contributing factor
It is not clear that the app would not have started working again if I had waited, I only gave it 5 minutes so it could have been working on the log in the background. Even if this is the case breaking the users mouse is still a problem.

**Comment by Manuel-777** [comment]
Might have been fixed in the latest betas? I cannot see this behaviour

**Comment by Dunkhan** [comment]
I haven't been able to either. No reason to leave this open unless someone else has the same issue. Please anyone reopen if this is the case.
