### ISSUE TITLE
Error: User not found

### ISSUE THREAD

**Issue by Looking4OffSwitch** [Manuel-777/MTG-Arena-Tool#94]
I've been using MTG Arena Tool for weeks now and I love it. I saw [this ](https://github.com/Manuel-777/MTG-Arena-Tool/issues/75) issue and perhaps you are doing maintenance again but I wanted to make you aware, just in case. I've been getting a ["User not found" error](https://imgur.com/a/sN8kk3A) for the past two days. Again, everything has been working great for weeks.

Clicking the gear icon doesn't do anything (i.e. the settings views do not become visible). I'm running the latest version on a fully up-to-date Windows 10 machine. I've re-installed the tool (and rebooted) multiple times.

**Comment by Manuel-777** [comment]
Hi @Looking4OffSwitch ! We have actually run out of disk space on the server, so I'm looking into it now, sorry for this, ill let you know if its fixed!

**Comment by Looking4OffSwitch** [comment]
Thank you for the super prompt response. I don't see a patreon link anywhere... I'd be happy to make a donation if it would help to "keep the lights on".

**Comment by Manuel-777** [comment]
I am considering that as I solve this issue haha, thank you !

**Comment by Looking4OffSwitch** [comment]
Also, I'm a retired software engineer (Apple, MS, Intel). I have a ton of time on my hands if you could use any help. I see the Roadmap in the Readme but that isn't super specific; are you maintaining a feature request, low-hanging fruit bug list, etc. anywhere?

**Comment by Manuel-777** [comment]
I am following suggestions here in GitHub and on our [discord server](https://discord.gg/K9bPkJy) and follow the other issues if you would like to contribute, currently there are no actual high-priority features to implement, so I am mostly bug-fixing lately.
Also [patreon is up](https://www.patreon.com/mtgatool) :D

**Comment by rmangino** [comment]
Got it - thanks! I haven't looked at how you are storing data but I was thinking about making an iOS client so that I could look at my collection, history, etc. on the go.

Yup, I started a patreon pledge. ;-)
