### ISSUE TITLE
Economy view doesn't show Haversack of Favor when it resolved to XP

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#943]
If you get 500 XP through a Haversack of Favor, the economy view doesn't reflect this.

Version 3.0.8

**Comment by lusbenjamin** [comment]
Can confirm this is a problem, but not sure how to fix yet. When I dug into the logs, it appears this is due to the fact that the Haversack of Favor only gives us an `InventoryUpdate` for the non-XP rewards. 😿

**Comment by lusbenjamin** [comment]
Disregard my previous comment, I just tried today's workshop and it worked fine???
![image](https://user-images.githubusercontent.com/14894693/77355310-78f5f000-6d01-11ea-82e6-2105096cf141.png)

**Comment by Manuel-777** [comment]
Odd, I cant see it in `develop` neither ?

**Comment by Thaoden** [comment]
![Capture](https://user-images.githubusercontent.com/3832723/79789732-f2a5eb80-834a-11ea-8373-e94ec8212289.PNG)

working here
