### ISSUE TITLE
[Linux] Crash on startup with 3.1.0 release, and mouse interactions interception.

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#946]
I couldn't copy the error message, but could screenshot it:

![Screenshot from 2020-03-23 22-32-01](https://user-images.githubusercontent.com/709500/77365745-ee3fe000-6d56-11ea-816f-c954d0f411c6.png)

It's the error that happens on current master with `v3.1.0` on startup. It also breaks mouse usage for every other window, only letting keyboard working.

Environment: ArchLinux, running latest Gnome on Wayland.

Here's also the exception found in console during the `npm start`:

```
[BABEL] Note: The code generator has deoptimised the styling of /home/clement/repositories/MTG-Arena-Tool/src/window_background/messages_pb.js as it exceeds the max of 500KB.
Successfully compiled 200 files with Babel.
linux
Reading /home/clement/repositories/MTG-Arena-Tool/node_modules/electron-react-devtools/manifest.json failed.
Error: ENOENT: no such file or directory, open '/home/clement/repositories/MTG-Arena-Tool/node_modules/electron-react-devtools/manifest.json'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at getManifestFromPath (electron/js2c/browser_init.js:4026:26)
    at Function.BrowserWindow.addExtension (electron/js2c/browser_init.js:4448:22)
    at Function.BrowserWindow.addDevToolsExtension (electron/js2c/browser_init.js:4480:40)
    at App.<anonymous> (electron/js2c/browser_init.js:4509:23)
INSTALLING DEV TOOLS..
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Added React Developer Tools
Added Redux DevTools
```

**Comment by Manuel-777** [comment]
Have you run `npm install` after pulling?
if so, I can try setting up again an Arch machine see if it works

**Comment by Porkepix** [comment]
Yes, full `npm install` on latest master. It even downloaded itself electron.

**Comment by Porkepix** [comment]
By the way, and because I think ArchLinux might be quite long to install and cause some difficulties for anyone not used to - even if wiki is of a great help here - I think that the beta of Fedora 32, available here: https://getfedora.org/workstation/download/ should offer similar environment while a lot easier and quicker to install if needed (the latest Ubuntu to come, 20.04 might also be).

If you really want the same environment and test on Arch, or for me to conduct such tests, feel free to reach me here or on IRC/Matrix :)

**Comment by Porkepix** [comment]
@Manuel-777 Actually, as the fix involve a file named `electron-transparency-mouse-fix.js`, I don't know if this is a permanent fix or not. I prefer to reopen and let you decide about whether it have to be closed now or not.

**Comment by Manuel-777** [comment]
We can close it, the second error is probably something in the developer tools configuration (they are configured automatically via a library)

**Comment by Porkepix** [comment]
@Manuel-777 Actually, I didn't tested as I should for the overlay, and have some issues around it, some might deserve other issues to open here, please tell me about those. Before, bear in mind that I still (sadly), mainly play from a Windows computer due to how sluggish MTGA is on Linux (Wine required) and that due to that I didn't used often MTG-Arena-Tool on Linux, as well as I have issues with overlays on Windows for different reasons which makes it difficult to use for me (among them, uncommon screen resolution). Due to that, I'm unsure of what the behavior should actually be.

Now for what I think are the issues: Overlay correctly displays once we start a game. However, it stays visible on top of every single window, not only MTGA one. I think it also have to do with the fact that Wayland + Wine layer might make it quite difficult to deal with.
The overlay normally have buttons, but it's not possible to use those: this doesn't work.

When the overlay is triggered, it also hides the main window. Problem is that you have no way to bring it back while the overlay is here, and if for example for whatever reason you need to kill MTGA, then you're stuck with the overlay and the only way to get rid of it is to grab your terminal and go kill the process.
