### ISSUE TITLE
Unable to log on

### ISSUE THREAD

**Issue by Sashweed** [Manuel-777/MTG-Arena-Tool#96]
Created user a few days go but now its saying "User not found" 

Wont let me create a new user either. When I click create it just loops.

**Comment by Manuel-777** [comment]
Hello @Sashweed, today we will be experiencing some server issues, you can continue in offline mode in the meantime until it's solved, sorry for the troubles!  :(

**Comment by Sashweed** [comment]
yep .. working now.

Maybe a msg to say servers are offline instead of "user not found" might help
