### ISSUE TITLE
UI is missing the scroller when a lot of cards a gained in an event

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#978]
Version 4.0.2, see below:
![2020-04-04 20_15_12-MTG Arena Tool](https://user-images.githubusercontent.com/3404787/78458389-275e4580-76b1-11ea-9504-433d86bd9909.png)

**Comment by Manuel-777** [comment]
Fixed in 4.0.4

**Comment by riQQ** [comment]
Confirmed
