### ISSUE TITLE
4.0.4 Issue - Black Screen on Event Tab

### ISSUE THREAD

**Issue by LuckyBlack72** [Manuel-777/MTG-Arena-Tool#980]
When you switch to event tab, the screen became black , and you have to quit the app, but when you restart it return to event tab... so it's am infinite loop

**Comment by Manuel-777** [comment]
Hello !

Coud you please check in dev console for errors? Just press `Alt + Shift + D` when the tool is running (after the black screen has happened) and inspect the devtools window, in the "Console" tab for any red errors.

**Comment by LuckyBlack72** [comment]
![Screenshot_arena](https://user-images.githubusercontent.com/42611122/78827022-bf766a80-79e2-11ea-8a10-ac83457afaff.jpg)

attached there a screenshot of developer console, there is a json parse error

**Comment by max1c** [comment]
Same issue with the latest release here 4.0.15 
![image](https://user-images.githubusercontent.com/11587156/79671566-19242500-8199-11ea-98c1-366f74d06861.png)

**Comment by Kannagimoe** [comment]
Same issue here for me. Black Screen on login now. I cannot use the tool at all.

![bug](https://user-images.githubusercontent.com/5789081/79678799-f9bbe500-81f6-11ea-936d-af7b9057afc4.jpg)
