### ISSUE TITLE
4.0.4 windows version error "could not find log"

### ISSUE THREAD

**Issue by LuckyBlack72** [Manuel-777/MTG-Arena-Tool#982]
since the 4.0.3 version there is an error when mtga-tool starts, the app ask for log location , i never changed it , arena log are in default location , but when the app start it says that couldn't find log ,  in the popup which appears. i select the latest arena log, but when the log changes , the app request again to choose log, in previous version never happened

**Comment by Manuel-777** [comment]
Could you check if this is fixed for you on latest version? A fix was pushed already.
