### ISSUE TITLE
Drafts are not completed

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#985]
Version 4.0.6.

Events are not completed. 

- drafts are only marked as completed after a restart of MTGA Tool
- the record is only updated after a restart of MTGA Tool
- open-ended events like the FNM event are never marked as completed

![grafik](https://user-images.githubusercontent.com/3404787/79075840-7fbac600-7cf5-11ea-9a03-a37b256f64c2.png)

**Comment by Manuel-777** [comment]
Maybe fixed in `develop`, fix will be up on next beta.

**Comment by riQQ** [comment]
Workshops still show as in progress

**Comment by Manuel-777** [comment]
I think Workshops are unique in that they never really end once you enter them..

**Comment by riQQ** [comment]
For Workshops see #1011
