### ISSUE TITLE
Login button does nothing (2.1.18)

### ISSUE THREAD

**Issue by smgoller** [Manuel-777/MTG-Arena-Tool#99]
Uninstalled, reinstalled multiple times. The output_log.txt exists in the MTGA directory. Logging in offline works, and I see info from the log. There's no feedback from the UI, just a button that looks like it's being clicked, but does nothing.

**Comment by BanditoP** [comment]
Can confirm I am having this issue as well. It worked previously in this version but seems to be non-functional today.

**Comment by trolder** [comment]
ver 2.1.18 Was logging in yesterday for me. But not today.

**Comment by Manuel-777** [comment]
Hello guys. The server had maintenance today and several changes. Please update to [2.2.0 ](https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/2.2.0) and try again (it should work normally now)
