### ISSUE TITLE
output_log.txt contains no player data v3.0.8

### ISSUE THREAD

**Issue by fractalsonfire** [Manuel-777/MTG-Arena-Tool#992]
As per title.

I suspect this is due to the Ikoria update. Should i just use the 4.0.xx versions?

**Comment by flasaracina** [comment]
I have the same problem. Have WOTC devs changed the structure of the log file AGAIN?

**Comment by Thaoden** [comment]
They did. 

A fix is being worked on.

**Comment by fractalsonfire** [comment]
4.0.10 fixes any log issues if you don't care about a stable version.

**Comment by flasaracina** [comment]
@Thaoden @fractalsonfire  thanks for the reply. I can only imagine the amount of work needed to make the software comply to the new spec. I really appreciate the effort put in this MTGArena Tool.

I'll wait for a stable version because I don't want to take the risk of losing progress. Anyway, when do you expect the 4.0 version to become stable? 

Keep up the good works! Thanks

**Comment by bauris-prvt** [comment]
I am using ubuntu linux. I had the above mentioned issues with the 3.0.8 (stable) client after Ikoria released yesterday. I switched from the 3.08 appimage to the 4.0.10 appimage. MTG arena tool is working again. Parsing the log seems to have been the issue for me.
Although i can see the usuall console output from parsing the matches, none of the matches show in the 'History' tab. The most recent matches in the 'History'-tab are from my last Theros-logs it seems.
The other client tabs, e.g. 'My Decks', 'Economy', 'Collection' seem to be in order. I can see obvious deck changes from Ikoria, reward info and booster data is present and accurate and the collection is up-to-date with my most recent cards.
This seems to be a minor issue, nothing back-breaking at this point.

Thx for beeing on top of things as usual <3

**Comment by thisguy23** [comment]
I love this tool WotC needs to calm down on the log changes

**Comment by riQQ** [comment]
This will be fixed with the next 4.x release. For now, you can use a 4.0.12 or higher pre release.

**Comment by Thaoden** [comment]
Closing as this should be fixed in `4.0.15`.
