### ISSUE TITLE
4.0.14 'History' tab, match duration '0:00 long'

### ISSUE THREAD

**Issue by bauris-prvt** [Manuel-777/MTG-Arena-Tool#998]
4.0.1x seems to have introduced data output issues concerning the display of 'match duration' on the 'History' tab. All my Ikoria matches are displayed with 'match duration' == 0:00 in the 'History' tab.
I noticed it just now, with version 4.0.14. It might have also affected the other 4.0.1x versions I was running after the Ikoria release (4.0.10, 4.0.12)

**Comment by Manuel-777** [comment]
It's a know one, not limited to Linux. The place we get that data from on the logs was removed, we're looking into new options!

**Comment by Manuel-777** [comment]
Fixed in v4.0.18

**Comment by riQQ** [comment]
Implemented by #1009
